### ISSUE TITLE
GitLens code shortcut conflicting with python unittest code shortcut.

### ISSUE THREAD

**Issue by matheusssilva** [eamodio/vscode-gitlens#529] opened 2018-10-16 20:38 UTC
- GitLens Version: 8.5.6
- VSCode Version: 1.28.1
- OS Version: Linux Mint 19

Steps to Reproduce:

1. Configure [python unittest](https://code.visualstudio.com/docs/python/unit-testing)
2. Create a python teste case.
3. Install and configure GitLens

The GitLens shortcut overlaps on the python unittest shortcut. In order for the python unittest shortcut to reappear, just disable gitlens.

With GitLens:
![com_gitlens](https://user-images.githubusercontent.com/7414956/47045604-99636780-d169-11e8-81a9-fea2fbada34c.png)

Without GitLens:
![sem_gitlens](https://user-images.githubusercontent.com/7414956/47045614-9ff1df00-d169-11e8-958f-92a28680a81c.png)

[Python unittest tools](https://github.com/Microsoft/vscode-python) is development by Microsoft.

**Comment by bramsvs** [comment] 2018-10-30 13:29
Can confirm this. 

Quick workaround while keeping GitLens active is disabling the GitLens code lens in `settings.json`:
```
 "gitlens.codeLens.enabled": false,
```

**Comment by bramsvs** [comment] 2018-10-30 13:44
Also check this: https://github.com/eamodio/vscode-gitlens/issues/60#issuecomment-429549737

> Recently pytest and vs-code were fixing the python unittest lens, probably their solution didn't take into account working with GitLens.
Microsoft/vscode-python#2347
Microsoft/vscode-python#2663

**Comment by khurom** [comment] 2019-03-16 21:58
I can confirm this also. At the moment I'm segregating my work -- when I work on testing I disable GitLens, but for most of the time I will keep it on. As I do not need the GitLens decorations as much I think I will disable this particular feature as @bramsvs suggested.

**Comment by milsto** [comment] 2019-08-22 10:30
I am confirming this issue is affecting me also. VSCode version 1.37.1, GitLens version 9.9.3

**Comment by eamodio** [comment] 2019-11-11 20:09
Duplicate of https://github.com/eamodio/vscode-gitlens/issues/439

**Closed by eamodio** 2019-11-11 20:09 UTC
Labels: status: duplicate
