### ISSUE TITLE
Line toggle/pop

### ISSUE THREAD

**Issue by wsmelton** [eamodio/vscode-gitlens#129] opened 2017-08-12 18:16 UTC
- GitLens Version:4.3.3
- VSCode Version: 1.15.0 (x64)
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. All extensions are disabled except for Git Lens
2. Just open a file from GitHub repository

![gitlens_linepop](https://user-images.githubusercontent.com/11204251/29243258-18fd6ce6-7f60-11e7-86c8-50d9d8fd083d.gif)

Is there any way to disable the extension from making the line pop out?

**Comment by wsmelton** [comment] 2017-08-13 03:12
I'll confirm that this is strictly an issue with the 64-bit version of VS Code. I had 32-bit running on a Windows 2016 Server and did not see this issue. I removed the 32-bit and installed 64-bit version, as soon as GitLens loaded it started doing the same thing as above.

**Comment by eamodio** [comment] 2017-08-13 13:57
@wsmelton Are you using a non-monospace font? That is the only way I can reproduce this. I'll have to dig into this a bit more, but it really seems like a vscode bug. For now one way to stop this behavior would be to disable the line blame setting `"gitlens.blame.line.enabled": false`.

Hope that helps!

**Comment by eamodio** [comment] 2017-08-14 01:39
Opened https://github.com/Microsoft/vscode/issues/32436

**Comment by eamodio** [comment] 2017-08-15 00:12
@wsmelton That is the font you are using in vscode when you see the issue? If so I'm quite confused because the vscode change that caused this behavior was already in effect for monospace fonts

**Comment by wsmelton** [comment] 2017-08-15 11:47
Yes that is the font I have set.

**Comment by eamodio** [comment] 2017-09-12 23:11
Closing this as it is a vscode issue.

**Closed by eamodio** 2017-09-12 23:11 UTC
Labels: vscode issue
