### ISSUE TITLE
Revision navigation doesn't work after release 11.0.0

### ISSUE THREAD

**Issue by PaulLitvin** [eamodio/vscode-gitlens#1213] opened 2020-11-26 12:24 UTC
I have an issue with navigation to previous commits. Just shown popup with message 'There is no previous commit'.
But it works fine when I use previous release version 10.2.3

Can anybody help how to fix it?

**Comment by artkravchenko** [comment] 2020-11-26 13:28
I'm experiencing the issue too while clicking on the "Open Changes with Previous Revision" button. The extension doesn't detect revisions before the file rename. The "File History" panel doesn't show commits before the rename as well.

It all works fine on 10.2.3. @PaulLitvin, thank you for a tip!

**Comment by eamodio** [comment] 2020-11-28 07:02
@PaulLitvin @artkravchenko When you experience this is it always with renamed files? I can't seem to reproduce the issue with the _Open Changes with Previous Revision_ command. But not showing renames by default in the _File History_ view is a by-design change in v11 (because Git rename detection can cause all sorts of other history issues). You can easily toggle it from the view: 
![image](https://user-images.githubusercontent.com/641685/100495860-7e6fc980-311d-11eb-92ff-e008dd8c0302.png)

Or by setting `"gitlens.advanced.fileHistoryFollowsRenames": true` in your `settings.json`

Outside of the _File History_ view, and the `Show File History` command, there shouldn't be a change in behavior when navigating through history. Can both of  you please enable output channel logging by setting `"gitlens.outputLevel": "debug"` in your settings. This will enable logging to the *GitLens* channel in the *Output* pane. Once enabled, please reproduce the issue and attach the log from the *GitLens* channel.

**Comment by intellix** [comment] 2020-11-28 22:17
I've noticed this on all of my files as well. Sometimes clicking it takes me to a further back commit and I have to click forwards afterwards. Other times it says there are no changes at all, but funnily enough the File blame shows multiple commits

<img width="1091" alt="Screenshot 2020-11-28 at 22 17 06" src="https://user-images.githubusercontent.com/1162531/100527149-753b3700-31c7-11eb-96a2-1c462c200b1b.png">
<img width="615" alt="Screenshot 2020-11-28 at 22 17 20" src="https://user-images.githubusercontent.com/1162531/100527152-7c624500-31c7-11eb-81f1-33e851d76dc3.png">

This file: cloudbuild.json never changed it's name

**Comment by eamodio** [comment] 2020-11-29 05:06
@intellix 
Can you please enable output channel logging by setting `"gitlens.outputLevel": "debug"` in your settings. This will enable logging to the *GitLens* channel in the *Output* pane. Once enabled, please reproduce the issue and attach the log from the *GitLens* channel.

**Comment by intellix** [comment] 2020-11-29 21:59
```
[2020-11-29 21:58:31:457] [21ed] GitUri.fromUri — e=Uri(file:///Users/dom/Projects/gitlab/www/cloudbuild.json)
[2020-11-29 21:58:31:457] [21ee] GitService.getRepoPath — e=Uri(file:///Users/dom/Projects/gitlab/www/cloudbuild.json)
[2020-11-29 21:58:31:457] [21ef] GitService.getRepository — e=Uri(file:///Users/dom/Projects/gitlab/www/cloudbuild.json), t={"skipCacheUpdate":true}
[2020-11-29 21:58:31:457] [21f0] GitService.isTracked returned true • 0 ms — e=/Users/dom/Projects/gitlab/www/cloudbuild.json, t=/Users/dom/Projects/gitlab/www, i={"skipCacheUpdate":true}
[2020-11-29 21:58:31:457] [21ef] GitService.getRepository returned /Users/dom/Projects/gitlab/www • 0 ms
[2020-11-29 21:58:31:457] [21ee] GitService.getRepoPath returned /Users/dom/Projects/gitlab/www • 0 ms
[2020-11-29 21:58:31:457] [21ed] GitUri.fromUri returned GitUri(file:///Users/dom/Projects/gitlab/www/cloudbuild.json repoPath=/Users/dom/Projects/gitlab/www) • 0 ms
[2020-11-29 21:58:31:457] [21f1] GitService.getPreviousDiffUris — e=/Users/dom/Projects/gitlab/www, t=GitUri(file:///Users/dom/Projects/gitlab/www/cloudbuild.json repoPath=/Users/dom/Projects/gitlab/www), i=undefined, n=0
[2020-11-29 21:58:31:457] [21f2] GitService.getStatusForFile — e=/Users/dom/Projects/gitlab/www, t=cloudbuild.json
[2020-11-29 21:58:31:488] [/Users/dom/Projects/gitlab/www] git status --porcelain=v2 --find-renames -- cloudbuild.json • 30 ms 
[2020-11-29 21:58:31:488] [21f3] GitStatusParser.parse completed • 0 ms
[2020-11-29 21:58:31:489] [21f2] GitService.getStatusForFile completed • 31 ms
[2020-11-29 21:58:31:489] [21f4] GitService.getPreviousUri — e=/Users/dom/Projects/gitlab/www, t=GitUri(file:///Users/dom/Projects/gitlab/www/cloudbuild.json repoPath=/Users/dom/Projects/gitlab/www), i=undefined, n=0, o=undefined, r=false
[2020-11-29 21:58:31:537] [/Users/dom/Projects/gitlab/www] git log --format=%x3cr%x3e%x20%H -n3 --follow --first-parent --name-status -- cloudbuild.json • 48 ms 
[2020-11-29 21:58:31:537] [21f4] GitService.getPreviousUri completed • 48 ms
[2020-11-29 21:58:31:537] [21f1] GitService.getPreviousDiffUris completed • 79 ms
[2020-11-29 21:58:31:538] ShowMessage(info, 'There is no previous commit.', suppressCommitHasNoPreviousCommitWarning, {"title":"Don't Show Again"})
```

**Comment by eamodio** [comment] 2020-11-30 03:56
@intellix what happens if you remove the `--first-parent` rather than the `--follow`

**Comment by eamodio** [comment] 2020-11-30 04:08
Can you please try out the latest insiders version? It has a possible fix for this issue 🤞 

You can install the insiders version from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders).

**Comment by intellix** [comment] 2020-11-30 11:03
yep without first-parent:
```
<r> 549c52b0622adf2dfd15fe3592e743aeb509714e

M       cloudbuild.json
<r> ca04243b7c0238b07e2c3abedb6a2326a2fe29c5

M       cloudbuild.json
<r> 2636b7e950e920b005f2caa95458c6db212bf676

M       cloudbuild.json
```

**Closed** 2020-12-06 07:22 UTC
Labels: status: pending stable release, status: verified, type: bug
