### ISSUE TITLE
GitLens disables merging CodeLens

### ISSUE THREAD

**Issue by CoenraadS** [eamodio/vscode-gitlens#319] opened 2018-03-20 09:15 UTC
- GitLens Version: 8.1.1
- VSCode Version: 1.21.1
- OS Version: Windows 10

Steps to Reproduce:

1. Use VSCode as mergetool

GitLens enabled:

![image](https://user-images.githubusercontent.com/5593825/37645558-8a5f4368-2c27-11e8-864a-d53d0750dd23.png)

GitLens disabled:
![image](https://user-images.githubusercontent.com/5593825/37645608-a529dbe0-2c27-11e8-8a63-8f901395b807.png)

**Comment by eamodio** [comment] 2018-03-20 14:49
I can't reproduce this behavior, nor should it be possible for GitLens to conflict with any other code lens. When this occurs can you open the devtools (*Developer: Toggle Developer Tools* from the command palette) and see if there are any errors in the console and post them here? And when you say GitLens disabled, do you mean uninstalled? Code lens turned off?

**Comment by CoenraadS** [comment] 2018-03-20 16:02
Disable = disabled via extension manager

The dev console is empty

Here is a screenshot of all my extensions disabled but gitlens:

![image](https://user-images.githubusercontent.com/5593825/37666714-84173040-2c60-11e8-8b30-1714268437d6.png)

**Comment by CoenraadS** [comment] 2018-03-20 17:46
I can't reproduce on my other machine either. I'll take a deeper look tomorrow

**Comment by eamodio** [comment] 2018-03-20 17:49
Thank you for the update! Let me know.

**Comment by eamodio** [comment] 2018-04-19 05:24
I've seen this actually happen myself (once), but saw no errors or issue related to GitLens. Once I restarted vscode it fixed itself. Very strange.

**Comment by CoenraadS** [comment] 2018-04-19 05:56
It still happens for me everytime at my work pc, but I don't really have any other helpful information

**Comment by eamodio** [comment] 2018-04-22 04:40
@CoenraadS if it is reliably reproducible for you, I'd love to find a way to dig deeper into it -- maybe a Live Share or something?

**Comment by eamodio** [comment] 2018-05-23 13:44
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!

**Comment by Waltari10** [comment] 2018-10-04 07:07
I've just now been having similar issues with GitLens. Disabling GitLens makes the actions show up again. I have GitLens version 8.5.6 and Visual Code 1.27.2.

Not sure how to reproduce. Seems to pop up every now and then.

**Comment by AhmedBHameed** [comment] 2018-10-15 13:28
Hey guys, So after long searching with trying i may discovered the reason of disabled options for the merge conflict sections. In my case was solved by removing this line in `settings.json` file which is located in
`~/.config/code/User` note that my OS is Linux Ubuntu.

`"editor.codeLens": false`

Hope that will resolve your issue also.
Thank you.

**Comment by eamodio** [comment] 2018-10-22 17:17
Just so everyone is clear, that setting has nothing directly to do with GitLens -- and GitLens never changes that setting. That is vscode's master setting to allow (or disallow) and code lens in the editor -- GitLens or otherwise.

**Comment by eamodio** [comment] 2018-12-03 14:09
Is anyone still experiencing this? If so, please try GitLens 9 and let me know if the issue still persists.

**Comment by shiftgeist** [comment] 2018-12-03 16:09
I have experiences the same as yuo @eamodio: Installed gitlense: Links are gone. The setting "Merge-conflict > Code Lense: Enabled" (checked) brought it back.

Thanks for mentioning @James-E-Adams, it works again!

**Comment by eamodio** [comment] 2018-12-12 16:45
I'm going to close this as I think this is resolved (and was a vscode issue).

**Closed by eamodio** 2018-12-12 16:45 UTC
Labels: needs more info

**Comment by oferz** [comment] 2018-12-19 10:45
I'm having this issue with GitLens 9.2.2, VS Code 1.30.1 running on Linux.
editor.codelens and Merge-conflict > Code Lense are enabled.
Turning off GitLens' review mode (to Zen mode) fixes the issue and I can see the resolve conflict actions above the merge conflict code again.

**Comment by AustonZ** [comment] 2018-12-19 20:04
FYI @oferz:

For me:
VSCode 1.30.1
GitLens 9.2.2

`Merge-conflict > Code Lens` was already enabled, so that wasn't the problem, but as @AhmedBHameed said up above, `Editor: Code Lens` was disabled, and switching that to enabled fixed it.  I'm not sure how that got disabled in the first place.

**Comment by eamodio** [comment] 2018-12-27 21:39
@oferz I'm not sure how GitLens could be conflicting with the built-in merge code lens unless there is an issue in vscode itself. Could you please open an issue against the vscode repository and link it here?

**Comment by oferz** [comment] 2019-01-03 11:13
@eamodio with the latest versions (VSCODE 1.30.1 and GitLense 9.3.0) it works fine again.

**Comment by sztomi** [comment] 2019-01-22 11:09
I'm using 1.30.2, `Merge-conflict > Code Lens: Enabled`, `Editor: Code Lens: Enabled` and yet I'm not seeing the merge conflict actions. Anything I can do?

**Comment by eamodio** [comment] 2019-01-22 15:47
What OS?

**Comment by sztomi** [comment] 2019-01-22 16:25
Linux. But it turns out that switching to Review mode solved it. I'm not sure if this behavior changed recently, but I recall I usually use Zen mode and switch to Review as needed. If it's a change, I'd prefer the old behavior where the action items still appear in Zen mode for merge conflicts.

**Comment by eamodio** [comment] 2019-01-22 18:17
Review mode in GitLens right? GitLens doesn't provide the merge code lens (that is built into vscode itself) and there seems to be some issue (only under linux) where somehow GitLens can affect those built in code lens.

I'm a little confused on the steps -- are you using GitLens in Zen mode or the Zen mode of vscode itself? GitLens Zen mode *should* have no effect on vscode features (such as the merge code lens). But if you toggle between GitLens Zen mode and Review mode, the merge code lens will go away and come back?

**Comment by randallmeeker** [comment] 2019-03-09 21:06
FWIW I do NOT have GitLens installed but still had this issue and google brought me here. 

Ubuntu 18, VSC 1.32.1

Enable / Disabling 
`Merge-conflict > Code Lens: Enabled, Editor: Code Lens: Enabled`

fixed my issues. Both shown as enabled. I disabled both and then re-enabled both via the GUI.

![image](https://user-images.githubusercontent.com/2538537/54077331-6044a480-427c-11e9-8e41-fefcce3d623f.png)

**Comment by i-love-thinking** [comment] 2019-03-31 03:29
The same reason as @randallmeeker. Disable `Gitlens > Code Lens:` make **merge conflict actions** appear.
![disable](https://user-images.githubusercontent.com/38521343/55284385-17c66580-53a8-11e9-93b8-2aafcb2083d4.png)

**Comment by eamodio** [comment] 2019-03-31 17:14
@i-love-thinking what platform are you on? Linux?

**Comment by i-love-thinking** [comment] 2019-04-01 06:37
Ubuntu 18, VSC 1.32.3

**Comment by eamodio** [comment] 2019-04-01 08:43
Reported here: https://github.com/Microsoft/vscode/issues/71532

**Comment by bgpedersen** [comment] 2019-06-20 07:49
This happend to me just now doing a rebase. I left the computer for 10 minutes, and when I came back the missing merge actions buttons were back. I also noticed the Srouce Control: GIT tab, had MERGE CHANGES with the correct file now - before it was in STAGED CHANGES, even though it contained conflicts.
