### ISSUE TITLE
Unable to show branch history for branch that matches file or folder name

### ISSUE THREAD

**Issue by jabacchetta** [eamodio/vscode-gitlens#313] opened 2018-03-13 16:12 UTC
- GitLens Version: 8.1.1
- VSCode Version: 1.21.0
- OS Version: macOS 10.13.3

Steps to Reproduce:

1. Run the following command "GitLens: Show Branch History"
2. Select a branch

I'm getting the following error: "Unable to show branch history". I've used this feature on a regular basis in the past (without any problems), but this seems to have become an issue over the last month or so.

**Comment by eamodio** [comment] 2018-03-14 22:54
Unfortunately I can't reproduce this behavior. Can you please enable output channel logging by setting `"gitlens.outputLevel": "verbose"` in your `settings.json`. This will enable logging to the *GitLens* channel in the *Output* pane. Once enabled, please attempt to reproduce the issue (if possible) and attach the relevant log lines from the *GitLens* channel.

**Comment by eamodio** [comment] 2018-03-31 18:05
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!

**Comment by conan-z** [comment] 2018-04-12 20:11
Hi Eric:

I experienced the same problem today. Where can I see the output log from GitLens channel after changing the output level?

Thanks!

VSCode info:
> Version 1.22.1
> Commit 950b8b0d37a9b7061b6f0d291837ccc4015f5ecd
> Date 2018-04-06T00:24:49.616Z
> Shell 1.7.12
> Renderer 58.0.3029.110
> Node 7.9.0
> Architecture x64

Gitlens version: 8.2.1

**Comment by eamodio** [comment] 2018-04-12 20:13
Hi you can find it in the Output pane:
![image](https://user-images.githubusercontent.com/641685/38701622-5ba6c22e-3e6c-11e8-8ee3-75cec7756f63.png)

**Comment by conan-z** [comment] 2018-04-12 20:34
I manage to find the log output. Thanks for the detailed instruction :)

This seems to be a special case. I am on a Git (local dev) branch called **concourse**. I also have a folder in my project called "concourse". This causes the git command to be confused.

Workaround: rename git branch "concourse" to anything else.

**Comment by conan-z** [comment] 2018-04-12 20:34
Full log output:

```
getBlameForLine('/home/ubuntu/git/projects/api', '/home/ubuntu/git/projects/api/docker/docker-compose.yml', 'undefined', 26)
getBlameForFile[Cached(blame)]('/home/ubuntu/git/projects/api', '/home/ubuntu/git/projects/api/docker/docker-compose.yml', 'undefined')
isTracked('docker/docker-compose.yml', '/home/ubuntu/git/projects/api', 'undefined')
isTracked('docker/docker-compose.yml', '/home/ubuntu/git/projects/api', 'undefined')
getBranch('/home/ubuntu/git/projects/api')
Running(/home/ubuntu/git/projects/api): git rev-parse --abbrev-ref --symbolic-full-name @ @{u}
Error(/home/ubuntu/git/projects/api): git -c core.quotepath=false -c color.ui=false rev-parse --abbrev-ref --symbolic-full-name @ @{u})
    (128) Command failed: git -c core.quotepath=false -c color.ui=false rev-parse --abbrev-ref --symbolic-full-name @ @{u}
fatal: no upstream configured for branch 'concourse'

fatal: no upstream configured for branch 'concourse'

FAILED(/home/ubuntu/git/projects/api): git rev-parse --abbrev-ref --symbolic-full-name @ @{u} FAILED in 10 ms
isTracked('docker/docker-compose.yml', '/home/ubuntu/git/projects/api', 'undefined')
Keyboard.beginScope 0
getLog('/home/ubuntu/git/projects/api', 'concourse', undefined, false)
Running(/home/ubuntu/git/projects/api): git log --name-status -M --format=%x3c%x2ff%x3e%n%x3cr%x3e %H%n%x3ca%x3e %an%n%x3ce%x3e %ae%n%x3cd%x3e %at%n%x3cp%x3e %P%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e%n%x3cf%x3e --full-history -m -n200 concourse
Error(/home/ubuntu/git/projects/api): git -c core.quotepath=false -c color.ui=false log --name-status -M --format=%x3c%x2ff%x3e%n%x3cr%x3e %H%n%x3ca%x3e %an%n%x3ce%x3e %ae%n%x3cd%x3e %at%n%x3cp%x3e %P%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e%n%x3cf%x3e --full-history -m -n200 concourse)
    (128) Command failed: git -c core.quotepath=false -c color.ui=false log --name-status -M --format=%x3c%x2ff%x3e%n%x3cr%x3e %H%n%x3ca%x3e %an%n%x3ce%x3e %ae%n%x3cd%x3e %at%n%x3cp%x3e %P%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e%n%x3cf%x3e --full-history -m -n200 concourse
fatal: ambiguous argument 'concourse': both revision and filename
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

fatal: ambiguous argument 'concourse': both revision and filename
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

FAILED(/home/ubuntu/git/projects/api): git log --name-status -M --format=%x3c%x2ff%x3e%n%x3cr%x3e %H%n%x3ca%x3e %an%n%x3ce%x3e %ae%n%x3cd%x3e %at%n%x3cp%x3e %P%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e%n%x3cf%x3e --full-history -m -n200 concourse FAILED in 6 ms
git log --name-status -M --format=%x3c%x2ff%x3e%n%x3cr%x3e %H%n%x3ca%x3e %an%n%x3ce%x3e %ae%n%x3cd%x3e %at%n%x3cp%x3e %P%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e%n%x3cf%x3e --full-history -m -n200 concourse   cwd='/home/ubuntu/git/projects/api'

   Error: Command failed: git -c core.quotepath=false -c color.ui=false log --name-status -M --format=%x3c%x2ff%x3e%n%x3cr%x3e %H%n%x3ca%x3e %an%n%x3ce%x3e %ae%n%x3cd%x3e %at%n%x3cp%x3e %P%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e%n%x3cf%x3e --full-history -m -n200 concourse
fatal: ambiguous argument 'concourse': both revision and filename
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

KeyboardScope.dispose 1 0

```

**Comment by SalvaElabs** [comment] 2018-04-20 09:14
Just wanted to say that I had the same problem as @conan-z : i have a branch called "magento" and a folder with the same name inside the repository and it fails to show the commits for the branch.

If i rename it to another name it works.

**Closed** 2018-04-21 07:09 UTC
Labels: bug
