### ISSUE TITLE
Unsaved code lens appears on untracked files

### ISSUE THREAD

**Issue by DFelten** [eamodio/vscode-gitlens#211] opened 2017-11-23 08:36 UTC
I'm not in any git project, yet the message "Cannot determine recent change or authors (unsaved changes)" appears. Is this intended to appear even if I am not in a git project?

This message is helpful when I am working on a git project, but for me it is useless in a normal document. 

- GitLens Version: 6.12
- VSCode Version: 1.19.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Open a new file and save it for example as test.md
2. Write something

![image](https://user-images.githubusercontent.com/1169185/33163926-f14ad5d6-d030-11e7-943a-d7c253a8d94a.png)

**Comment by metcalfc** [comment] 2017-11-24 00:45
I get the same notation on nearly every line in an untracked file in a git project.

**Comment by eamodio** [comment] 2017-11-27 04:00
This is definitely NOT by design. I have never noticed this -- it took me a little bit to reproduce too. It will be fixed in the next GitLens release. Sorry for the inconvenience and thank you both for the report!

**Closed** 2017-11-27 07:21 UTC
Labels: alt-feature
