### ISSUE TITLE
I really want it to support Chinese

### ISSUE THREAD

**Issue by jiejieTop** [eamodio/vscode-gitlens#913] opened 2019-11-24 04:19 UTC
Gitlens is the best git plugin I have ever used. I really want it to support Chinese. Thank you very much anyway.

**Comment by eamodio** [comment] 2019-11-25 07:24
Duplicate of https://github.com/eamodio/vscode-gitlens/issues/577

**Closed by eamodio** 2019-11-25 07:24 UTC
Labels: status: duplicate, type: feature

**Comment by jiejieTop** [comment] 2019-11-25 09:56
@eamodio Oh, I am very sorry that I have not searched, and I am very grateful for your answer.
