### ISSUE TITLE
Toggle for branch comparison does not work

### ISSUE THREAD

**Issue by divnych** [eamodio/vscode-gitlens#1570] opened 2021-07-02 08:28 UTC
- GitLens Version:
v11.5.1
- Git Version: Run `git --version`
git version 2.31.1.windows.1

- VSCode Version: Run `code --version`
1.57.1
507ce72a4466fbb27b715c3722558bb15afa9f48
x64
- OS Version:
Windows_NT x64 10.0.19042
Steps to Reproduce:

1. I see no toggle icon within branch comparison section when hovering over it.
![image](https://user-images.githubusercontent.com/33792604/124244549-e8958600-dad3-11eb-9fc3-fce13a277bec.png)

2. Moreover, if I change the option to compare the current branch it still shows the comparison between the working tree.
![image](https://user-images.githubusercontent.com/33792604/124244999-62c60a80-dad4-11eb-862b-a0419b47b6c1.png)

Thanks.

**Comment by divnych** [comment] 2021-07-02 13:51
This feature seems to be working only for the new branches. So, when I check out to a new branch and choose another one to be compared with then there is no way to change a branch for comparison. Is this expected or am I doing something wrong?

**Comment by justlevine** [comment] 2021-07-04 21:26
Same here.  
- Gitlens: v11.5.1
- Git: v2.20.1
- VSCode : 1.57.1
507ce72a4466fbb27b715c3722558bb15afa9f48
x64
- WSL2 Ubuntu 20.04

(Also happens when running VSCode natively, Windows 10 Pro 10.0.19042 Build 19042 ).

**Comment by phantomkingx** [comment] 2021-07-08 12:13
This still works properly in version 11.4.1
![image](https://user-images.githubusercontent.com/27621671/124919446-48080000-dfc4-11eb-8389-197748d5af1e.png)

**Comment by eamodio** [comment] 2021-07-09 04:58
Duplicate of #1545

**Closed by eamodio** 2021-07-09 04:58 UTC
Labels: potential-bug, triage
