### ISSUE TITLE
Get avatars from GitHub if possible

### ISSUE THREAD

**Issue by monk-time** [eamodio/vscode-gitlens#281] opened 2018-02-09 06:29 UTC
Since I haven't registered my e-mail on gravatar, Git Lens shows all my commits with a default avatar. I think it would be neat if it could try to fetch an avatar from GitHub if a user has GitHub remotes under their `user.name` on GitHub or `user.email=*@users.noreply.github.com` in Git's config. Or maybe just send a request to `https://api.github.com/users/{user.name}` in all cases?

- GitLens Version: 8.0.0
- VSCode Version: 1.20
- OS Version: Win7x64

**Comment by eamodio** [comment] 2018-02-09 17:53
Honestly, I looked into adding this when I add the avatars feature, but shied away from it because I only have the email address of the commit author and there isn't a any (that I know of) to get a GitHub username from an email (unless as you say the e-mail address is `*@users.noreply.github.com` -- which I honestly haven't seen in the wild). I had thought about fuzzy lookup, but because there is a chance they can return the wrong data (an email, without the domain, could match someone else's GitHub account), I'm don't think it is a good solution.

Also need to consider that these avatars aren't just for the local user, they are anyone who has committed to the repository, so it would need to work for them all.

**Comment by monk-time** [comment] 2018-02-09 19:03
Yeah, I haven't considered all that. 

Another idea: what about going through remotes? The extension can show GH avatars only if a repo has at least one GitHub remote configured. Then it can do a one-time request to GH to see if there are matching hashes between remote and local repos, and create an e-mail:GH-user:avatar mapping based on that. There must be some API incantation to search for a hash in a repo and get an author's avatar for a matching commit. Once it's done, this mapping can be used to show avatars for new commits.

**Comment by eamodio** [comment] 2018-02-09 20:09
Sounds like a lot of upfront processing work, that is very GitHub specific. I normally try to stay away from features that will only work with 1 provider/host, since I want GitLens to a broader reach and no favorites 😄 

Given the challenges here and the value of the feature imo -- it isn't worth the investment (for me). But if the community wants to submit a PR (start with a spec first please) I'm open.

**Comment by eamodio** [comment] 2018-10-05 08:34
I'd be thrilled to review/accept a PR for something like this 😄

**Comment by tecosaur** [comment] 2019-03-12 00:44
@eamodio Just regarding getting avatars for no-reply emails such as `20903656+tecosaur@users.noreply.github.com` would you be willing to point me to the relevant bits of the codebase and I'll take a look and implement it if it isn't too hard.

**Comment by scottmerck7007** [comment] 2019-08-17 11:33
Dismiss

**Comment by scottmerck7007** [comment] 2019-08-17 11:33
Dismiss <clear>

**Comment by tecosaur** [comment] 2019-08-18 06:55
This may be of interest: https://github.com/mhutchie/vscode-git-graph/commit/ee829d6c5ed826835d9b40a836063b5db72d8054

**Comment by KamasamaK** [comment] 2019-09-20 22:55
For some reason, gravatars are HUGE in the line blame hover.

**Comment by eamodio** [comment] 2019-09-20 23:08
@KamasamaK can you please open a new issue for this? And I can't seem to reproduce it, so please provide any details you can.

**Comment by adamreisnz** [comment] 2020-08-17 03:56
Any movement on this feature?
The default avatars look really weird and don't seem to work well with a dark background:

![image](https://user-images.githubusercontent.com/490562/90355968-16333580-e0a2-11ea-8c51-c6e723d43bef.png)

Looks like a red exclamation mark to me when not wearing glasses 😆

**Comment by eamodio** [comment] 2020-08-17 16:38
PR is welcome 😄

**Comment by matzar** [comment] 2020-10-28 14:01
You can change it to different style by searching in the settings: `gitlens.defaultGravatarsStyle`

something like this should pop up: 
![image](https://user-images.githubusercontent.com/15261018/97445910-aead2800-1925-11eb-95bc-77f0d4bbab00.png)

the weirdo is called `robohash` and according to the description it's supposed to be `a robot with different colors, faces etc.`.

**Comment by eamodio** [comment] 2020-10-29 19:57
FYI, this is coming in GitLens 11 (should be coming either later this week or next)

**Comment by plwalsh** [comment] 2020-11-15 21:27
Was a generic solution implemented that works with both GitHub and GitLab, or does it only support GitHub so far?

And great job with the GitLens 11 update!

**Comment by eamodio** [comment] 2020-11-15 22:11
The infrastructure is generic and can support any remote provider, but it would need to be implemented. PRs welcome!

**Comment by eamodio** [comment] 2020-12-01 06:02
Added in GitLens 11

**Closed by eamodio** 2020-12-01 06:02 UTC
Labels: type: feature
