### ISSUE TITLE
The outline of the icon doesn't fit the new icons

### ISSUE THREAD

**Issue by shiftgeist** [eamodio/vscode-gitlens#839] opened 2019-09-04 08:05 UTC
![image](https://user-images.githubusercontent.com/30648730/64235597-f9d1d380-cef8-11e9-83fa-5146207e7282.png)

I would like to see a thinner circle. Imo this would fit more to the current style. 
![image](https://user-images.githubusercontent.com/30648730/64236813-782f7500-cefb-11e9-9ae7-2c2822894d05.png)
(left: current, right: new)

**Comment by eamodio** [comment] 2019-09-04 20:01
Duplicate of #784 -- which will be fixed in the next release

**Closed by eamodio** 2019-09-04 20:01 UTC
