### ISSUE TITLE
Defer gitlens auth notification

### ISSUE THREAD

**Issue by roblourens** [eamodio/vscode-gitlens#1367] opened 2021-02-05 17:28 UTC
Currently when I create a codespace, I immediately get this notification:

![image](https://user-images.githubusercontent.com/323878/107067491-34960600-6794-11eb-8091-470199b5e95b.png)

alongside the "configuring your codespace" notification and any others that an extension might show immediately. Could this be delayed until I see a gitlens view, or trigger some feature that would be affected by it? I actually won't see anything missing until I do something like go to the SCM viewlet and expand "Commits", right?

**Comment by eamodio** [comment] 2021-02-09 06:56
Duplicate of https://github.com/eamodio/vscode-gitlens/issues/1336

**Closed by eamodio** 2021-02-09 06:56 UTC
Labels: duplicate
