### ISSUE TITLE
Full-width characters break gutter annotations

### ISSUE THREAD

**Issue by phillyai** [eamodio/vscode-gitlens#135] opened 2017-08-29 11:50 UTC
- GitLens Version: 4.4.1
- VSCode Version: 1.15.1
- OS Version: Windows 10

![Screenshot](https://s26.postimg.org/mf2c0lk8p/054.png)

When commit message contains fullwidth chracter happens.

**Comment by eamodio** [comment] 2017-08-29 17:25
This is a duplicate of https://github.com/eamodio/vscode-gitlens/issues/107 and sadly it depends on the font used.

**Comment by phillyai** [comment] 2017-08-29 17:33
I'm using monospace font but it doesn't work. Isn't there any way to calculate length of string using full-width character as two character?

**Comment by eamodio** [comment] 2017-08-29 18:32
Unfortunately as I understand it (from the vscode issue around it) only certain monospace fonts actually render full-width characters as double-width. If the font does, like Inconsolata, then it works, otherwise it won't. But AFAIK, there is nothing I can do as a vscode extension to get that to work -- maybe it is something vscode can do, but again I don't know. Here is the vscode issue: https://github.com/Microsoft/vscode/issues/14589

**Comment by phillyai** [comment] 2017-08-29 23:27
I think you didn't understane what's the problem. I'm using monospace font, and it works.
![screenshot](https://s26.postimg.org/lsolvrz21/060.png)
What I want to tell you is, you shouldn't pad just using length of string. Maybe you should use `isHalfWidth` in `eastasianwidth` or something to pad actual length of string.

**Comment by eamodio** [comment] 2017-08-30 01:10
@phillyai can you try the Inconsolata font and see if you are still having an issue? 

I am currently using the [string-width](https://github.com/sindresorhus/string-width) library to calculate the width of the line to pad it.

**Comment by phillyai** [comment] 2017-08-30 01:16
![screenshot](https://s26.postimg.org/kvrtxrj95/062.png)
Inconsolata used, still have issue.
```javascript
> s=require('string-width')
[Function]
> s('가나다')
6
```
And also string-width seems working well.

**Comment by eamodio** [comment] 2017-08-30 01:19
@phillyai is this a public repo that I can try out for myself? Also can you try setting: `"gitlens.annotations.file.gutter.compact": false` to see if you see the same behavior?

**Comment by phillyai** [comment] 2017-08-30 01:24
1. Sure, yes. Also there are many repository contains korean commit messages not only this. https://github.com/phillyai/bumble
2. Sadly, yes.
![screenshot](https://s26.postimg.org/7g9em2055/064.png)

**Comment by eamodio** [comment] 2017-08-30 01:38
@phillyai I think I see the issues. One is with the compact mode where I wasn't using string-width, and the other is my truncation function doesn't work properly with full-width characters.

**Comment by eamodio** [comment] 2017-08-30 02:52
@phillyai Just released v4.4.2 -- it should hopefully fix these issues. Thanks again for being persistent on this one!

**Comment by phillyai** [comment] 2017-08-30 04:47
I'm sorry, it's much better but it still have issue. Three dots character makes line little bit longer.
![screenshot](https://s26.postimg.org/6o7nplttl/065.png)

**Comment by eamodio** [comment] 2017-08-30 04:55
@phillyai what font is that? (Also is that file in the repo?)

This is what I see with `Inconsolata` (in the lexer.py file)
![image](https://user-images.githubusercontent.com/641685/29855980-c7ea6342-8d1d-11e7-8e7b-779c95acce98.png)

**Comment by phillyai** [comment] 2017-08-30 05:01
I'm using Inconsolata, same as you, and sorry, this is [another repository](https://github.com/phillyai/claculator/blob/master/src/builder.py).
Also I tried `lexer.py` in bumble, and it is working very well.

**Comment by eamodio** [comment] 2017-08-30 05:05
OK -- I'll check that one out -- thank you!

**Closed** 2017-08-30 16:20 UTC
