### ISSUE TITLE
Does not honor the word wrap settings

### ISSUE THREAD

**Issue by atishay** [eamodio/vscode-gitlens#311] opened 2018-03-12 22:06 UTC
- GitLens Version: 8.1.1
- VSCode Version: 1.20.1
- OS Version: OSX 10.13.3

Steps to Reproduce:

1. Enable word wrap in VSCode Preferences.
2. Check the horizontal scroll bar.

**Comment by eamodio** [comment] 2018-03-13 05:48
Duplicate of https://github.com/eamodio/vscode-gitlens/issues/290. Unfortunately there isn't much I can do here given the constraints of the vscode api and behavior.

**Closed** 2018-03-14 22:07 UTC
Labels: vscode issue
