### ISSUE TITLE
Can go to previuos changes, no detect the file

### ISSUE THREAD

**Issue by pookdeveloper** [eamodio/vscode-gitlens#938] opened 2020-01-24 08:10 UTC
- GitLens Version:
10.2.0
- VSCode Version:
- OS Version:
Windows 10
Steps to Reproduce:

I can fetch the repo, but if I click in the previous change its dosen't detect any change and show a error 
![image](https://user-images.githubusercontent.com/3384734/73053847-23c86a00-3e89-11ea-98df-32b17854a655.png)

And when I open gitlens panel it throws:

![image](https://user-images.githubusercontent.com/3384734/73053867-35aa0d00-3e89-11ea-9f96-658ed0d6fa38.png)

Thanks

**Comment by d1vanloon** [comment] 2020-01-30 21:14
I'm seeing a similar issue. File and line history are also broken. Downgrading from `git` version `2.25.0` to version `2.24.1.2` resolved the issue for me.

**Comment by d1vanloon** [comment] 2020-02-03 16:45
Possible duplicate of #932

**Comment by aleksandar-kandzhichki** [comment] 2020-02-09 18:25
Same issue here. On start of VSCode it detects 2 repositories on the same path, for any repository - so then the compare gitRepo path returns undefined and breaks the logic.

Downgrading to git 2.24.0 resolved it for me!

**Comment by eamodio** [comment] 2020-02-10 20:41
Duplicate of #932

**Closed by eamodio** 2020-02-10 20:41 UTC
Labels: type: potential bug
