### ISSUE TITLE
Invalid links are created

### ISSUE THREAD

**Issue by dnicolson** [eamodio/vscode-gitlens#907] opened 2019-11-17 00:15 UTC
Links can be created based on fuzzy matches of file system provider schemes which are invalid. The below example shows `pling` associated with `plist`. The issue is not present when the scheme is changed from `plist` to something else. The issue maybe a Visual Studio Code issue but the issue is only present when the GitLens extension is enabled.

- GitLens Version: 10.1.2
  
- VSCode Version: 1.40.1
- OS Version: 10.15.1

Steps to Reproduce:

1. Install GitLens
2. Disable GitLens

Option 1:
1. Enable GitLens
2. Install Binary Plist (dnicolson.binary-plist)

Option 2:
1. Enable GitLens
2. Enable Binary Plist (dnicolson.binary-plist)
3. Enable Wallaby.js (wallabyjs.wallaby-vscode)

The following text:
```
file:///Users/dave/negative-integer.plist
plist:/Users/dave/negative-integer.plist
{sampling: 0.1}
```

Produces this:

![bug](https://user-images.githubusercontent.com/2276355/69000898-66dcee80-08d6-11ea-9a79-1f8db1fe6335.gif)

**Comment by eamodio** [comment] 2019-11-23 04:57
Duplicate of #888 and of https://github.com/microsoft/vscode/issues/83410 (which has been fixed in insiders)

**Closed by eamodio** 2019-11-23 04:57 UTC
Labels: status: duplicate
