### ISSUE TITLE
"apply Changes" has discarded all my changes.

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [eamodio/vscode-gitlens#451] opened 2018-07-20 02:20 UTC
Issue Type: <b>Bug</b>

- There is the file named a.txt in the master branch.
- I edited contents of a.txt and save in VS Code.
- in GITLENS view, master -> 1 file changed -> a.txt -> mouse right click -> select "apply changes" to move changes into staged area.
- But nothing happened except the changes were all gone.
 file, right click on the master -> 1 file changed -> a.txt in the
- Due to "apply changes" GITLENS, I lost all my work for two hours.

VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_9341160|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|Pet|0.0.27
vagrant|bbe|0.5.0
vscode-instant-markdown|dba|1.4.2
githistory|don|0.4.2
gitlens|eam|8.4.1
vsc-material-theme|Equ|2.3.0
prettier-vscode|esb|1.5.0
mssql|ms-|1.4.0
python|ms-|2018.6.0
markdown-pdf|yza|1.2.0

</details>

**Comment by eamodio** [comment] 2018-07-20 05:28
First, I'm really very sorry that you lost your work. 😢 I will add protection ASAP that will stop that from happening again, but the root of the issue is confusion about what *Apply Changes* does.

*Apply Changes* is to be used to take the changes from a file revision and apply those changes to your working copy. It is not for saving (or staging) your working changes. So given that, *Apply Changes* **should** have taken your working changes and applied them to your working copy (basically a no-op), but unfortunately there was a bug in the code that caused it to use the changes from *HEAD* rather than the working copy.

I will fix that ASAP and it will be in the next GitLens release. I am also changing the order of operations for how *Apply Changes* works. Before I would tell git to apply the requested changes to the working copy (git checkout) and then I would have vscode open the file. Instead, I will first have vscode open the file, and then have git update it. That way vscode will add the changes to the undo buffer, so that the changes could also be easily undone if needed.

Again I'm really sorry for the time and work lost.

**Closed** 2018-07-20 06:19 UTC
Labels: bug

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment] 2018-07-21 06:35
Thank you for your quick response. I am always thankful for contributing the best git extension!!

**Comment by doutdex** [comment] 2018-10-24 12:02
Hey, I got the same issue 3 days of full work on a file is lost, exist a wat revert or check history within Visual Studio to get back my last data of the file.....

**Comment by eamodio** [comment] 2018-10-24 14:18
Sorry that you lost work, but what were the steps that caused it? This bug has been fixed so I'd like to  understand if there are other issues lurking.
