### ISSUE TITLE
Editor actions fail to collapse properly when multiple columns are open

### ISSUE THREAD

**Issue by jscheel** [eamodio/vscode-gitlens#868] opened 2019-09-27 14:20 UTC
![collapse](https://user-images.githubusercontent.com/211478/65776446-c9501480-e107-11e9-8e12-8fd7a89a0d59.gif)

- GitLens Version:
  
- VSCode Version: 1.38.1
- OS Version: macOS 10.12.5

Steps to Reproduce:

1. Open several tabs in two different editor layout columns (enough to span the width of the column).
2. Click on tabs in right column and editor actions collapse properly, click on tabs in right column and they do not.

**Comment by eamodio** [comment] 2019-11-11 20:05
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!

**Closed by eamodio** 2019-11-11 20:05 UTC
Labels: status: needs more info, type: potential bug

**Comment by jscheel** [comment] 2019-11-12 03:16
Hey, sorry, my github notifications have so much noise in them, I missed this. So, I may be misunderstanding when certain actions in this toolbar should be present.

![Screen Shot 2019-11-11 at 9 15 02 PM](https://user-images.githubusercontent.com/211478/68638848-74eed180-04c8-11ea-8d47-b057e7455856.png)

vs

![Screen Shot 2019-11-11 at 9 15 11 PM](https://user-images.githubusercontent.com/211478/68638860-7f10d000-04c8-11ea-8917-e93c0950033b.png)

**Comment by eamodio** [comment] 2019-11-12 03:19
The icon below are always present in the toolbar if the file is part of a repo (mostly).
![image](https://user-images.githubusercontent.com/641685/68638968-21cd4c80-04d1-11ea-96d4-c440a0a24cc6.png)

But you can turn them off if you want:
https://github.com/eamodio/vscode-gitlens/issues/900#issuecomment-552313898

**Comment by jscheel** [comment] 2019-11-12 03:36
Ok, so that's not happening consistently for me (working in the same repo). Interestingly, I also find that often my blame annotations in the bottom bar don't show up. I'm guessing these two issues are linked.

**Comment by eamodio** [comment] 2019-11-12 04:37
Can you provide more details as to what you are seeing? 
Also can you please enable output channel logging by setting `"gitlens.outputLevel": "debug"` in your settings. This will enable logging to the *GitLens* channel in the *Output* pane. Once enabled, please reproduce the issue and attach the log from the *GitLens* channel.
