### ISSUE TITLE
History comparison of renamed files fall into error

### ISSUE THREAD

**Issue by psychelzh** [eamodio/vscode-gitlens#422] opened 2018-06-18 07:21 UTC
If a file under version control has ever renamed, "`cannot open file`" error occurs when clicking to view one of its history commit. But I can view the patches of that commit, but only that commit, i.e., all the commits but that one disappeared from "**GIT HISTORY**" panel. See following screenshots:

![image](https://user-images.githubusercontent.com/13306020/41522974-ddc36bcc-730a-11e8-82f6-0224d204d03e.png)

![image](https://user-images.githubusercontent.com/13306020/41523072-3c6cbcdc-730b-11e8-8e12-8a5fa7a45cbf.png)

**Comment by eamodio** [comment] 2018-06-19 05:29
Can you please enable output channel logging by setting `"gitlens.outputLevel": "verbose"` in your `settings.json`. This will enable logging to the *GitLens* channel in the *Output* pane. Once enabled, please attempt to reproduce the issue (if possible) and attach the relevant log lines from the *GitLens* channel.

While the behavior of the commit disappearing is less than desirable, it is expected. When you open a diff with the file at a particular revision, that the file has been renamed (or moved) GitLens can't easily detect this rename, so it only show's commits for the file with that specific name.

**Comment by psychelzh** [comment] 2018-06-19 07:03
I see. The 'cannot open' error occurs again, but I get to know that it is not possible to have a full view of every detail of the changes for a file that have been renamed.

**Comment by eamodio** [comment] 2018-06-19 14:38
I don't see the error in those logs, do those logs cover the time range from when you saw the error message?

**Comment by psychelzh** [comment] 2018-06-19 14:43
After the update (`v8.4`) of today, I cannot view a file's history before it was renamed. So this bug won't occur from now on. It might be a better way to do it this way.

Thank you very much. And I think I should close this now.

**Comment by psychelzh** [comment] 2018-06-19 14:46
But the reality is not so? The error occurred again in another file. Here are the logs:

```dos
getVersionedFile('c:/Users/liang/OneDrive/Documents/Git/iquizoo/reports', 'c:\Users\liang\OneDrive\Documents\Git\iquizoo\reports\reports.Rproj', '1ecf03e1b3d6e956a96777b370f9a9786607d0eb')
Running(c:/Users/liang/OneDrive/Documents/Git/iquizoo/reports): git show 1ecf03e1b3d6e956a96777b370f9a9786607d0eb:./reports.Rproj --
getVersionedFile('c:/Users/liang/OneDrive/Documents/Git/iquizoo/reports', 'c:\Users\liang\OneDrive\Documents\Git\iquizoo\reports\iquizoo-reports.Rproj', 'dc1aa4786283698b81427eecbad2b6240da99719')
Running(c:/Users/liang/OneDrive/Documents/Git/iquizoo/reports): git show dc1aa4786283698b81427eecbad2b6240da99719:./iquizoo-reports.Rproj --
Completed(c:/Users/liang/OneDrive/Documents/Git/iquizoo/reports): git show 1ecf03e1b3d6e956a96777b370f9a9786607d0eb:./reports.Rproj -- Completed in 80 ms
getVersionedFile[C:\Users\liang\AppData\Local\Temp\reports-1ecf03e1__17168fLcQEfBy9gis.Rproj]('c:/Users/liang/OneDrive/Documents/Git/iquizoo/reports', 'c:\Users\liang\OneDrive\Documents\Git\iquizoo\reports\reports.Rproj', 1ecf03e1b3d6e956a96777b370f9a9786607d0eb)
Completed(c:/Users/liang/OneDrive/Documents/Git/iquizoo/reports): git show dc1aa4786283698b81427eecbad2b6240da99719:./iquizoo-reports.Rproj -- Completed in 74 ms
getVersionedFile[C:\Users\liang\AppData\Local\Temp\iquizoo-reports-dc1aa478__17168u5VnbBinKbcb.Rproj]('c:/Users/liang/OneDrive/Documents/Git/iquizoo/reports', 'c:\Users\liang\OneDrive\Documents\Git\iquizoo\reports\iquizoo-reports.Rproj', dc1aa4786283698b81427eecbad2b6240da99719)
Reset state for 'c:/users/liang/onedrive/documents/git/iquizoo/reports/reports.rproj', reason=dispose
isTracked('c:\Users\liang\OneDrive\Documents\Git\iquizoo\reports\iquizoo-reports.Rproj', 'c:/Users/liang/OneDrive/Documents/Git/iquizoo/reports', 'dc1aa4786283698b81427eecbad2b6240da99719')
isTracked('c:\Users\liang\OneDrive\Documents\Git\iquizoo\reports\iquizoo-reports.Rproj', 'c:/Users/liang/OneDrive/Documents/Git/iquizoo/reports', 'dc1aa4786283698b81427eecbad2b6240da99719') = true
getBlameForLine('c:/Users/liang/OneDrive/Documents/Git/iquizoo/reports', 'c:\Users\liang\OneDrive\Documents\Git\iquizoo\reports\iquizoo-reports.Rproj', 'dc1aa4786283698b81427eecbad2b6240da99719', 0)
getBlameForFile[Not Cached(blame:dc1aa4786283698b81427eecbad2b6240da99719)]('c:/Users/liang/OneDrive/Documents/Git/iquizoo/reports', 'c:\Users\liang\OneDrive\Documents\Git\iquizoo\reports\iquizoo-reports.Rproj', 'dc1aa4786283698b81427eecbad2b6240da99719')
isTracked('c:\Users\liang\OneDrive\Documents\Git\iquizoo\reports\iquizoo-reports.Rproj', 'c:/Users/liang/OneDrive/Documents/Git/iquizoo/reports', 'dc1aa4786283698b81427eecbad2b6240da99719')
Add blame cache for 'c:/users/liang/appdata/local/temp/iquizoo-reports-dc1aa478__17168u5vnbbinkbcb.rproj:blame:dc1aa4786283698b81427eecbad2b6240da99719'
isTracked('c:\Users\liang\OneDrive\Documents\Git\iquizoo\reports\iquizoo-reports.Rproj', 'c:/Users/liang/OneDrive/Documents/Git/iquizoo/reports', 'dc1aa4786283698b81427eecbad2b6240da99719') = true
Running(c:/Users/liang/OneDrive/Documents/Git/iquizoo/reports): git blame --root --incremental dc1aa4786283698b81427eecbad2b6240da99719 -- iquizoo-reports.Rproj
Completed(c:/Users/liang/OneDrive/Documents/Git/iquizoo/reports): git blame --root --incremental dc1aa4786283698b81427eecbad2b6240da99719 -- iquizoo-reports.Rproj Completed in 38 ms
HistoryExplorer.refresh reason='active-editor-changed'
getStatusForFile('c:/Users/liang/OneDrive/Documents/Git/iquizoo/reports', 'c:\Users\liang\OneDrive\Documents\Git\iquizoo\reports\iquizoo-reports.Rproj')
Running(c:/Users/liang/OneDrive/Documents/Git/iquizoo/reports): git -c color.status=false status --porcelain=v2 iquizoo-reports.Rproj
Completed(c:/Users/liang/OneDrive/Documents/Git/iquizoo/reports): git -c color.status=false status --porcelain=v2 iquizoo-reports.Rproj Completed in 103 ms
```

**Comment by eamodio** [comment] 2018-07-09 05:07
Assuming this is still reproducible, when this error happens can you look in the devtools console to see if there are any error messages there?

**Comment by psychelzh** [comment] 2018-07-09 15:29
I will try to capture it the next time it occurs. Thank you for your respondent.

**Comment by eamodio** [comment] 2018-07-09 18:53
Is there any other details that you can provide? Like is it a multi-root workspace, when it happens is it reproducible, anything else that is specific to when it happens. As I cannot seem to reproduce it, and the logs are sadly unhelpful :(

**Comment by eamodio** [comment] 2018-07-29 06:40
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!

**Closed by eamodio** 2018-07-29 06:40 UTC
Labels: needs more info
