### ISSUE TITLE
Interactive rebase editor fails when opened in a VS Code window that doesn't have the repository opened

### ISSUE THREAD

**Issue by n1l** [eamodio/vscode-gitlens#1361] opened 2021-02-02 14:47 UTC
Hi, I have an issue with Git lens, I can not do interactive rebase with the plugin, when I delete the plugin interactive rebase is working correctly.
I receive the following error:
Unable to open 'git-rebase-todo': Assertion Failed: argument is undefined or null. from notification, and rebase-todo file is empty.

I can not repoduce the bug with 11.1.3 version

<details>
  <summary>Output (GitLens)</summary>
[2021-02-02 14:22:45:196] [c:\Project OpenSource\scriban\.git\rebase-merge] Git Command failed: C:\Program Files\Git\cmd\git.exe -c core.longpaths=true -c core.quotepath=false -c color.ui=false rev-parse --show-toplevel • this operation must be run in a work tree • 53 ms 
[2021-02-02 14:25:25:760] [72] GitService.onWindowStateChanged — e={"focused":false}
[2021-02-02 14:25:25:760] [72] GitService.onWindowStateChanged completed • 0 ms
[2021-02-02 14:25:31:788] [73] LineAnnotationController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=true, reason=selection
[2021-02-02 14:25:31:789] [74] LineAnnotationController.clear completed • 0 ms
[2021-02-02 14:25:31:789] [73] LineAnnotationController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:25:31:789] [75] LineHoverController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=true, reason=selection
[2021-02-02 14:25:31:789] [75] LineHoverController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:25:31:789] [76] StatusBarController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=true, reason=selection
[2021-02-02 14:25:31:790] [76] StatusBarController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:25:31:790] [77] GitService.onWindowStateChanged — e={"focused":true}
[2021-02-02 14:25:31:790] [77] GitService.onWindowStateChanged completed • 0 ms
[2021-02-02 14:25:32:040] [78] GitLineTracker.updateState returned false • document is not blameable • 0 ms — e=21, t=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json
[2021-02-02 14:25:32:040] [79] LineAnnotationController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=false, reason=selection
[2021-02-02 14:25:32:040] [7a] LineAnnotationController.clear completed • 0 ms
[2021-02-02 14:25:32:040] [79] LineAnnotationController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:25:32:040] [7b] LineHoverController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=false, reason=selection
[2021-02-02 14:25:32:040] [7b] LineHoverController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:25:32:040] [7c] StatusBarController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=false, reason=selection
[2021-02-02 14:25:32:040] [7c] StatusBarController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:25:34:035] [7d] LineAnnotationController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=true, reason=selection
[2021-02-02 14:25:34:035] [7e] LineAnnotationController.clear completed • 0 ms
[2021-02-02 14:25:34:035] [7d] LineAnnotationController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:25:34:035] [7f] LineHoverController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=true, reason=selection
[2021-02-02 14:25:34:035] [7f] LineHoverController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:25:34:035] [80] StatusBarController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=true, reason=selection
[2021-02-02 14:25:34:035] [80] StatusBarController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:25:34:289] [81] GitLineTracker.updateState returned false • document is not blameable • 0 ms — e=13, t=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json
[2021-02-02 14:25:34:289] [82] LineAnnotationController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=false, reason=selection
[2021-02-02 14:25:34:289] [83] LineAnnotationController.clear completed • 0 ms
[2021-02-02 14:25:34:289] [82] LineAnnotationController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:25:34:289] [84] LineHoverController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=false, reason=selection
[2021-02-02 14:25:34:289] [84] LineHoverController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:25:34:289] [85] StatusBarController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=false, reason=selection
[2021-02-02 14:25:34:290] [85] StatusBarController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:25:35:190] [86] RebaseEditorProvider.resolveCustomTextEditor
[2021-02-02 14:25:35:190] [87] GitService.getRepository — e=Uri(file:///c:/Project OpenSource/scriban)
[2021-02-02 14:25:35:191] [88] GitService.findRepositoryForPath — e=count=0, t=c:\Project OpenSource\scriban, i=false
[2021-02-02 14:25:35:191] [88] GitService.findRepositoryForPath completed • 0 ms
[2021-02-02 14:25:35:191] [87] GitService.getRepository returned undefined • 0 ms
[2021-02-02 14:25:35:191] [86] RebaseEditorProvider.resolveCustomTextEditor — failed • 1 ms
TypeError: Cannot read property 'onDidChange' of undefined
[2021-02-02 14:25:35:192] [89] LineAnnotationController.onActiveLinesChanged — e=editor=undefined, selections=undefined, pending=false, reason=editor
[2021-02-02 14:25:35:192] [8a] LineAnnotationController.clear completed • 0 ms
[2021-02-02 14:25:35:192] [89] LineAnnotationController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:25:35:192] [8b] LineHoverController.onActiveLinesChanged — e=editor=undefined, selections=undefined, pending=false, reason=editor
[2021-02-02 14:25:35:192] [8b] LineHoverController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:25:35:192] [8c] StatusBarController.onActiveLinesChanged — e=editor=undefined, selections=undefined, pending=false, reason=editor
[2021-02-02 14:25:35:193] [8c] StatusBarController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:25:35:270] [8d] LineAnnotationController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=true, reason=selection
[2021-02-02 14:25:35:270] [8e] LineAnnotationController.clear completed • 0 ms
[2021-02-02 14:25:35:270] [8d] LineAnnotationController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:25:35:270] [8f] LineHoverController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=true, reason=selection
[2021-02-02 14:25:35:270] [8f] LineHoverController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:25:35:270] [90] StatusBarController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=true, reason=selection
[2021-02-02 14:25:35:270] [90] StatusBarController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:25:35:299] [91] GitService.isTracked returned false • 0 ms — e=GitUri(file:///c:/Project OpenSource/scriban/.git/rebase-merge/git-rebase-todo)
[2021-02-02 14:25:35:351] [92] GitUri.fromUri — e=Uri(file:///c:/Project OpenSource/scriban/.git/rebase-merge/git-rebase-todo)
[2021-02-02 14:25:35:351] [93] GitService.getRepoPath — e=Uri(file:///c:/Project OpenSource/scriban/.git/rebase-merge/git-rebase-todo)
[2021-02-02 14:25:35:351] [94] GitService.getRepository — e=Uri(file:///c:/Project OpenSource/scriban/.git/rebase-merge/git-rebase-todo), t={"skipCacheUpdate":true}
[2021-02-02 14:25:35:351] [95] GitService.findRepositoryForPath — e=count=0, t=c:\Project OpenSource\scriban\.git\rebase-merge\git-rebase-todo, i=false
[2021-02-02 14:25:35:352] [95] GitService.findRepositoryForPath completed • 0 ms
[2021-02-02 14:25:35:352] [94] GitService.getRepository returned undefined • 0 ms
[2021-02-02 14:25:35:352] [96] GitService.getRepoPathCore — e=c:\Project OpenSource\scriban\.git\rebase-merge\git-rebase-todo, t=false
[2021-02-02 14:25:35:414] [c:\Project OpenSource\scriban\.git\rebase-merge] Git Command failed: C:\Program Files\Git\cmd\git.exe -c core.longpaths=true -c core.quotepath=false -c color.ui=false rev-parse --show-toplevel • this operation must be run in a work tree • 61 ms 
[2021-02-02 14:25:35:414] [96] GitService.getRepoPathCore completed • 62 ms
[2021-02-02 14:25:35:414] [93] GitService.getRepoPath returned undefined • 63 ms
[2021-02-02 14:25:35:415] [92] GitUri.fromUri returned GitUri(file:///c:/Project OpenSource/scriban/.git/rebase-merge/git-rebase-todo) • 63 ms
[2021-02-02 14:25:35:415] [97] GitService.getRepository — e=GitUri(file:///c:/Project OpenSource/scriban/.git/rebase-merge/git-rebase-todo)
[2021-02-02 14:25:35:415] [98] GitService.findRepositoryForPath — e=count=0, t=c:\Project OpenSource\scriban\.git\rebase-merge\git-rebase-todo, i=false
[2021-02-02 14:25:35:415] [98] GitService.findRepositoryForPath completed • 0 ms
[2021-02-02 14:25:35:415] [97] GitService.getRepository returned undefined • 0 ms
[2021-02-02 14:25:35:415] [99] GitService.isTracked returned false • 0 ms — e=GitUri(file:///c:/Project OpenSource/scriban/.git/rebase-merge/git-rebase-todo)
[2021-02-02 14:25:35:522] [9a] GitLineTracker.updateState returned false • document is not blameable • 0 ms — e=13, t=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json
[2021-02-02 14:25:35:522] [9b] LineAnnotationController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=false, reason=selection
[2021-02-02 14:25:35:522] [9c] LineAnnotationController.clear completed • 0 ms
[2021-02-02 14:25:35:522] [9b] LineAnnotationController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:25:35:522] [9d] LineHoverController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=false, reason=selection
[2021-02-02 14:25:35:522] [9d] LineHoverController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:25:35:522] [9e] StatusBarController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=false, reason=selection
[2021-02-02 14:25:35:523] [9e] StatusBarController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:25:38:284] [9f] GitService.onWindowStateChanged — e={"focused":false}
[2021-02-02 14:25:38:284] [9f] GitService.onWindowStateChanged completed • 0 ms
[2021-02-02 14:25:45:359] [a0] GitService.onWindowStateChanged — e={"focused":true}
[2021-02-02 14:25:45:359] [a0] GitService.onWindowStateChanged completed • 0 ms
[2021-02-02 14:25:45:360] [a1] LineAnnotationController.onActiveLinesChanged — e=editor=undefined, selections=undefined, pending=false, reason=editor
[2021-02-02 14:25:45:360] [a2] LineAnnotationController.clear completed • 0 ms
[2021-02-02 14:25:45:360] [a1] LineAnnotationController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:25:45:360] [a3] LineHoverController.onActiveLinesChanged — e=editor=undefined, selections=undefined, pending=false, reason=editor
[2021-02-02 14:25:45:360] [a3] LineHoverController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:25:45:360] [a4] StatusBarController.onActiveLinesChanged — e=editor=undefined, selections=undefined, pending=false, reason=editor
[2021-02-02 14:25:45:361] [a4] StatusBarController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:25:45:384] [a5] RebaseEditorProvider.resolveCustomTextEditor
[2021-02-02 14:25:45:384] [a6] GitService.getRepository — e=Uri(file:///c:/Project OpenSource/scriban)
[2021-02-02 14:25:45:385] [a7] GitService.findRepositoryForPath — e=count=0, t=c:\Project OpenSource\scriban, i=false
[2021-02-02 14:25:45:385] [a7] GitService.findRepositoryForPath completed • 0 ms
[2021-02-02 14:25:45:385] [a6] GitService.getRepository returned undefined • 0 ms
[2021-02-02 14:25:45:386] [a5] RebaseEditorProvider.resolveCustomTextEditor — failed • 2 ms
TypeError: Cannot read property 'onDidChange' of undefined
[2021-02-02 14:25:45:443] [a8] LineAnnotationController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=true, reason=selection
[2021-02-02 14:25:45:443] [a9] LineAnnotationController.clear completed • 0 ms
[2021-02-02 14:25:45:443] [a8] LineAnnotationController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:25:45:443] [aa] LineHoverController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=true, reason=selection
[2021-02-02 14:25:45:443] [aa] LineHoverController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:25:45:443] [ab] StatusBarController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=true, reason=selection
[2021-02-02 14:25:45:444] [ab] StatusBarController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:25:45:561] [ac] GitUri.fromUri — e=Uri(file:///c:/Project OpenSource/scriban/.git/rebase-merge/git-rebase-todo)
[2021-02-02 14:25:45:561] [ad] GitService.getRepoPath — e=Uri(file:///c:/Project OpenSource/scriban/.git/rebase-merge/git-rebase-todo)
[2021-02-02 14:25:45:561] [ae] GitService.getRepository — e=Uri(file:///c:/Project OpenSource/scriban/.git/rebase-merge/git-rebase-todo), t={"skipCacheUpdate":true}
[2021-02-02 14:25:45:562] [af] GitService.findRepositoryForPath — e=count=0, t=c:\Project OpenSource\scriban\.git\rebase-merge\git-rebase-todo, i=false
[2021-02-02 14:25:45:562] [af] GitService.findRepositoryForPath completed • 0 ms
[2021-02-02 14:25:45:562] [ae] GitService.getRepository returned undefined • 0 ms
[2021-02-02 14:25:45:562] [b0] GitService.getRepoPathCore — e=c:\Project OpenSource\scriban\.git\rebase-merge\git-rebase-todo, t=false
[2021-02-02 14:25:45:604] [c:\Project OpenSource\scriban\.git\rebase-merge] Git Command failed: C:\Program Files\Git\cmd\git.exe -c core.longpaths=true -c core.quotepath=false -c color.ui=false rev-parse --show-toplevel • this operation must be run in a work tree • 42 ms 
[2021-02-02 14:25:45:604] [b0] GitService.getRepoPathCore completed • 42 ms
[2021-02-02 14:25:45:604] [ad] GitService.getRepoPath returned undefined • 43 ms
[2021-02-02 14:25:45:604] [ac] GitUri.fromUri returned GitUri(file:///c:/Project OpenSource/scriban/.git/rebase-merge/git-rebase-todo) • 43 ms
[2021-02-02 14:25:45:604] [b1] GitService.getRepository — e=GitUri(file:///c:/Project OpenSource/scriban/.git/rebase-merge/git-rebase-todo)
[2021-02-02 14:25:45:605] [b2] GitService.findRepositoryForPath — e=count=0, t=c:\Project OpenSource\scriban\.git\rebase-merge\git-rebase-todo, i=false
[2021-02-02 14:25:45:605] [b2] GitService.findRepositoryForPath completed • 0 ms
[2021-02-02 14:25:45:605] [b1] GitService.getRepository returned undefined • 0 ms
[2021-02-02 14:25:45:605] [b3] GitService.isTracked returned false • 0 ms — e=GitUri(file:///c:/Project OpenSource/scriban/.git/rebase-merge/git-rebase-todo)
[2021-02-02 14:25:45:700] [b4] GitLineTracker.updateState returned false • document is not blameable • 0 ms — e=13, t=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json
[2021-02-02 14:25:45:700] [b5] LineAnnotationController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=false, reason=selection
[2021-02-02 14:25:45:700] [b6] LineAnnotationController.clear completed • 0 ms
[2021-02-02 14:25:45:700] [b5] LineAnnotationController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:25:45:700] [b7] LineHoverController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=false, reason=selection
[2021-02-02 14:25:45:700] [b7] LineHoverController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:25:45:701] [b8] StatusBarController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=false, reason=selection
[2021-02-02 14:25:45:701] [b8] StatusBarController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:26:04:449] [b9] RebaseEditorProvider.resolveCustomTextEditor
[2021-02-02 14:26:04:449] [ba] GitService.getRepository — e=Uri(file:///c:/Project OpenSource/scriban)
[2021-02-02 14:26:04:449] [bb] GitService.findRepositoryForPath — e=count=0, t=c:\Project OpenSource\scriban, i=false
[2021-02-02 14:26:04:449] [bb] GitService.findRepositoryForPath completed • 0 ms
[2021-02-02 14:26:04:449] [ba] GitService.getRepository returned undefined • 0 ms
[2021-02-02 14:26:04:449] [b9] RebaseEditorProvider.resolveCustomTextEditor — failed • 0 ms
TypeError: Cannot read property 'onDidChange' of undefined
[2021-02-02 14:26:04:461] [bc] LineAnnotationController.onActiveLinesChanged — e=editor=undefined, selections=undefined, pending=false, reason=editor
[2021-02-02 14:26:04:461] [bd] LineAnnotationController.clear completed • 0 ms
[2021-02-02 14:26:04:461] [bc] LineAnnotationController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:26:04:461] [be] LineHoverController.onActiveLinesChanged — e=editor=undefined, selections=undefined, pending=false, reason=editor
[2021-02-02 14:26:04:461] [be] LineHoverController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:26:04:461] [bf] StatusBarController.onActiveLinesChanged — e=editor=undefined, selections=undefined, pending=false, reason=editor
[2021-02-02 14:26:04:461] [bf] StatusBarController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:26:04:510] [c0] LineAnnotationController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=true, reason=selection
[2021-02-02 14:26:04:510] [c1] LineAnnotationController.clear completed • 0 ms
[2021-02-02 14:26:04:510] [c0] LineAnnotationController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:26:04:510] [c2] LineHoverController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=true, reason=selection
[2021-02-02 14:26:04:511] [c2] LineHoverController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:26:04:511] [c3] StatusBarController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=true, reason=selection
[2021-02-02 14:26:04:511] [c3] StatusBarController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:26:04:542] [c4] GitService.isTracked returned false • 0 ms — e=GitUri(file:///c:/Project OpenSource/scriban/.git/rebase-merge/git-rebase-todo)
[2021-02-02 14:26:04:601] [c5] GitUri.fromUri — e=Uri(file:///c:/Project OpenSource/scriban/.git/rebase-merge/git-rebase-todo)
[2021-02-02 14:26:04:601] [c6] GitService.getRepoPath — e=Uri(file:///c:/Project OpenSource/scriban/.git/rebase-merge/git-rebase-todo)
[2021-02-02 14:26:04:601] [c7] GitService.getRepository — e=Uri(file:///c:/Project OpenSource/scriban/.git/rebase-merge/git-rebase-todo), t={"skipCacheUpdate":true}
[2021-02-02 14:26:04:601] [c8] GitService.findRepositoryForPath — e=count=0, t=c:\Project OpenSource\scriban\.git\rebase-merge\git-rebase-todo, i=false
[2021-02-02 14:26:04:601] [c8] GitService.findRepositoryForPath completed • 0 ms
[2021-02-02 14:26:04:601] [c7] GitService.getRepository returned undefined • 0 ms
[2021-02-02 14:26:04:601] [c9] GitService.getRepoPathCore — e=c:\Project OpenSource\scriban\.git\rebase-merge\git-rebase-todo, t=false
[2021-02-02 14:26:04:642] [c:\Project OpenSource\scriban\.git\rebase-merge] Git Command failed: C:\Program Files\Git\cmd\git.exe -c core.longpaths=true -c core.quotepath=false -c color.ui=false rev-parse --show-toplevel • this operation must be run in a work tree • 41 ms 
[2021-02-02 14:26:04:642] [c9] GitService.getRepoPathCore completed • 41 ms
[2021-02-02 14:26:04:642] [c6] GitService.getRepoPath returned undefined • 41 ms
[2021-02-02 14:26:04:642] [c5] GitUri.fromUri returned GitUri(file:///c:/Project OpenSource/scriban/.git/rebase-merge/git-rebase-todo) • 41 ms
[2021-02-02 14:26:04:642] [ca] GitService.getRepository — e=GitUri(file:///c:/Project OpenSource/scriban/.git/rebase-merge/git-rebase-todo)
[2021-02-02 14:26:04:642] [cb] GitService.findRepositoryForPath — e=count=0, t=c:\Project OpenSource\scriban\.git\rebase-merge\git-rebase-todo, i=false
[2021-02-02 14:26:04:642] [cb] GitService.findRepositoryForPath completed • 0 ms
[2021-02-02 14:26:04:642] [ca] GitService.getRepository returned undefined • 0 ms
[2021-02-02 14:26:04:642] [cc] GitService.isTracked returned false • 0 ms — e=GitUri(file:///c:/Project OpenSource/scriban/.git/rebase-merge/git-rebase-todo)
[2021-02-02 14:26:04:771] [cd] GitLineTracker.updateState returned false • document is not blameable • 0 ms — e=13, t=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json
[2021-02-02 14:26:04:771] [ce] LineAnnotationController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=false, reason=selection
[2021-02-02 14:26:04:771] [cf] LineAnnotationController.clear completed • 0 ms
[2021-02-02 14:26:04:771] [ce] LineAnnotationController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:26:04:771] [d0] LineHoverController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=false, reason=selection
[2021-02-02 14:26:04:771] [d0] LineHoverController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:26:04:771] [d1] StatusBarController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=false, reason=selection
[2021-02-02 14:26:04:771] [d1] StatusBarController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:26:07:932] [d2] LineAnnotationController.onActiveLinesChanged — e=editor=undefined, selections=undefined, pending=false, reason=editor
[2021-02-02 14:26:07:932] [d3] LineAnnotationController.clear completed • 0 ms
[2021-02-02 14:26:07:932] [d2] LineAnnotationController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:26:07:932] [d4] LineHoverController.onActiveLinesChanged — e=editor=undefined, selections=undefined, pending=false, reason=editor
[2021-02-02 14:26:07:932] [d4] LineHoverController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:26:07:932] [d5] StatusBarController.onActiveLinesChanged — e=editor=undefined, selections=undefined, pending=false, reason=editor
[2021-02-02 14:26:07:932] [d5] StatusBarController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:26:09:653] [d6] LineAnnotationController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=true, reason=selection
[2021-02-02 14:26:09:653] [d7] LineAnnotationController.clear completed • 0 ms
[2021-02-02 14:26:09:653] [d6] LineAnnotationController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:26:09:653] [d8] LineHoverController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=true, reason=selection
[2021-02-02 14:26:09:653] [d8] LineHoverController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:26:09:653] [d9] StatusBarController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=true, reason=selection
[2021-02-02 14:26:09:653] [d9] StatusBarController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:26:09:913] [da] GitLineTracker.updateState returned false • document is not blameable • 0 ms — e=13, t=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json
[2021-02-02 14:26:09:913] [db] LineAnnotationController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=false, reason=selection
[2021-02-02 14:26:09:913] [dc] LineAnnotationController.clear completed • 0 ms
[2021-02-02 14:26:09:913] [db] LineAnnotationController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:26:09:913] [dd] LineHoverController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=false, reason=selection
[2021-02-02 14:26:09:913] [dd] LineHoverController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:26:09:913] [de] StatusBarController.onActiveLinesChanged — e=editor=vscode-userdata:/c:/Users/daniel.vega/AppData/Roaming/Code/User/settings.json, selections=undefined, pending=false, reason=selection
[2021-02-02 14:26:09:913] [de] StatusBarController.onActiveLinesChanged completed • 0 ms
[2021-02-02 14:27:07:172] [df] GitService.onWindowStateChanged — e={"focused":false}
[2021-02-02 14:27:07:172] [df] GitService.onWindowStateChanged completed • 0 ms
[2021-02-02 14:28:36:468] [e0] GitService.onWindowStateChanged — e={"focused":true}
[2021-02-02 14:28:36:468] [e0] GitService.onWindowStateChanged completed • 0 ms
</details>

<details>
  <summary>Output : (GitLens (Git))</summary>
[2021-02-02 14:25:45:604] [c:\Project OpenSource\scriban\.git\rebase-merge] git rev-parse --show-toplevel • FAILED 42 ms 

Error: Command failed: C:\Program Files\Git\cmd\git.exe -c core.longpaths=true -c core.quotepath=false -c color.ui=false rev-parse --show-toplevel
fatal: this operation must be run in a work tree

[2021-02-02 14:26:04:642] [c:\Project OpenSource\scriban\.git\rebase-merge] git rev-parse --show-toplevel • FAILED 41 ms 

Error: Command failed: C:\Program Files\Git\cmd\git.exe -c core.longpaths=true -c core.quotepath=false -c color.ui=false rev-parse --show-toplevel
fatal: this operation must be run in a work tree
</details>

- GitLens Version: v11.2.0
- Git Version: 2.30.0.windows.2

- VSCode Version: 1.52.1 x64
- OS Version: Windows 10 PRO 20H2

Steps to Reproduce:

1.  Configure git config with the following params:
```
[difftool "code"]
    cmd = code  $LOCAL $REMOTE --diff -rw
[mergetool "code"]
    cmd = code $MERGED -rw
    keepBackup = false
[merge]
    tool = code
[diff]
    tool = code
[core]
    editor = code -rw
[commit]
    verbose = 2
[mergetool]
    keepBackup = false
```
2. Create a few commits in a branch in a repo
3. run `git rebase -i master`

You will receive a notification:
![image](https://user-images.githubusercontent.com/1175469/106615151-333ec080-657d-11eb-8555-21bb60097122.png)
Interective rebase is not started.

**Comment by DoctorPolski** [comment] 2021-02-02 19:29
Sadly this happened to me today also :(

**Comment by DoctorPolski** [comment] 2021-02-02 19:33
I notice this is in the patch notes for v11.2.0

- Adds a Switch to Text button on the Interactive Rebase Editor to open the text rebase todo file — note that closing either document will start the rebase

**Comment by DavideDaniel** [comment] 2021-02-02 20:40
Yep this broke for me as soon as vscode updated today.

**Comment by marvingbh** [comment] 2021-02-02 20:53
Same here

**Comment by nickzylstra** [comment] 2021-02-02 21:45
➕

**Comment by eamodio** [comment] 2021-02-02 22:55
For all those reporting this, was this working prior to the update? Is there any more details you can provide? I am currently unable to reproduce this.

**Comment by eamodio** [comment] 2021-02-02 22:57
Nm, I can reproduce now -- it only happens with VS Code 1.52 (1.53-insiders is fine). Will hopefully have a fix shortly. Really sorry for the inconvenience

**Comment by DoctorPolski** [comment] 2021-02-02 23:51
No problem Eric. Thank you for your swift response and continued excellent service to the coding community.

**Closed** 2021-02-03 01:16 UTC
Labels: bug

**Comment by eamodio** [comment] 2021-02-03 01:19
OK, the 11.2.1 release is building now and will be out shortly. The issue turned out to have nothing to do with the VS Code version, but instead about the window the rebase launched into. If the VS Code window had the rebasing repository open in it, then everything worked, but if it didn't it would fail.

Thanks again for your patience! 😄
