### ISSUE TITLE
Inline git commit history inserts in between code

### ISSUE THREAD

**Issue by XsongyangX** [eamodio/vscode-gitlens#1224] opened 2020-12-01 01:02 UTC
Hello. I noticed that GitLens' inline commit history time stamp inserts into the middle of my code when typing. This happens not all the time, or I wouldn't be able to write anything at all. 😅 It happens mostly when the editor is busy computing something, like C++ Intellisense's auto completion.

I can't provide screenshots because the behavior lasts one second or two. It is also difficult to reproduce because it depends on background processes' stress on the CPU.

When the bug happens, the cursor jumps suddenly to the end of the line, usually far enough to slide the window to the right. I can wait for the cursor to come back to the correct position, or move it to another line to fix the problem. 

- GitLens Version: 11.0.6
- Git Version: git version 2.28.0.windows.1

**VSCode version**
Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Initialize a git repository.
2. Write code in a language with an extension in VSCode. The extension should preferably be slow, e.g. C++.
3. Commit.
4. Keep writing code and depending on CPU stress caused by the VSCode, your cursor will move behind the one-liner commit time stamp.

**Comment by eamodio** [comment] 2021-06-22 03:59
Duplicate of #1477

**Closed by eamodio** 2021-06-22 03:59 UTC
Labels: potential-bug, triage
