### ISSUE TITLE
Inline blame "comment" showing up on the left hand side of new text

### ISSUE THREAD

**Issue by boblauer** [eamodio/vscode-gitlens#221] opened 2017-11-30 20:20 UTC
- GitLens Version: 6.3.0
- VSCode Version: 1.19.0-insider
- OS Version: OSX 10.12.6 (Sierra)

Steps to Reproduce:

1. Move to a new line and being typing quickly

Not always, but occasionally the in-line blame will show up to the left of the text that you're typing:

![image](https://user-images.githubusercontent.com/824632/33452846-25cc37fc-d5d9-11e7-9eed-06fb8c4bca24.png)

I've also seen it show up after some text, but then any new text is added to the right of the comment, so it's actually in the middle of the line of text:

![image](https://user-images.githubusercontent.com/824632/33452921-6f0f4594-d5d9-11e7-81b4-f959718819a9.png)

**Comment by eamodio** [comment] 2017-12-02 16:57
This is a duplicate of https://github.com/eamodio/vscode-gitlens/issues/190. Unfortunately there isn't much I can do here as this is a vscode issue.

**Closed by eamodio** 2017-12-02 16:57 UTC
Labels: duplicate, vscode issue
