### ISSUE TITLE
GitLens blocks AltGR input

### ISSUE THREAD

**Issue by OttoRobba** [eamodio/vscode-gitlens#227] opened 2017-12-12 19:59 UTC
Mac OS allows us to use option/alt + key for punctuation.
The cedilla character (ç) is created through option + c, is not inputted as the shortcut opens up gitlens "Show commit file details".

- GitLens Version: 6.4.0
- VSCode Version: 1.18.1
- OS Version: Mac OSX 10.12.6

Steps to Reproduce:

1. Using default U.S. locale, press `option` + `c`

**Comment by eamodio** [comment] 2017-12-12 20:22
Duplicate of https://github.com/eamodio/vscode-gitlens/issues/104.

Please try setting `"gitlens.keymap": "chorded"` for a set of shortcut keys that should not conflict. Or `"gitlens.keymap": "none"` to not have GitLens automatically add any shortcut keys at all

**Closed by eamodio** 2017-12-12 20:22 UTC
