### ISSUE TITLE
rendering issue

### ISSUE THREAD

**Issue by vip32** [eamodio/vscode-gitlens#15] opened 2016-11-15 21:36 UTC
what could be causing this? alle lens stuff is rendered outside the editor

![image](https://cloud.githubusercontent.com/assets/164303/20325200/e8b83f26-ab83-11e6-8b59-acdffc246846.png)

**Comment by eamodio** [comment] 2016-11-15 21:48
@vip32 this is caused by this vscode bug: https://github.com/Microsoft/vscode/issues/15389 in 1.7.1 -- it is already fixed in the latest insiders build

**Closed by eamodio** 2016-11-15 21:48 UTC

**Comment by vip32** [comment] 2016-11-15 22:20
yes that solved it, thx
