### ISSUE TITLE
Open Revision quickpick results in empty file

### ISSUE THREAD

**Issue by sQVe** [eamodio/vscode-gitlens#220] opened 2017-11-30 08:01 UTC
- GitLens Version: **6.3.0**
- VSCode Version: **1.18.1-1**
- Linux Version:  **4.13.12-1**

Steps to Reproduce:
1. Open _File History_ and select a previous commit.
2. Select _Open Revision_ to see the file at that commit.

-------
First and foremost, thank you for providing a great extension/tool!

I cannot open a file at a specific revision (commit) when using Git Lens. When trying to _Open Revision_ on a specific commit it **opens a file that is empty**. This is something that is part of my workflow so it is a bit of a hindrance. Does this work for anyone?

Happy to provide more information if needed!

**Comment by monk-time** [comment] 2017-11-30 13:50
Can confirm, in 6.3.0 Open Revision works only if I choose it in a right-click menu on a file in the Git Lens sidebar section. But if I do `Alt+H` → \<older commit\> → Open Revision, nothing happens.

**Comment by bochen2014** [comment] 2017-11-30 23:39
it's the same on my mackbook

I think this is a critical issue to be fixed as it's such a useful feature

**Comment by bochen2014** [comment] 2017-11-30 23:49
@monk-time  so how do you check a particular file revision with gitlens?
I tried your approach, but the gitlens sidebar section doesn't provide a file-tree view, it only contains a commit-tree view; i.e. you can't locate a file there and open its hisotry revisions

**Comment by monk-time** [comment] 2017-12-01 04:42
@bochen2014, of course, but if you know which commit modified a file you are interested in, you can expand it in the Branches tree and open the file from there. It's not as convenient as through File History, just a workaround until this is fixed.

**Comment by bochen2014** [comment] 2017-12-01 09:29
thanks

**Comment by monk-time** [comment] 2017-12-02 12:55
@eamodio I see it's labeled as `alt-feature`, but just in case there's some misunderstanding: this is not a feature request but a bug, and something that I recall working previously. Doing `Alt+H` → <older commit> → "Open Revision" triggers the following four errors in the console:

<details>

	textModelResolverService.ts:89 Unable to open 'gitlens-git:2015%5Caoc13%3Ace71eeab.js?%7B%22repoPath%22%3A%22d%3A%2FCode%2Fadvent-of-code%22%2C%22fileName%22%3A%22C%3A%2FProgram%20Files%2F_my%2FVS%20Code%2F2015%2Faoc13.js%22%2C%22sha%22%3A%22ce71eeab560d1c9a6918d43e9ec36ecd0213fef9%22%7D' resource is not available.
	(anonymous) @ textModelResolverService.ts:89
	g @ winjs.base.raw.js:1170
	enter @ winjs.base.raw.js:852
	_run @ winjs.base.raw.js:1068
	_completed @ winjs.base.raw.js:1036
	then @ winjs.base.raw.js:1566
	enter @ winjs.base.raw.js:747
	_run @ winjs.base.raw.js:1068
	_setCompleteValue @ winjs.base.raw.js:1052
	g @ winjs.base.raw.js:1170
	enter @ winjs.base.raw.js:852
	_run @ winjs.base.raw.js:1068
	_completed @ winjs.base.raw.js:1036
	e.resolveOk @ lazyPromise.ts:65
	e._receiveOneMessage @ rpcProtocol.ts:72
	(anonymous) @ rpcProtocol.ts:32
	(anonymous) @ rpcProtocol.ts:157
	e.invoke @ callbackList.ts:36
	e.fire @ event.ts:123
	(anonymous) @ ipc.net.ts:82
	emitOne @ events.js:96
	emit @ events.js:191
	readableAddChunk @ _stream_readable.js:178
	Readable.push @ _stream_readable.js:136
	onread @ net.js:560

	index.js:41 [uncaught exception]: Error: resource is not available
	onError @ index.js:41
	(anonymous) @ index.js:110
	emitOne @ events.js:96
	emit @ events.js:191
	window.onerror @ C:\Program Files\_my\VS Code\resources\electron.asar\renderer\init.js:135
	i.globals.onerror @ errorTelemetry.ts:64

	index.js:44 Error: resource is not available
		at textModelResolverService.ts:90
		at Object.g [as _notify] (winjs.base.raw.js:1170)
		at Object.enter (winjs.base.raw.js:852)
		at n.Class.derive._creator._run (winjs.base.raw.js:1068)
		at n.Class.derive._creator._completed (winjs.base.raw.js:1036)
		at n.Class.define.cancel.then (winjs.base.raw.js:1566)
		at Object.enter (winjs.base.raw.js:747)
		at n.Class.derive._creator._run (winjs.base.raw.js:1068)
		at n.Class.derive._creator._setCompleteValue (winjs.base.raw.js:1052)
		at Object.g [as _notify] (winjs.base.raw.js:1170)
	onError @ index.js:44
	(anonymous) @ index.js:110
	emitOne @ events.js:96
	emit @ events.js:191
	window.onerror @ C:\Program Files\_my\VS Code\resources\electron.asar\renderer\init.js:135
	i.globals.onerror @ errorTelemetry.ts:64

	textModelResolverService.ts:90 Uncaught Error: resource is not available
		at textModelResolverService.ts:90
		at Object.g [as _notify] (winjs.base.raw.js:1170)
		at Object.enter (winjs.base.raw.js:852)
		at n.Class.derive._creator._run (winjs.base.raw.js:1068)
		at n.Class.derive._creator._completed (winjs.base.raw.js:1036)
		at n.Class.define.cancel.then (winjs.base.raw.js:1566)
		at Object.enter (winjs.base.raw.js:747)
		at n.Class.derive._creator._run (winjs.base.raw.js:1068)
		at n.Class.derive._creator._setCompleteValue (winjs.base.raw.js:1052)
		at Object.g [as _notify] (winjs.base.raw.js:1170)
	(anonymous) @ textModelResolverService.ts:90
	g @ winjs.base.raw.js:1170
	enter @ winjs.base.raw.js:852
	_run @ winjs.base.raw.js:1068
	_completed @ winjs.base.raw.js:1036
	then @ winjs.base.raw.js:1566
	enter @ winjs.base.raw.js:747
	_run @ winjs.base.raw.js:1068
	_setCompleteValue @ winjs.base.raw.js:1052
	g @ winjs.base.raw.js:1170
	enter @ winjs.base.raw.js:852
	_run @ winjs.base.raw.js:1068
	_completed @ winjs.base.raw.js:1036
	e.resolveOk @ lazyPromise.ts:65
	e._receiveOneMessage @ rpcProtocol.ts:72
	(anonymous) @ rpcProtocol.ts:32
	(anonymous) @ rpcProtocol.ts:157
	e.invoke @ callbackList.ts:36
	e.fire @ event.ts:123
	(anonymous) @ ipc.net.ts:82
	emitOne @ events.js:96
	emit @ events.js:191
	readableAddChunk @ _stream_readable.js:178
	Readable.push @ _stream_readable.js:136
	onread @ net.js:560

</details>

**Comment by eamodio** [comment] 2017-12-02 16:55
@monk-time sorry for the confusion on the labeling -- I was using `alt-feature` to mean bug (it was my little joke to the political state of things in the use with the alt-right, fake-news, etc). I've changed it to `bug` to avoid any further confusion.

This is clearly a bug (regression) and one that I take seriously. Unfortunately fixing this issue turned into a bit of an unraveling of related issues, which then lead to a decent refactoring (and add on top of it I've got a nasty cold that's been getting worse for the last week). I have now fixed this issue, and hopefully a whole lot of related issues, but because of the scope of the changes I'm not going to push it to the marketplace until I get some more burn in on the beta.

Please try out the latest [GitLens beta](https://github.com/eamodio/vscode-gitlens/releases/tag/v6.4.0-beta) and let me know if you experience any issues.

Again sorry for the inconvenience with this bug 😢

**Comment by bochen2014** [comment] 2017-12-03 02:35
thanks @eamodio for the updates.  but how install gitlens from source code?
I downloaded the soruce code but don't know how to install it

**Comment by eamodio** [comment] 2017-12-03 03:28
@bochen2014 sorry I screwed up on the post to github and didn't attach the vsix. Its been fixed. For further install instructions you can use these: https://github.com/eamodio/vscode-gitlens/wiki/Installing-Pre-release-Versions

**Comment by bochen2014** [comment] 2017-12-03 04:17
thanks. 
I copied the source code to `~/.vscode/extensions/` and did a `npm install&& npm compile`; it worked for me as well ; 
but thanks for the update!

**Closed** 2017-12-12 19:16 UTC
Labels: bug
