### ISSUE TITLE
Disable 'Open Changes'... buttons / menu

### ISSUE THREAD

**Issue by jasperkuperus** [eamodio/vscode-gitlens#899] opened 2019-11-08 15:51 UTC
So, is there a way to disable this menu:

![G4UUu](https://user-images.githubusercontent.com/1655683/68489694-e10ed280-0247-11ea-8d09-c7e0d8624363.png)

I personally hardly use this menu and it takes up quite some space in my tabbar, so I'd rather hide it. But I can't seem to find the option responsible for that, if there is any.

**Comment by eamodio** [comment] 2019-11-11 06:41
Duplicate of https://github.com/eamodio/vscode-gitlens/issues/900

**Closed by eamodio** 2019-11-11 06:41 UTC
Labels: type: question
