### ISSUE TITLE
Comparing un-staged changes against a branch

### ISSUE THREAD

**Issue by lucianthorr** [eamodio/vscode-gitlens#844] opened 2019-09-04 17:43 UTC
I mark this as a question because I may just be misusing gitlens.

For a period of time, I was able to compare "origin/master" against my local branch using the "Compare with Working Tree" option.  This allowed me to compare a true diff of all my files against origin/master.
In the more recent versions, the same option seems to only compare the most recent local commit against "origin/master"

Was something changed?  Is it possible for me to set up the older behavior?  I found it really useful for refactoring before committing.
Thanks for the help

**Comment by eamodio** [comment] 2019-09-04 17:51
Duplicate of #842 -- this will be fixed in the next release.

**Closed** 2019-09-04 17:51 UTC
Labels: status: duplicate
