### ISSUE TITLE
Copy Remote File Url no longer includes code line(s) in the copied URL

### ISSUE THREAD

**Issue by erikphansen** [eamodio/vscode-gitlens#1463] opened 2021-04-14 16:41 UTC
- GitLens Version: 11.4.0
- Git Version: 2.31.0

- VSCode Version: 1.55.2
- OS Version: macOS 10.15.7 (19H524)

Steps to Reproduce:

1. Run the `GitLens: Copy Remote File Url` command
2. See that a link to the file is copied but it does not contain a "deep link" to the selected line.

Example: I'd expect `https://github.com/department-of-veterans-affairs/vets-website/blob/5e8c85fea79c92e4a9f7f53a9c8a70cd562c52cf/src/applications/claims-status/actions/index.jsx` to be `https://github.com/department-of-veterans-affairs/vets-website/blob/5e8c85fea79c92e4a9f7f53a9c8a70cd562c52cf/src/applications/claims-status/actions/index.jsx#L9`

I use this command _a lot_ and only started noticing it today, possibly due to the recent release of VSCode 1.55.2.

**Comment by erikphansen** [comment] 2021-04-14 17:10
I just had a coworker confirm that updating to VSCode 1.55.2 created this same issue for him.

**Comment by eamodio** [comment] 2021-04-14 17:48
Duplicate of #1458, which is fixed in 11.4.1 (will be in the marketplace any minute now)

**Closed by eamodio** 2021-04-14 17:48 UTC
Labels: potential-bug, triage

**Comment by erikphansen** [comment] 2021-04-14 18:29
Sorry I missed #1458. I swear I did a search first 😆

**Comment by eamodio** [comment] 2021-04-14 19:00
Hehe, no worries 😁
