### ISSUE TITLE
GitLens doesn't work on virtual workspaces

### ISSUE THREAD

**Issue by j0k4rX** [eamodio/vscode-gitlens#1520] opened 2021-05-25 12:11 UTC
- **GitLens doesn't work on any repo pulled from GitHub**

After enabling all extensions for workspace (multiple times), yet the extensions are dimmed in color
it shows `This extension has been disabled because it doesn't support virtual workspace`

![Screenshot 2021-05-25 170024](https://user-images.githubusercontent.com/71499522/119494369-0e1bcb00-bd83-11eb-8b2a-f1ef6ad27325.jpg)

Today, I freshly installed vscode insiders.. signed-in with my github account
also installed Git (added in path directory) 
and then GitLens extension

I added this code in my settings.json
```
"git.enabled": true,
"git.path": "C:\\Program Files\\Git\\cmd\\git.exe",

"gitlens.outputLevel": "debug"
```
- GitLens Version: 11.4.1
- Git Version: 2.31.1.windows.1

- VSCode Version: 1.57.0-insider 
- OS Version: windows 10 pro

**Comment by j0k4rX** [comment] 2021-06-04 13:27
@eamodio, please look into this matter.

**Comment by eamodio** [comment] 2021-06-12 07:02
Duplicate of #1495

**Closed by eamodio** 2021-06-12 07:02 UTC
Labels: potential-bug, triage
