### ISSUE TITLE
Disable Connect with GitHub prompt

### ISSUE THREAD

**Issue by balibebas** [eamodio/vscode-gitlens#1241] opened 2020-12-07 05:46 UTC
> GitLens doesn't collect any telemetry -- that setting was old (and unused) and has been removed in GitLens 11

Today GitLens prompted me to connect to GitHub which is another form of Telemetry (if enabled). Is there a way to prevent this prompt from occurring now that the telemetry disable feature has been removed?

_Originally posted by @balibebas in https://github.com/eamodio/vscode-gitlens/issues/1094#issuecomment-739680748_

**Comment by eamodio** [comment] 2020-12-07 06:54
This is a duplicate of #1208

**Closed by eamodio** 2020-12-07 06:54 UTC
Labels: status: duplicate
