### ISSUE TITLE
Symlink related bug

### ISSUE THREAD

**Issue by ampresent** [eamodio/vscode-gitlens#780] opened 2019-07-05 14:05 UTC
- GitLens Version: 9.8.2
- VSCode Version: 1.36.0-insider
- OS Version: 10.14.5

Steps to Reproduce:

1. `mkdir /work`
2. `ln -s /work /home/username/stuff`
3. work in /home/username/stuff
4. Use GitLens to see line history
5. Fail. And we see `/work/home/username/stuff/file1` pattern in the log

This bug is in method `resolve` in `gitUrls.ts`, where 
repoPath is recognized as `/work`, while `fileName` is recognized as `/work/home/username/stuff/file1`. `resolve` simply join these two strings giving the wrong pathname.

**Comment by eamodio** [comment] 2019-11-11 15:52
Duplicate of https://github.com/eamodio/vscode-gitlens/issues/677

**Closed by eamodio** 2019-11-11 15:52 UTC
Labels: status: duplicate, type: bug
