### ISSUE TITLE
Secondary, blank repository appears repeatedly in Repositories view

### ISSUE THREAD

**Issue by mliq** [eamodio/vscode-gitlens#405] opened 2018-06-07 21:46 UTC
- GitLens Version: 8.3.3
- VSCode Version: 1.24.0 (also occurred on 1.23.1)
- OS Version: 10.13.5

Steps to Reproduce:

1. Work as normal in a large single repository project. (Note that this project does have a second package.json and .gitignore in a subfolder, but it does not have a git repo there.)
2. Eventually, notice that gitExplorer shows a secondary, completely blank repository.
3. Close the blank repository via right click menu.
4. Minutes or hours later, the empty repository reappears.
repeat ad infinitum.

Note that the VSCode build in VCS does not appear to have this issue.

Things I have tried unsuccessfully:
`"git.autoRepositoryDetection": false`
`"gitlens.advanced.repositorySearchDepth": 0`

![screenshot 2018-06-07 16 32 12 copy](https://user-images.githubusercontent.com/7573605/41127877-e2850914-6a71-11e8-9718-ac67ddc73cce.png)

**Comment by eamodio** [comment] 2018-06-08 05:27
@mliq And there is no `.git` folder some where else in the folder tree? If not, are you opening any files outside of the workspace, because GitLens will try to detect repos for just single files opened in the same window.

Can you please enable output channel logging by setting "gitlens.outputLevel": "verbose" in your settings.json. This will enable logging to the GitLens channel in the Output pane. Once enabled, please attempt to reproduce the issue (if possible) and attach the relevant log lines from the GitLens channel.

**Comment by mliq** [comment] 2018-06-08 14:50
@eamodio 
* there are no other `.git` folders. However, one subdirectory does contain a secondary `.gitignore` and `.vscode` - could this impact it? 
* I am not opening any files outside of the workspace when this happens. 
* turned on logging and will submit here when it happens again.

**Comment by eamodio** [comment] 2018-06-08 17:05
Thanks, none of those things *should* affect GitLens finding a repo. Looking forward to the logs.

**Comment by eamodio** [comment] 2018-07-09 04:59
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!

**Comment by mliq** [comment] 2018-08-23 17:02
@eamodio I am not able to re-open, should I make a duplicate or can you re-open?

Attached here is a log:
[gitlens.log](https://github.com/eamodio/vscode-gitlens/files/2315414/gitlens.log)

**Closed** 2018-12-02 09:33 UTC
Labels: bug
