### ISSUE TITLE
Unable to Open any Remote on GHE

### ISSUE THREAD

**Issue by robbyki** [eamodio/vscode-gitlens#886] opened 2019-10-28 17:12 UTC
Issue Type: <b>Bug</b>

I have seen other issues reporting this but none of the recommendations or solutions as far as I can tell has solved the issue for me. When trying to open any file on remote Github Enterprise, I'm given a box to fill with no select options. Gitlens has already been correctly configured to view repo. 

Extension version: 10.1.1
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 3.10.0-1062.1.2.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2669)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|30.69GB (2.82GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|17%|
</details>

**Comment by eamodio** [comment] 2019-11-11 06:48
Please enable output channel logging by setting `"gitlens.outputLevel": "debug"` in your settings. This will enable logging to the *GitLens* channel in the *Output* pane. Once enabled, please reproduce the issue and attach the log from the *GitLens* channel.

**Comment by eamodio** [comment] 2020-03-30 07:10
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!

**Closed by eamodio** 2020-03-30 07:10 UTC
Labels: status: needs more info, type: potential bug
