### ISSUE TITLE
Using the extension manager it says it takes >450ms to load the plugin. This seems like a really long time

### ISSUE THREAD

**Issue by niemyjski** [eamodio/vscode-gitlens#233] opened 2017-12-14 23:29 UTC
- Extension Name: gitlens
- Extension Version: 6.4.0
- OS Version: Darwin x64 17.3.0
- VSCode version: 1.19.0

 We have written the needed data into your clipboard. Please paste:

```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 453,
		"activateCallTime": 78,
		"activateResolvedTime": 64,
		"activationEvent": "*"
	}
}
```

**Comment by Philip-Trettner** [comment] 2017-12-16 18:11
I have the same problem:

- Extension Name: gitlens
- Extension Version: 6.4.0
- OS Version: Windows_NT x64 10.0.16299
- VSCode version: 1.19.0

 We have written the needed data into your clipboard. Please paste:

```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 620,
		"activateCallTime": 68,
		"activateResolvedTime": 1042,
		"activationEvent": "*"
	}
}
```

**Comment by eamodio** [comment] 2017-12-17 18:56
Duplicate of https://github.com/eamodio/vscode-gitlens/issues/225

**Closed by eamodio** 2017-12-17 18:56 UTC
Labels: duplicate
