### ISSUE TITLE
<Toggle File Blame Annotations> Icon disappears when clicked

### ISSUE THREAD

**Issue by cruzzoe** [eamodio/vscode-gitlens#831] opened 2019-08-27 13:46 UTC
When clicking button: <Toggle File Blame Annotations> it disappears. This didnt use to happen.
![Capture](https://user-images.githubusercontent.com/11476338/63776463-5de11000-c8d9-11e9-9451-17863991971e.PNG)

VSCODE version:  1.37.1
Gitlens version:: 9.9.3

VSCODE client os: Windows 10
Gitlens installed on Redhat 7

Workaround in place: use the command pallet

Looking inside developer console I see: Failed to load resource: net::ERR_NOT_IMPLEMENTED

![Capture 2PNG](https://user-images.githubusercontent.com/11476338/63776678-badcc600-c8d9-11e9-87db-cad423401860.PNG)

**Comment by eamodio** [comment] 2019-09-03 07:37
Duplicate of https://github.com/eamodio/vscode-gitlens/issues/790

**Closed by eamodio** 2019-09-03 07:37 UTC
