### ISSUE TITLE
Compare working tree with... (2 Bugs)

### ISSUE THREAD

**Issue by mrbeak** [eamodio/vscode-gitlens#877] opened 2019-10-11 13:22 UTC
- GitLens Version: 9.9.1
- VSCode Version: 1.32.2
- OS Version: Win7

Steps to Reproduce:

1. Open any git repo with several commits
2. F1 + type Compare Working Tree With...  + type HEAD~ + Enter
3. In the compare view open any of the files changed. Left side is the old version, right side the new version. Now I'm able to edit the left side of the file (which is in the git index) but not the right side of the file which is on my disk.

Shouldn't this be vice-versa? (BUG 1)

Next:

4. Remember the file you just had open
5. Clear diff results
6. Open the file you remembered in (4) and edit it, save it
7. F1 + type Compare Working Tree With...  + type HEAD~ + Enter

On the right side the new changes from 6 are not visible. (BUG 2)

For me this would make sense if I would have executed Compare HEAD with... command (gitlens.diffHeadWith) as the chanes from 6 are not yet commited so not part of HEAD. But as I executed Compare Working Tree with... command (gitlens.diffWorkingWith) I expect unstaged changes to be part of the diff.

**Comment by OttlikG** [comment] 2019-10-14 19:02
I also came across the second bug.

**Comment by eamodio** [comment] 2019-10-25 06:23
@mrbeak I can't reproduce bug # 1 (and it shouldn't be possible as vscode should block that).

@mrbeak @OttlikG Can you please try with GitLens 10.1, I believe it should be fixed.

**Comment by eamodio** [comment] 2019-11-06 07:42
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!

**Closed by eamodio** 2019-11-06 07:42 UTC
Labels: status: needs more info, type: potential bug

**Comment by mrbeak** [comment] 2019-11-08 08:41
Sorry I did not have the time to test again. Today I had.

With Version 1.40 (vscode) and Version 1.10.2 (gitlens) both(!) are fixed and cannot be reproduced by me on Windows!

Thanks
