### ISSUE TITLE
Indentation issue - "editor.renderWhitespace": "all"

### ISSUE THREAD

**Issue by JarvisPrestidge** [eamodio/vscode-gitlens#136] opened 2017-08-29 23:24 UTC
The cursor will indent the line it's on by a single space (or more sometimes) if using the `editor.renderWhitespace: all` settings option and the GitLens extension.

- GitLens Version: v4.4.1
- VSCode Version: 1.15.1
- OS Version: Ubuntu 17.04 Gnome

Steps to Reproduce:

1. Disable all extension, except GitLens.
2. Enable `"editor.renderWhitespace": "all"` in `settings.json`
3. Open a GoLang file (I've only been able to reproduce with .go files).
4. Observe the cursor indenting every line it moves onto by a single space.

> Note: seems to indent the line the instant the blame annotation is rendered.

Example:
![example](https://media.giphy.com/media/3oKGzolER3usJG7yI8/giphy.gif)

**Comment by eamodio** [comment] 2017-08-30 01:02
This is a duplicate of https://github.com/eamodio/vscode-gitlens/issues/129, unfortunately right now there isn't much I can do as this is a vscode issue.

**Closed by eamodio** 2017-08-30 01:02 UTC
