### ISSUE TITLE
Gitlens View doesn't save position

### ISSUE THREAD

**Issue by NavyAdmiral** [eamodio/vscode-gitlens#453] opened 2018-07-20 12:32 UTC
- GitLens Version: latest

- VSCode Version: 1.26 insiders
- OS Version: Win 10

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/40662484/43002609-6ff5b980-8c3a-11e8-95cb-8193d9d548c1.png)

1.Move Gitlens up/down
2.Reload vscode
3.Gitlens moved position was not saved.

**Comment by eamodio** [comment] 2018-07-20 16:49
This is technically a duplicate of https://github.com/eamodio/vscode-gitlens/issues/447
And unfortunately it is a vscode issue.

**Closed by eamodio** 2018-07-20 16:49 UTC
