### ISSUE TITLE
Git blame relative dates are incorrect

### ISSUE THREAD

**Issue by robCrawford** [eamodio/vscode-gitlens#191] opened 2017-11-08 13:25 UTC
- GitLens Version: 5.7.1
- VSCode Version: 1.17.2
- OS Version: Windows 7 Professional [Version 6.1.7601]

Steps to Reproduce:
1. Toggle on Gitlens: Show file blame annotations

The screenshot shows Atom on the left displaying the absolute commit date 2016-11-09, on the right is VSCode displaying the relative date 'a month ago' which is incorrect.
This screenshot was taken on 08th November 2017, the commit in question is dated 09th November 2016. I have checked that it is the same commit.
![blame](https://user-images.githubusercontent.com/1692200/32550731-22c6987c-c486-11e7-9d48-347175e66615.png)

**Comment by eamodio** [comment] 2017-11-08 22:36
Duplicate of https://github.com/eamodio/vscode-gitlens/issues/185

**Closed by eamodio** 2017-11-08 22:36 UTC
