### ISSUE TITLE
Rebase "onto" line in the interactive rebase UI is sometimes duplicated in the commits to rebase

### ISSUE THREAD

**Issue by Mumeii** [eamodio/vscode-gitlens#1201] opened 2020-11-23 11:49 UTC
Hi

I encounter a strange behhavior with the new rebase window. 

I'd like to know : 
* If it's either a bug or a normal behavior.
* And if it's a normal behavior, what it mean ?

---
OS : Mac OS Catalina v10.15.7
VSCode version : 1.51.1
Gitlens version : 11.0.4

---

I want to rebase the following set of commits over themself : 

```
* c9c925f (HEAD -> tech/CI-enhancement, origin/tech/CI-enhancement) fixup! tech: remove install step & dockerize tests
* 4de658e tech: remove install step & dockerize tests
* 22a9d09 tech: Jest & jest-html-reporter version update To prepare a subsequent NodeJS version upgrade
* 89f3f0a tech: turn jest testResultsProcessor into reporter Doing so in order to ...
* 1cbc2f3 tech: ignore node_modules* : easy version swapping
* 525325a tech: major enhancement to Dockerfile
* d80fada tech: define NODE_ICU_DATA only when necessary
* a1cb5aa tech: remove old useless Jenkinsfile-open & -close
* dc9d67b tech: remove useless comments
* 78bdbd2 tech: add .dockerignore
* 1bc9ae0 tech: add timestamps to CI log lines
* 070ee0a fixup! tech: use stages for docker builds
* c4f4a61 fixup! tech: use stages for docker builds
* f213b58 tech: use stages for docker builds
* 0889eb9 fixup! tech: prevent chromium download for tests
* 99ff719 tech: prevent chromium download for tests
```

To do so, I perform a `git rebase -i HEAD~16`, as I usualy do

I was expecting to have 16 lines displayed, like the command line version of git rebase usually do.

Instead of that, I got the following display.

<img width="2880" alt="Screenshot 2020-11-23_12-32-45-744" src="https://user-images.githubusercontent.com/17477935/99957573-36048480-2d88-11eb-90f4-e7041cbdfba1.png">

Notice : 
* the extra line at the end which seems to be a duplicate of the first one, but without any SHA1 associated
* I have `--autosquash` activated by default on rebase, and that there is `fixup!`entries in the commits I intend to rebase

What mean this extra final line been displayed ?

Thanks you for your feedback about it, and more importently, for Gitlens which is a great tool !

**Comment by lupalby** [comment] 2020-11-24 23:40
I was about to open an issue myself about the same thing. I think it's a bug, I do not understand what kind of feature would that be. In my case, the last line does show an SHA1, that is the same as the commit that it shares the message with. I have done a few rebases in the last week, and usually the duplicated line is the same as the first line, but today it was the same as the second line. Even stranger! 
![image](https://user-images.githubusercontent.com/34496994/100163772-44779c80-2e6b-11eb-81e9-8e09d1305b32.png)

In general I don't mind the new rebase window, I find it more user-friendly especially for some of my colleagues that aren't as well-versed in git, but this creates some confusion.

**Comment by lupalby** [comment] 2020-11-24 23:43
Actually by looking at my screenshot I just realized that the title of the rebase is also incorrect "Rebasing 9 commits onto b733e3a3" is wrong, as it is clearly second to last commit in my local branch. Perhaps that last line is supposed to show which commit we are rebasing onto, to help giving an idea in which direction is the timeline (up or down), but since it picks the wrong commit as base it looks like a duplicate

**Comment by eamodio** [comment] 2020-11-29 08:24
Yeah, the last line it to provide extra context for the rebase -- the commit the rebase will be sitting on top of.

@lupalby Do you still see the wrong commit showing for the last line in the latest version (11.0.6)?

**Comment by lupalby** [comment] 2020-11-29 22:55
I just tried again, I still see the same behavior even with version 11.0.6. I reloaded the window too, just to make sure it was using the latest version after the update. The "context" commit should not be any of those that are being rebased.
![image](https://user-images.githubusercontent.com/34496994/100555810-e5db6580-3252-11eb-8f13-c77416699aa3.png)

**Comment by eamodio** [comment] 2020-12-02 07:15
@lupalby what does your rebase command look like that causes that output? I never see the "base" commit in the rebase list.

**Comment by lupalby** [comment] 2020-12-02 18:17
Nothing fancy really. I am in branch `am/os1` and I simply ran `git rebase -i origin/master`.
Let me know how else I can help debug this

**Comment by lupalby** [comment] 2020-12-02 18:41
And let me clarify. The rebase list is perfectly correct. The "base" commit is the wrong one, as I expect it to be the newest commit from master, that I am rebasing on top of, rather than one of the commits of my branch

**Comment by lupalby** [comment] 2020-12-02 19:08
@eamodio After some more digging I think the issue does not originate in your extension, but from Git. It is something to be aware of though, because if it is somehow a "normal" behavior of Git, it can invalidate the way you obtain info about the "base" commit.
Below you can see the rebase-todo both in VSC and using a plain notepad to show the raw text:
![image](https://user-images.githubusercontent.com/34496994/100917441-080bf800-348c-11eb-8f97-d5d20cdf69ab.png)
You can see that your interactive rebase UI shows just what is provided by the raw text. I am not quite sure why Git says `Rebase d8f36471..457c562a onto aea5061b`
`d8f36471` is the newest commit in origin/master, and `457c562a` is the latest commit I added in my branch. I am not 100% sure, but it could be that `aea5061b` was the first commit that I added into my branch when I started it, and it is not anymore the first one in there because I shuffled commits around during a previous interactive rebase, including some squash/fixups as well. If that is the case however, it happened weeks ago and I did other non interactive rebases in the meanwhile too, so I am surprised that it still remembers of that. If you move commits around and then try rebasing again afterwards, do you see a similar behavior?

**Comment by eamodio** [comment] 2020-12-02 22:36
Does anyone know why the `onto` on the line: ```# Rebase d8f36471..457c562a onto aea5061b (7 commands)``` above is also contained in the set of commits to be rebased? That seems completely wrong to me.

/cc @derrickstolee?

**Comment by derrickstolee** [comment] 2020-12-03 15:46
Cc: @dscho who knows a lot about this area.

**Comment by dscho** [comment] 2020-12-03 19:36
Hmm. The `aea5061b` commit really is supposed to be the one you rebase _onto_. I.e. if you truly call `git rebase -i origin/master`, I would be highly surprised if the interactive rebase showed anything but the shortened commit hash of `origin/master` after that `onto`.

Further, the revision range before that is generated [here](https://github.com/git/git/blob/v2.29.2/builtin/rebase.c#L272-L296), and it only shows a different base than `<onto>` if a differing `<upstream>` was provided, i.e. something like `git rebase -i --onto <onto> <upstream>` (the corresponding code would be [here](https://github.com/git/git/blob/v2.29.2/builtin/rebase.c#L1841)).

There is an exception to that rule: if you provide neither `<onto>` nor `<upstream>`, Git tries to figure out where you forked off of the remote-tracking branch that is configured as the "upstream" branch. From the [docs](https://git-scm.com/docs/git-rebase#_description):

> If <upstream> is not specified, the upstream configured in branch.<name>.remote and branch.<name>.merge options will be used (see git-config[1] for details) and the --fork-point option is assumed.

Details about the way the fork point is determined are found [here](https://git-scm.com/docs/git-rebase#Documentation/git-rebase.txt---no-fork-point):

> Use reflog to find a better common ancestor between `<upstream>` and `<branch>` when calculating which commits have been introduced by `<branch>`.
>
> When `--fork-point` is active, `fork_point` will be used instead of `<upstream>` to calculate the set of commits to rebase, where `fork_point` is the result of `git merge-base --fork-point <upstream> <branch>` command (see [git-merge-base](https://git-scm.com/docs/git-merge-base)). If `fork_point` ends up being empty, the `<upstream>` will be used as a fallback.

And crucially:

> If your branch was based on `<upstream>` but `<upstream>` was rewound and your branch contains commits which were dropped, this option can be used with `--keep-base` in order to drop those commits from your branch.

I think that might have happened here: the upstream might have been rewound at some stage.

**Comment by eamodio** [comment] 2020-12-04 05:51
@derrickstolee thank for the cc 😄 

@dscho Thank you for the write up. So, if I'm understanding it correctly, while GitLens should be able to rely on that `onto` value there are cases where it could end up being confusing to users. So maybe I should just hide the "onto" row, if the "onto" sha is in the list of sha to be rebased.

Does that make sense?

**Comment by lupalby** [comment] 2020-12-04 06:43
@dscho that is very insightful, thanks for sharing.
Just to clear the water, in all this I was always the only one pushing to Github, so there is no way that remote may have had changes that did not come from my local. I am sure I have never used `onto` or anything like that. I have originally created the branch off of master, then at a certain point I wanted to use some feature from a development branch before it was merged into master, so I rebased `am/os1` (my branch) on that branch with `git rebase -i origin/dev-branch` and once `dev-branch` got merged into master I rebased on master with `rebase -i origin/master`. During one of the rebase operations I have also moved commits around and squashed some of them, and the commit that was originally the first one of my branch (`aea5061b`) ended up somewhere in the middle. 
Could it be that combining rebase on a different branch with shuffling commits may have caused this mess? Since I never specified `onto`, it looks like git had to figure some stuff out by itself and something may have gone wrong.

If it is of any help, I am more than happy to test anything for any you. I truly appreciate everybody's work and this is the least I can do to give back.

**Comment by derrickstolee** [comment] 2020-12-04 16:28
I'm not so sure about @dscho's interpretation. It is entirely possible that the reason this happens is because `origin/master` was rewound, but `aea5061b` being the `onto` target _and_ selected as a `pick` commit seems **incredibly wrong** to me and makes me think this is a bug in Git. 

Instead, I expect the `onto` commit to match the current commit that `origin/master` is on, even though it is different from the base (`d8f36471`) of the range (`d8f36471..467c62a`).

There have been a lot of recent changes to `sequencer.c` in git/git, but I'm not an expert so I am having trouble parsing the changes and how they might affect the value of `shortonto`.

I have been unable to reproduce this behavior myself except by doing an "obviously wrong thing" such as `git rebase --onto HEAD~1 HEAD~2 HEAD`, which shows two `pick` commands onto one of the commits in that list! But that doesn't seem to be what you are attempting here.

**Comment by lupalby** [comment] 2020-12-15 17:38
What other information is needed?

**Comment by eamodio** [comment] 2020-12-15 23:04
@lupalby it was just a left over label -- corrected.

**Comment by eamodio** [comment] 2020-12-15 23:07
@derrickstolee yeah, I haven't been able to reproduce it myself either. It does feel like it's a bug in Git. @dscho What do you think?

In the interim, I think I should just hide the "onto" row, if the "onto" sha is in the list of sha to be rebased. Does that sound reasonable?

**Comment by derrickstolee** [comment] 2020-12-16 14:04
> In the interim, I think I should just hide the "onto" row, if the "onto" sha is in the list of sha to be rebased. Does that sound reasonable?

That sounds good to me. I think it solves the problem from the user perspective. We'll keep trying to reproduce and fix the bug in Git, but this is "just" a comment line so doesn't change functionality from Git's perspective.

**Comment by lupalby** [comment] 2020-12-16 18:18
I was able to reproduce the issue! Starting from master, here are the steps:
- create a new branch `test1` from `master`
- add a commit in `test1`
- create a new branch `test2` from `master`
- add a commit in `test2`
- add a second commit in `test2`
- `git rebase -i test1` and while doing it, swap the other of the 2 commits in `test2` that are being rebased
- switch to `test1` and add a second commit in `test1`
- switch to `test2` and rebase again on `test1` with `git rebase -i test1` (I don't think `-i` is necessary, but useful to see that everything seems to be working fine so far)
- now try to rebase again on master with `git rebase -i master` and here is what I see:
![image](https://user-images.githubusercontent.com/34496994/102387417-335f0e80-3f85-11eb-9635-fc6503bca080.png)

There are 2 issues there in my opinion: one is that the "onto" SHA is clearly incorrect, since it refers to one of the commits being rebased rather than the last commit in `master`.
The other puzzling bit is: why are the commits from `test1` being carried with `test2` while rebasing on `master`? I would expect that only the 2 commits that I pushed to `test2` should now be added on top of master, not all 4. If this is happening because I am using the rebase command improperly please let me know, that would be very helpful!

Here the relevant part of the raw content of the git-rebase-todo file:
```
pick 65790d62 first commit in test1
pick 9d92cf0c second commit in test1
pick e7e67a98 second commit in test2
pick b231985d first commit in test2

# Rebase df60b221..b231985d onto b231985d (4 commands)
(...)
```
where `df60b221` is actually the SHA of the last commit in `master`

**Comment by derrickstolee** [comment] 2020-12-16 19:31
Thank you, @lupalby, for the repro.

> The other puzzling bit is: why are the commits from `test1` being carried with `test2` while rebasing on `master`? I would expect that only the 2 commits that I pushed to `test2` should now be added on top of master, not all 4. If this is happening because I am using the rebase command improperly please let me know, that would be very helpful!

Let's take a look at the commit graph before and after each rebase.

Before the first rebase, we have:

```ShellSession
$ git log --graph --oneline --all
* 6e06b65 (HEAD -> test2) second in test2
* 2118724 first in test2
* b36ce79 (test1) first in test1
* a13d130 (main) base
```

and we swap the top two commits in `git rebase -i test1` to get:

```ShellSession
$ git log --graph --oneline --all
* a6eaa25 (HEAD -> test2) first in test2
* 8e08e0f second in test2
* b36ce79 (test1) first in test1
* a13d130 (main) base
```

We then add another commit onto `test1`:

```ShellSession
$ git log --graph --oneline --all
* f3a3492 (HEAD -> test1) second in test1
| * a6eaa25 (test2) first in test2
| * 8e08e0f second in test2
|/
* b36ce79 first in test1
* a13d130 (main) base
```

Notice how the "first in test1" commit is in both the `test1` branch and the `test2` branch, but not in the `main` branch? That means a `git rebase -i main` will include that commit in the list, possibly creating a new "matching" commit that is not in the history of `test1`. (If we don't change the rebase at all, then Git will keep the existing commit instead of creating a new one by updating the committer date.)

Of course, you had another rebase command, `git rebase -i test1`, which results in this graph:

```ShellSession
$ git log --graph --oneline --all
* 58a6208 (HEAD -> test2) first in test2
* b3ff1fa second in test2
* f3a3492 (test1) second in test1
* b36ce79 first in test1
* a13d130 (main) base
```

So, at this point, `git rebase -i main` from `test2` will take all commits in `test2` that are not in `main`, which includes the two commits in `test1`.

My `git-rebase-todo` file doesn't have the same comment bug that you do:

```
pick b36ce79 first in test1 # empty
pick f3a3492 second in test1 # empty
pick b3ff1fa second in test2 # empty
pick 58a6208 first in test2 # empty

# Rebase a13d130..58a6208 onto a13d130 (4 commands)
```

It's interesting that you constructed a simple example that shows this behavior on your machine, but it doesn't repro on my version of Git.

**Closed** 2020-12-16 20:09 UTC
Labels: bug

**Comment by lupalby** [comment] 2020-12-16 20:33
@derrickstolee thank you for the detailed explanation. First, some more details about my system:
Ubuntu 20.04.1 running in WSL, fully up-to-date, git version 2.25.1. Let me know if there could be any other info or log that could help you.
I tried to follow the steps again, running `git log --graph --oneline --all` at each step to make sure it looks like yours, and the graph follows exactly the same transformations as in your message. However at the last stage, when rebasing with master/main, mine shows the bug as in my earlier message.

Anyway, it is clear that this is not an issue with vscode-gitlens, but rather a Git issue, so perhaps should we move the conversation to the git repo? It is clearly not something that happens to me only, as I am not the one that opened this issue.
I am more than happy to help nail the issue down if I can.

Ultimately, I understand why the commits from test1 were brought with test2 when trying to rebase on main/master. What would be the correct way of using rebase to handle this use case?
I am working on a new feature in my branch. A colleague is working on another feature in his branch, and they ask me to verify that what we are independently developing is not breaking each other's code, so I rebase my branch on his, do the proper tests, and once we are satisfied I want to bring my branch back to be stemming out of main/master, of course containing only my commits. Based on what you showed, this last rebase would bring along all the commits from my colleague's branch. How can I make sure that doesn't happen? Should I just manually drop them in an interactive rebase? Or are there specific options to give to rebase to make sure this works properly?
I know this question is a bit off-topic, but I would really appreciate if you could help me understand this too! Thanks!

**Comment by derrickstolee** [comment] 2020-12-16 20:44
@lupalby: if you want the commits from `test2` that are not in `test1` to be rebased onto `master`, then you want the command `git rebase --onto master test1 test2`.

You are using Git 2.25.1, which is an old version. Perhaps update to the latest, v2.29.2 and try again?

**Comment by lupalby** [comment] 2020-12-16 23:41
@derrickstolee I see, I was using the latest version available through Ubuntu repositories.
I now got the latest version through `sudo add-apt-repository ppa:git-core/ppa` and I now have 2.29.2. With the latest version, everything looks normal. Sorry for wasting your time on something that has been fixed already, I didn't expect the Ubuntu repos to be so behind with the updates

**Comment by lupalby** [comment] 2020-12-17 00:30
@derrickstolee also thank you pointing me to using --onto, that does the trick!
Once situation that I did not manage to solve neither with regular `rebase` nor with `rebase --onto` is something like below:
```
A---B---C---D  master
                      \
                        E---F---G  test1
                                       \
                                        H---I---J test2 (HEAD)
```
if I remove a commit from `test1` (e.g. `F`), and I try to keep `test2` up-to-date with `test1`, I would run something like `git rebase test1 test2`, or even `git rebase --onto test1 test1 test2` but in both cases the command will "resurrect" commit F resulting in something like this:
```
A---B---C---D  master
                      \
                        E---G  test1
                                 \
                                  F---H---I---J test2 (HEAD)
```
and this is certainly unwanted. How could this be handled so that `F` does not reappear in `test2`. As of now, I always rebase with `-i` and make sure that I don't see any "foreign" commit appear, but I feel there should be a better way.
Thanks for the help!!

**Comment by derrickstolee** [comment] 2020-12-17 03:13
I'm glad you're resolved, @lupalby. If you remove commits from `test1` and don't want them carried over in `test2`, then you'll need to use the commit ID in the second position of the `--onto` command. Naturally, `git rebase --onto test1 test1 test2` is the same as `git rebase test1`.

Alternatively, you could just do `git rebase -i test1` and then delete the lines for the commits you want to drop (or change the `pick` command to `drop`).

**Comment by eamodio** [comment] 2020-12-17 07:05
Can you please verify this fix in tomorrow's insiders edition?

You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). Be sure to disable/uninstall the stable version of GitLens first.

**Comment by lupalby** [comment] 2020-12-18 20:37
@eamodio I downgraded to the old git version with the bug and repeated the steps. I can confirm that the rebase UI does not show the "onto" row anymore when before it was wrong, and it does show it when it shows something meaningful.

**Comment by eamodio** [comment] 2020-12-18 20:49
Awesome! Thank you!
