### ISSUE TITLE
Unable to find git

### ISSUE THREAD

**Issue by sascha-andres** [eamodio/vscode-gitlens#16] opened 2016-11-17 04:30 UTC
Hello,

GitLens can not find my installed git. The complete error message is:

GitLens: Unable to find Git. Please make sure Git is installed. Also ensure that Git is either in the PATH, or that 'gitlens.advanced.git' is pointed to its installed location.

Git is located in /usr/local/bin/git and the containing directory is in the path. Specifying a path breaks my setup because the path is not the same on Windows ( settings are synced ). Running Git on the commandline works, too.

How can I find out where GitLens looks for git or help you to help me?

Kind regards,
Sascha

**Comment by eamodio** [comment] 2016-11-17 06:08
@sascha-andres There is a bug in `1.0.1` where it can incorrectly report that it can't find Git, when in fact the issue is that it couldn't find a git repository. Is the folder you are opening a git repository (or is a folder inside a git repository)?

I'm going to publish `1.0.2` shortly that fixes the incorrect message -- and won't even show a message when it can't find a git repo (since that could be quite common and not a problem)

**Comment by eamodio** [comment] 2016-11-18 19:32
Since I'm fairly confident this was fixed in `1.0.2` I'm going to close this. Please re-open if not.

**Closed by eamodio** 2016-11-18 19:32 UTC
