### ISSUE TITLE
Line blame annotations re-enabled every time VSCode starts, gitlens.currentLine.enabled not working

### ISSUE THREAD

**Issue by Yzrsah** [eamodio/vscode-gitlens#668] opened 2019-02-26 15:53 UTC
The `"gitlens.currentLine.enabled": false,` setting does not work.

The line blame annotations are re-enabled at every startup of VSCode, and I have to run the `GitLens: Toggle line blame annotations` command each time.

version: VSCode Insiders 1.32

**Comment by eamodio** [comment] 2019-02-26 17:26
I can't reproduce this. Can you provide more details? Do you possibly have the setting on at the workspace or folder level that is overriding the user level setting? If not, can you please enable output channel logging by setting `"gitlens.outputLevel": "debug"` in your `settings.json`. This will enable logging to the *GitLens* channel in the *Output* pane. Once enabled, please reproduce the issue (if possible) and attach the log lines from the *GitLens* channel.

**Comment by Yzrsah** [comment] 2019-02-27 05:20
This only started happening in the past week.

Startup:
```
[2019-02-27 05:15:20:211] [/Users/foo/Source] git rev-parse --show-toplevel • 28 ms 
[2019-02-27 05:15:28:359] [/Users/foo/Source] git remote -v • 275 ms 
[2019-02-27 05:15:28:882] [/Users/foo/Library/Application Support/Code - Insiders/User] git rev-parse --show-toplevel • 42 ms 
[2019-02-27 05:15:28:897] [] git ls-files -- /Users/foo/Library/Application Support/Code - Insiders/User/settings.json • 13 ms 
```

Then opening a file:
```
[2019-02-27 05:15:51:568] [/Users/foo/Source] git ls-files -- bar.com/Site/next.config.js • 65 ms 
[2019-02-27 05:15:51:762] [/Users/foo/Source/bar.com/Site] git rev-parse --show-toplevel • 191 ms 
[2019-02-27 05:15:51:800] [/Users/foo/Source/bar.com/Site] git ls-files -- /Users/foo/Source/bar.com/Site/next.config.js • 34 ms 
[2019-02-27 05:15:51:856] [/Users/foo/Source/bar.com/Site] git remote -v • 54 ms 
[2019-02-27 05:15:51:901] [/Users/foo/Source/bar.com/Site] git blame --root --incremental -- next.config.js • 43 ms 
[2019-02-27 05:15:51:933] [/Users/foo/Source/bar.com/Site] git config --get-regex user.(name|email) • 31 ms 
[2019-02-27 05:15:52:404] [/Users/foo/Source/bar.com/Site] git check-mailmap Bar Baz <bar@bar.com> • 469 ms 
```

**Comment by Yzrsah** [comment] 2019-02-27 05:22
This only started happening in the past week.

Startup:
```
[2019-02-27 05:15:20:211] [/Users/foo/src] git rev-parse --show-toplevel • 28 ms 
[2019-02-27 05:15:28:359] [/Users/foo/src] git remote -v • 275 ms 
[2019-02-27 05:15:28:882] [/Users/foo/Library/Application Support/Code - Insiders/User] git rev-parse --show-toplevel • 42 ms 
[2019-02-27 05:15:28:897] [] git ls-files -- /Users/foo/Library/Application Support/Code - Insiders/User/settings.json • 13 ms 
```

Then opening a file:
```
[2019-02-27 05:15:51:568] [/Users/foo/src] git ls-files -- bar.com/site/next.config.js • 65 ms 
[2019-02-27 05:15:51:762] [/Users/foo/src/bar.com/site] git rev-parse --show-toplevel • 191 ms 
[2019-02-27 05:15:51:800] [/Users/foo/src/bar.com/site] git ls-files -- /Users/foo/src/bar.com/site/next.config.js • 34 ms 
[2019-02-27 05:15:51:856] [/Users/foo/src/bar.com/site] git remote -v • 54 ms 
[2019-02-27 05:15:51:901] [/Users/foo/src/bar.com/site] git blame --root --incremental -- next.config.js • 43 ms 
[2019-02-27 05:15:51:933] [/Users/foo/src/bar.com/site] git config --get-regex user.(name|email) • 31 ms 
[2019-02-27 05:15:52:404] [/Users/foo/src/bar.com/site] git check-mailmap Bar Baz <bar@bar.com> • 469 ms 
```

**Comment by Yzrsah** [comment] 2019-02-27 05:37
I found a way to make this reproducible:

It only happens when opening a workspace with a git repo that does not have commits, but contains nested git repos:
```
mkdir SuperProject
cd SuperProject
git init
cp ~/SomeGitProject .
cp ~/AnotherGitProject .
```

When opening the workspace for SuperProject,
It makes this log: ('GitService.getRepository returned undefined')
```
[2019-02-27 05:33:25:728] [1] GitService.initialize
[2019-02-27 05:33:26:341] Git found: 2.17.2 (Apple Git-113) @ /usr/bin/git • 30 ms
[2019-02-27 05:33:26:341] [1] GitService.initialize completed • 612 ms
[2019-02-27 05:33:26:349] Starting repository search in 1 folders
[2019-02-27 05:33:26:349] Searching for repositories (depth=1) in '/Users/foo/src/Bar' ...
[2019-02-27 05:33:26:363] [2] GitUri.fromUri — e=Uri(file:///Users/foo/Library/Application Support/Code - Insiders/User/settings.json)
[2019-02-27 05:33:26:363] [3] GitService.getRepoPath — e=Uri(file:///Users/foo/Library/Application Support/Code - Insiders/User/settings.json)
[2019-02-27 05:33:26:363] [4] GitService.getRepository — e=Uri(file:///Users/foo/Library/Application Support/Code - Insiders/User/settings.json), t={"skipCacheUpdate":true}
[2019-02-27 05:33:26:373] GitLens(v9.5.1) activated • 658 ms
[2019-02-27 05:33:26:423] [/Users/foo/src/Bar] git rev-parse --show-toplevel • 74 ms 
[2019-02-27 05:33:26:424] Repository found in '/Users/foo/src/Bar'
[2019-02-27 05:33:26:572] Completed repository search (depth=1) in '/Users/foo/src/Bar' • 223 ms
[2019-02-27 05:33:29:397] [/Users/foo/src/Bar] git remote -v • 30 ms 
[2019-02-27 05:33:33:679] [4] GitService.getRepository returned undefined • 7315 ms
[2019-02-27 05:33:33:694] [/Users/foo/Library/Application Support/Code - Insiders/User] git rev-parse --show-toplevel • 14 ms 
[2019-02-27 05:33:33:695] [3] GitService.getRepoPath returned undefined • 7331 ms
[2019-02-27 05:33:33:695] [2] GitUri.fromUri returned GitUri(file:///Users/foo/Library/Application Support/Code - Insiders/User/settings.json) • 7331 ms
[2019-02-27 05:33:33:695] [5] GitService.getRepository — e=GitUri(file:///Users/foo/Library/Application Support/Code - Insiders/User/settings.json)
[2019-02-27 05:33:33:695] [5] GitService.getRepository returned undefined • 0 ms
[2019-02-27 05:33:33:707] [] git ls-files -- /Users/foo/Library/Application Support/Code - Insiders/User/settings.json • 11 ms 
[2019-02-27 05:33:33:707] [6] GitService.isTracked returned false • 11 ms — e=GitUri(file:///Users/foo/Library/Application Support/Code - Insiders/User/settings.json)
```

**Comment by Yzrsah** [comment] 2019-02-27 05:55
I found a way to make this reproducible:

It only happens when opening a workspace with a git repo that does not have commits, but contains nested git repos:
```
mkdir SuperProject
cd SuperProject
git init
mv ~/SomeGitProject .
mv ~/AnotherGitProject .
```

When opening the workspace for SuperProject,
It makes this log: ('GitService.getRepository returned undefined')
```
[2019-02-27 05:33:25:728] [1] GitService.initialize
[2019-02-27 05:33:26:341] Git found: 2.17.2 (Apple Git-113) @ /usr/bin/git • 30 ms
[2019-02-27 05:33:26:341] [1] GitService.initialize completed • 612 ms
[2019-02-27 05:33:26:349] Starting repository search in 1 folders
[2019-02-27 05:33:26:349] Searching for repositories (depth=1) in '/Users/foo/src/Bar' ...
[2019-02-27 05:33:26:363] [2] GitUri.fromUri — e=Uri(file:///Users/foo/Library/Application Support/Code - Insiders/User/settings.json)
[2019-02-27 05:33:26:363] [3] GitService.getRepoPath — e=Uri(file:///Users/foo/Library/Application Support/Code - Insiders/User/settings.json)
[2019-02-27 05:33:26:363] [4] GitService.getRepository — e=Uri(file:///Users/foo/Library/Application Support/Code - Insiders/User/settings.json), t={"skipCacheUpdate":true}
[2019-02-27 05:33:26:373] GitLens(v9.5.1) activated • 658 ms
[2019-02-27 05:33:26:423] [/Users/foo/src/Bar] git rev-parse --show-toplevel • 74 ms 
[2019-02-27 05:33:26:424] Repository found in '/Users/foo/src/Bar'
[2019-02-27 05:33:26:572] Completed repository search (depth=1) in '/Users/foo/src/Bar' • 223 ms
[2019-02-27 05:33:29:397] [/Users/foo/src/Bar] git remote -v • 30 ms 
[2019-02-27 05:33:33:679] [4] GitService.getRepository returned undefined • 7315 ms
[2019-02-27 05:33:33:694] [/Users/foo/Library/Application Support/Code - Insiders/User] git rev-parse --show-toplevel • 14 ms 
[2019-02-27 05:33:33:695] [3] GitService.getRepoPath returned undefined • 7331 ms
[2019-02-27 05:33:33:695] [2] GitUri.fromUri returned GitUri(file:///Users/foo/Library/Application Support/Code - Insiders/User/settings.json) • 7331 ms
[2019-02-27 05:33:33:695] [5] GitService.getRepository — e=GitUri(file:///Users/foo/Library/Application Support/Code - Insiders/User/settings.json)
[2019-02-27 05:33:33:695] [5] GitService.getRepository returned undefined • 0 ms
[2019-02-27 05:33:33:707] [] git ls-files -- /Users/foo/Library/Application Support/Code - Insiders/User/settings.json • 11 ms 
[2019-02-27 05:33:33:707] [6] GitService.isTracked returned false • 11 ms — e=GitUri(file:///Users/foo/Library/Application Support/Code - Insiders/User/settings.json)
```

When I open a different workspace with a regular project that has git commits, the bug does not happen and line blame annotations do not display.

**Comment by Yzrsah** [comment] 2019-03-29 20:37
@eamodio Continuing to test this, the line blame annotations are enabled when opening files in the Monorepos or yarn workspace repos. It's 100% consistent - Open files in Yarn workspace, Git line blames are enabled.

**Comment by eamodio** [comment] 2019-04-02 04:56
@Yzrsah Unfortunately I can't reproduce this. I've tried the "super" repo example you provided and I don't see the current line blame show up with it off. Also from code inspection, I can't see how it could happen either.

Can you send a video or something that shows the problem? And is there any public repo(s) that I can clone to see it? Alternatively, I can add some more logging and provide a new build and see what we see there.

**Comment by eamodio** [comment] 2019-04-17 07:33
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!

**Closed by eamodio** 2019-04-17 07:33 UTC
Labels: status: needs more info, type: potential bug

**Comment by Yzrsah** [comment] 2019-04-17 07:52
@eamodio Sorry I didn't respond. I feel this is my responsibility to rebuild the VSCode setup and test with all the repos in multiple configurations to figure it out and make a perfect reproduction so that I can give you better information. I didn't have enough free time to finish this yet, I am working on it though. Any extra logging would be very helpful for this process.

**Comment by eamodio** [comment] 2019-04-17 07:58
@Yzrsah it is still reproducible with 9.6 (or 9.6.1 which I just released)?

**Comment by eamodio** [comment] 2019-04-17 07:59
Also if possible a video/gif showing the issue might help a great deal.

**Comment by Yzrsah** [comment] 2019-04-17 08:07
@eamodio Wow, the problem is no longer occurring with the new version. Thank you
