### ISSUE TITLE
History of binary file not shown in view

### ISSUE THREAD

**Issue by bardware** [eamodio/vscode-gitlens#672] opened 2019-02-27 14:26 UTC
- GitLens Version: 9.5.1
  
- VSCode Version: 1.31.1
- OS Version: Win 10 64 bit German

Steps to Reproduce:

1.

Right click on a jar file in the working directory. In the popup menu select `Show file history in View`
The file (name) is shown in the view, its history is missing
![grafik](https://user-images.githubusercontent.com/802702/53497096-b870ef00-3aa3-11e9-9dfb-fb7e66698b8d.png)

In the bottom right a popup appears saying the file seems to be a binary file and cannot be opened
![grafik](https://user-images.githubusercontent.com/802702/53497162-e0f8e900-3aa3-11e9-8261-f5ca9ea74ec6.png)

I expect the view to show the commit history of that files - whether it can be opened or not.

**Comment by bardware** [comment] 2019-10-08 13:54
Just wanted to file this as a bug for the very same reason I already did. I have some jar files in my repo  without the version number in the file name and wanted to see the commit comment to find out when I commited last.

**Comment by eamodio** [comment] 2019-10-09 06:41
Can you please enable output channel logging by setting `"gitlens.outputLevel": "debug"` in your settings. This will enable logging to the *GitLens* channel in the *Output* pane. Once enabled, please reproduce the issue and attach the log from the *GitLens* channel. Thanks!

**Comment by eamodio** [comment] 2019-10-25 06:17
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!

**Closed by eamodio** 2019-10-25 06:17 UTC
Labels: status: needs more info, type: potential bug
