### ISSUE TITLE
Text select issue on vsCode 1.43.0-insider

### ISSUE THREAD

**Issue by FDiskas** [eamodio/vscode-gitlens#956] opened 2020-02-11 16:30 UTC
- GitLens Version:
```
Name: GitLens — Git supercharged
Id: eamodio.gitlens
Description: Supercharge the Git capabilities built into Visual Studio Code — Visualize code authorship at a glance via Git blame annotations and code lens, seamlessly navigate and explore Git repositories, gain valuable insights via powerful comparison commands, and so much more
Version: 10.2.1
Publisher: Eric Amodio
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens
```
- VSCode Version:
```
Version: 1.43.0-insider
Commit: beaf391bc53136912e4f0bbdfb7844ad954247db
Date: 2020-02-07T05:30:08.850Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
```
- OS Version:
```
OS: Darwin x64 19.3.0
```
Steps to Reproduce:

1. [Screen Recording 2020-02-11 at 18.24.42.mov.zip](https://github.com/eamodio/vscode-gitlens/files/4186816/Screen.Recording.2020-02-11.at.18.24.42.mov.zip)

**Comment by eamodio** [comment] 2020-02-11 19:30
This is caused by Electron 7 in vscode insiders: https://github.com/microsoft/vscode/issues/88873. Unfortunately I don't know of anything GitLens can do, but VS Code is working on a fix.

**Comment by emeidell** [comment] 2020-02-12 20:58
Man that sucks. I hate this bug! haha super annoying trying to find the right place to click.

**Comment by eamodio** [comment] 2020-02-12 22:21
@emeidell Me too -- there is a temporary workaround here: https://github.com/microsoft/vscode/issues/88873#issuecomment-576456968

**Comment by eamodio** [comment] 2020-03-06 07:55
This has been fixed in VS Code

**Closed by eamodio** 2020-03-06 07:55 UTC
Labels: blocked: vscode, status: blocked
