### ISSUE TITLE
Installs to Azure Data Studio, Doesn't Work

### ISSUE THREAD

**Issue by ScaryDBA** [eamodio/vscode-gitlens#657] opened 2019-02-15 15:54 UTC
- GitLens Version:
  
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Install to Azure Data Studio through .vsix
2. Try using CTL-SHIFT-P GitLens: Open Settings
command 'gitlens.showSettingsPage' not found

**Comment by eamodio** [comment] 2019-02-18 21:21
GitLens doesn't currently support Azure Data Studio. This is duplicate of #573.

**Closed by eamodio** 2019-02-18 21:21 UTC

**Comment by speed-oss** [comment] 2019-02-21 23:56
@ScaryDBA if you think this feature should be built, consider adding a reward to this issue using [speedoss.com](speedoss.com)  :)
