### ISSUE TITLE
Adjust editor.rules when in Git Blame Mode

### ISSUE THREAD

**Issue by MindOver** [eamodio/vscode-gitlens#223] opened 2017-12-05 17:23 UTC
The editor rule is not adjusting it's position when using Git Blame panel.

- GitLens Version:
- VSCode Version: 1.18.1 x64
- OS Version: Windows 10.0.15063 Build 15063

Steps to Reproduce:

1. Set editor.rules
2. Toggle File Blame Annotations
3. Expected: Editor rules should shift to a new position to maintain it's initial value

![visual studio code git blame disabled](https://user-images.githubusercontent.com/4644006/33620546-09d5ef42-d9e0-11e7-9b59-1415324578ac.png)
![visual studio code git blame enabled](https://user-images.githubusercontent.com/4644006/33620554-10bac0a8-d9e0-11e7-95fe-22303c7df007.png)

**Comment by eamodio** [comment] 2017-12-12 16:43
Duplicate of https://github.com/eamodio/vscode-gitlens/issues/210

**Closed by eamodio** 2017-12-12 16:43 UTC
