### ISSUE TITLE
cannot open file

### ISSUE THREAD

**Issue by ulli-b** [eamodio/vscode-gitlens#940] opened 2020-01-27 17:38 UTC
Issue Type: <b>Bug</b>

File history, Line History:
File is workspace-path + full filepath:

cannot open file:///d%3A/htdocs/TestTs/d%3A/htdocs/TestTs/d%3A/htdocs/TestTs/d%3A/htdocs/TestTs/projects/admin/src/app/app.module.ts. Detail: Unable to read file 'd:\htdocs\TestTs\d:\htdocs\TestTs\d:\htdocs\TestTs\d:\htdocs\TestTs\projects\admin\src\app\app.module.ts' (Error: Unable to resolve non-existing file 'd:\htdocs\TestTs\d:\htdocs\TestTs\d:\htdocs\TestTs\d:\htdocs\TestTs\projects\admin\src\app\app.module.ts')

Extension version: 10.2.0
VS Code version: Code - Insiders 1.42.0-insider (5dcf2c96b6562b3aa879dbb455de4b58e17cb804, 2020-01-27T11:23:59.719Z)
OS version: Windows_NT x64 10.0.18363

**Comment by PowerMogli** [comment] 2020-01-29 11:34
I have the same problem.

My output of gitlens log looks like this:

```
[2020-01-29 11:31:28:980] [5f] GitService.getBlameForFile
[2020-01-29 11:31:28:982] [60] GitService.isTracked returned true • 0 ms
[2020-01-29 11:31:29:577] [C:/_source/work/Mobile/alberta.mobile] git status --porcelain=v2 --find-renames -- c:/_source/work/Mobile/alberta.mobile/src/app/shared/services/sync/order-sync.service.ts • 923 ms 
[2020-01-29 11:31:29:577] [52] GitService.getStatusForFile completed • 924 ms
[2020-01-29 11:31:29:578] [62] GitService.getLogForFile
[2020-01-29 11:31:29:600] [62] GitService.getLogForFile — failed • 22 ms
Error: cannot open file:///c%3A/_source/work/Mobile/alberta.mobile/c%3A/_source/work/Mobile/alberta.mobile/c%3A/_source/work/Mobile/alberta.mobile/src/app/shared/services/sync/order-sync.service.ts. Detail: Unable to read file 'c:\_source\work\Mobile\alberta.mobile\c:\_source\work\Mobile\alberta.mobile\c:\_source\work\Mobile\alberta.mobile\src\app\shared\services\sync\order-sync.service.ts' (Error: Unable to resolve non-existing file 'c:\_source\work\Mobile\alberta.mobile\c:\_source\work\Mobile\alberta.mobile\c:\_source\work\Mobile\alberta.mobile\src\app\shared\services\sync\order-sync.service.ts')
[2020-01-29 11:31:30:244] [C:/_source/work/Mobile/alberta.mobile] git blame --root --incremental -- src/app/shared/services/sync/order-sync.service.ts • 1262 ms 
```

**Comment by tonoslav** [comment] 2020-01-31 12:49
Happy that this is not only my problem but anybody got some solution for this or workaround?
I've change nothing and keep getting this error.

Extension reinstall doesn't help
git version 2.25.0.windows.1 (latest)
Version: 1.42.0-insider (system setup)
Commit: 9e8c4c247a779cdd1f4f53db963bc6124a28ac2f
Date: 2020-01-30T05:29:29.151Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT ia32 10.0.18363

GitLens output is empty

**Comment by PowerMogli** [comment] 2020-01-31 12:59
Install Git for Windows 2.24.0

**Comment by tonoslav** [comment] 2020-01-31 13:09
@PowerMogli  so it is Git for Windows error? Or GitLens is not ready for 2.25 ?

**Comment by PowerMogli** [comment] 2020-01-31 13:34
> @PowerMogli so it is Git for Windows error? Or GitLens is not ready for 2.25 ?

As far as I know Gitlens is working on a solution to fix this problem. It looks like Git for Windows changed some internal git details and so Gitlens is unable to handle it correctly

**Comment by d1vanloon** [comment] 2020-02-03 16:45
Possible duplicate of #932

**Comment by eamodio** [comment] 2020-02-10 20:40
Duplicate of #932

**Closed by eamodio** 2020-02-10 20:40 UTC
