### ISSUE TITLE
False Tree Compare

### ISSUE THREAD

**Issue by bm-stschneider** [eamodio/vscode-gitlens#339] opened 2018-04-10 14:55 UTC
Issue Type: <b>Bug</b>

Comparing working tree to master results in too many changed files compared with the pull request from the same branch to the master, that doesn't seem correct.

Extension version: 8.2.0
VS Code version: Code - Insiders 1.23.0-insider (609c4ba1e7abc39952ef5fb7f3a22c0be0349efe, 2018-04-10T05:10:23.305Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_766139|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by eamodio** [comment] 2018-04-10 15:36
OK, going to close this as a duplicate of #330. I will be working on how to solve this.

**Closed** 2018-04-10 15:36 UTC
Labels: needs more info
