### ISSUE TITLE
GitLens stop working

### ISSUE THREAD

**Issue by SerhiiBilyk** [eamodio/vscode-gitlens#525] opened 2018-10-12 05:11 UTC
I have update VS Code to 1.27.2 and  GitLens stop to work.
WIndows 10 x64,
Node:8.9.3

**Comment by amarinov** [comment] 2018-10-12 06:36
Same with VS Code 1.28.1 on MacOS X

**Comment by PerfectionCSGO** [comment] 2018-10-12 11:53
GitLens isn't working on 1.28.1 x64 Windows 10

**Comment by eamodio** [comment] 2018-10-12 17:41
Can you please enable output channel logging by setting `"gitlens.outputLevel": "debug"` in your `settings.json`. This will enable logging to the *GitLens* channel in the *Output* pane. Once enabled, please reproduce the issue (if possible) and attach the log lines from the *GitLens* channel.

**Comment by ekrapfl** [comment] 2018-10-12 18:32
Turning that on does not result in any ouptut.  In fact, I can even try running the command to show the welcome page, and I still get no output.  Just the following error message on screen:
![image](https://user-images.githubusercontent.com/5939413/46887436-37ca9280-ce23-11e8-9e1d-d953ae0f72c0.png)

**Comment by eamodio** [comment] 2018-10-12 18:48
Hrm, can you try uninstalling GitLens, restarting vscode twice (make sure there are no running instances), and then reinstall GitLens?

If that still doesn't help, can you look in your extensions folder (`~/.vscode/extensions`) and see if there is more than 1 GitLens folder?

**Comment by marquezw** [comment] 2018-10-12 19:06
Hi. I just followed your latest instructions and it's still not working. 
And in ~/.vscode/extensions I have only one folder of it. eamodio.gitlens-8.5.6.

**Comment by marquezw** [comment] 2018-10-12 19:19
Ok, I fixed the issue by reinstalling the **Command Line Tools**. 

xcode-select --install

This is on Mac with macOS Mojave.

**Comment by eamodio** [comment] 2018-10-12 20:03
@marquezw before you installed the tools, when GitLens was failing -- was there any output in the GitLens output channel? I really don't see how GitLens could be failing without logging something.

**Comment by luguoshaonian** [comment] 2018-10-13 08:29
@eamodio working well as you told

**Comment by SerhiiBilyk** [comment] 2018-10-15 05:17
I have uninstalled GitLens and after two reloads its began to work

**Comment by jozefizso** [comment] 2018-10-17 10:10
Gitlens stopped working for me. I'm currently running VS Code 1.28.1 (user setup) on Windows 10 x64.

I tried to uninstall Gitlens, restart VS Code and install it again. It did not help.

When I uninstalled Gitlens, closed VS Code and removed the `.vscode\extensions\eamodio.gitlens-8.5.6` folder, I was able to install Gitlens again.

I compared contents of the old and new folders and only difference is missing `out\extension.js` file in the old folder.

**Comment by zfeher** [comment] 2018-10-17 13:59
I had the same problem on Windows 10,  VSCode 1.28.1. Tried to uninstall/reinstall many times didn't help. Then after an uninstall I removed the Gitlens related folders from `.vscode/extensions` then installed Gitlens and it started to work again \o/

**Comment by zfeher** [comment] 2018-10-17 17:12
Now that you mentioned AVs, Eset complained about something and maybe quarantined it as well recently I think that was the `extension.js` file yes.

**Comment by SerhiiBilyk** [comment] 2018-10-17 19:13
@eamodio restarting twice help me

**Comment by ppatalong** [comment] 2018-10-18 10:28
had the same issue on windows 10. Reinstall extension helped.

**Comment by PerfectionCSGO** [comment] 2018-10-18 12:29
I repeatedly disabled, enabled, uninstalled, installed and checked ESET for any intervention but to no avail. Gitlens is not working in VS Code in 1.28

**Comment by BrendanBeltzNIH** [comment] 2018-10-18 12:55
Myself, and my colleague both lost gitlens a week ago. Manually deleting the folder after uninstall and then reinstalling seems to have worked for us as well.

**Comment by thanhduy2b** [comment] 2018-10-18 14:39
I had same problem in Windows 10 with VS Code 1.28.2. Tried uninstall/reinstall many times in only VS Code didn't help. Need remove the GitLens related folder and then it started to work again.
Depending on your platform, the location is in the following folder:
- Windows %USERPROFILE%\.vscode\extensions
- macOS ~/.vscode/extensions
- Linux ~/.vscode/extensions

**Comment by eamodio** [comment] 2018-11-11 06:55
I'm closing this -- as the main issue seems to be extension installation issue, which I cannot control (vscode handles extension installation).

**Closed by eamodio** 2018-11-11 06:55 UTC
Labels: needs more info

**Comment by viggy28** [comment] 2019-08-01 17:58
I hope this helps someone. Spent a week trying to understand why my gitlens was not working. 

Opening visual code directly from the terminal using **code** command works.
https://code.visualstudio.com/docs/setup/mac

**Comment by eamodio** [comment] 2019-08-01 18:00
@viggy28 are you on Catalina?

**Comment by viggy28** [comment] 2019-08-01 18:04
Actually, I used to live near LA, so I thought you were asking about Catalina island. 

Googled it. Well, I am in Mojave 10.1.4.3. VScode 1.36.1  GitLens 9.9.2. (I tried earlier different versions of GitLens too)

**Comment by eamodio** [comment] 2019-08-01 18:06
Hehe... hrm, I've only seen issues with Catalina.

Can you send me logs for when it fails? You can enable output channel logging by setting `"gitlens.outputLevel": "debug"` in your `settings.json`. This will enable logging to the *GitLens* channel in the *Output* pane. Once enabled, please reproduce the issue (if possible) and attach the log lines from the *GitLens* channel.
