### ISSUE TITLE
The gitlens style is polluted by my theme style.

### ISSUE THREAD

**Issue by lijunle** [eamodio/vscode-gitlens#110] opened 2017-07-05 07:20 UTC
# Info

- GitLens Version: 4.3.1
- VSCode Version: 1.13.1
- OS Version: Windows Server 2012

# Steps to Reproduce:

The gitlens history line inherits the style from my left text style. See the green underline in the picture:

![image](https://user-images.githubusercontent.com/1296500/27853484-6219a2e8-6195-11e7-8850-d7ce1a8fe756.png)

**Comment by jens1o** [comment] 2017-07-05 11:58
caused by this: https://github.com/Microsoft/vscode/issues/22018 and https://github.com/Microsoft/vscode/issues/28079

**Comment by eamodio** [comment] 2017-08-21 15:13
Closing this as once the vscode issue is fixed GitLens will work properly.

**Closed by eamodio** 2017-08-21 15:13 UTC
Labels: vscode issue
