### ISSUE TITLE
Cursor on Uncommitted message 

### ISSUE THREAD

**Issue by pankajpatel** [eamodio/vscode-gitlens#42] opened 2017-03-03 13:52 UTC
The cursor position should not be around the uncommitted info on empty line
![cursor](https://cloud.githubusercontent.com/assets/251937/23553395/de0e3520-0020-11e7-8284-cada52c2c91e.png)

**Comment by svipben** [comment] 2017-03-03 14:59
I can confirm this, OS: Linux Ubuntu 16.04, VS Code: 1.10, Git: 2.11.0

**Comment by eamodio** [comment] 2017-03-03 15:17
@pankajpatel as @svipben mentioned this should be fixed in a later version of GitLens. Please let me know if you are still seeing issues on the latest version (currently 2.9.0).

**Comment by pankajpatel** [comment] 2017-03-03 15:49
Sorry for less info;

OS: macOS Sierra v10.12.3 (16D32)
VSCode: Version 1.10.1 (1.10.1)
GitLens: v2.9.0

Issue is still visible.
![screen shot 2017-03-03 at 4 48 20 pm](https://cloud.githubusercontent.com/assets/251937/23557725/41057ce6-0031-11e7-9fcc-af8f6c569c05.png)

**Comment by svipben** [comment] 2017-03-03 16:10
Right now I can confirm it too.

![Image](https://i.gyazo.com/a80c20bfcfe27ffd205481e388166374.png)

**Comment by eamodio** [comment] 2017-03-03 17:13
@pankajpatel @svipben How do you get into that state? What are the steps?

**Comment by eamodio** [comment] 2017-03-03 17:49
@pankajpatel @svipben fyi, I pushed an update with a set of fixes, some of which might address this -- please let me know if the issue still persists. Thanks!

**Comment by svipben** [comment] 2017-03-03 18:49
I think I know why it happens, try to use tab or space in empty line, it will triggers `Uncommited change`.

**Comment by pankajpatel** [comment] 2017-03-03 21:57
@svipben correct. And one thing that I noticed is that if the if the setting for rendering whitespace is ste to all i.e. `"editor.renderWhitespace": "all"` then the issue doesn't come up.

**Comment by eamodio** [comment] 2017-03-03 23:58
@pankajpatel ah - that explains why I don't see it. Thanks for the information!

**Comment by eamodio** [comment] 2017-03-05 16:46
@pankajpatel @svipben Thanks for all the information. This appears to be a vscode bug (as nothing I could think of had any effect at stopping this behavior). I've opened the following issues to track this: [vscode #22018](https://github.com/Microsoft/vscode/issues/22018) & [vscode #22017](https://github.com/Microsoft/vscode/issues/22017)

**Comment by svipben** [comment] 2017-03-05 17:12
@eamodio Thank you!
Off topic: can you show how Darwin OS looks like and from where I can download it? I found http://www.puredarwin.org website and I saw screenshots, so it looks like this? Seems old & ugly ;D

**Comment by eamodio** [comment] 2017-03-05 18:18
np. Darwin OS is what macOS calls itself internally. I'm running macOS Sierra.

**Comment by eamodio** [comment] 2017-03-09 07:23
Since vscode fixed this issue I'm closing it

**Closed by eamodio** 2017-03-09 07:23 UTC
Labels: vscode issue

**Comment by pankajpatel** [comment] 2017-03-09 08:03
I also noticed the smooth working after updating the VSCode. Thankyou!

**Comment by pankajpatel** [comment] 2017-03-16 09:20
This issue is reappearing again. can we reopen it?

**Comment by eamodio** [comment] 2017-03-16 13:01
@pankajpatel you are still running the insiders build of vscode? If so is it the same scenario?

**Comment by pankajpatel** [comment] 2017-03-16 16:46
I am sunning the stable version and the scenario was similar. 
VSCOde: Version 1.10.2 (1.10.2)
GitLens: 2.12.2

<img width="439" alt="error" src="https://cloud.githubusercontent.com/assets/251937/24007933/6229c460-0a70-11e7-8e38-9d27ef8fcb95.png">

**Comment by svipben** [comment] 2017-03-16 16:48
@pankajpatel it wasn't fixed on stable, it was fixed in insiders build as @eamodio said. I didn't tested, just waiting for stable release :smile:

**Comment by eamodio** [comment] 2017-03-16 18:01
@pankajpatel as @svipben mentioned the vscode fix will be in the next version (1.11) or the current insiders build.
