### ISSUE TITLE
can't remove gitlens icon from acitivity bar

### ISSUE THREAD

**Issue by zhaomiing** [eamodio/vscode-gitlens#474] opened 2018-08-11 07:49 UTC
Issue Type: <b>Bug</b>

1 remove gitlens icon from activity bar
2 restart vscode
3 gitlens icon appears on the activity bar again
4 : (

Extension version: 8.5.4
VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.80GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by eamodio** [comment] 2018-08-16 05:17
Duplicate of #447

But until the vscode bug is fixed, if you want to remove the activity bar icon, you can turn off all of the explorers (or move them to a different activity)

**Closed by eamodio** 2018-08-16 05:17 UTC
