### ISSUE TITLE
Allow to use a different commant than blame

### ISSUE THREAD

**Issue by jyavenard** [eamodio/vscode-gitlens#554] opened 2018-11-22 09:04 UTC
While we can add arguments to the git blame command, you can't specify which blame command to use instead.

Like google's depot_tools has a hyper-blame method that works in an identical way to git blame but ignore specified commit.

It would be great if you could override the command to run, so that by default it uses say git hyper-blame instead.

**Comment by eamodio** [comment] 2018-12-03 13:59
Duplicate of #413

**Closed by eamodio** 2018-12-03 13:59 UTC
