### ISSUE TITLE
Extension disappeared

### ISSUE THREAD

**Issue by catexis** [eamodio/vscode-gitlens#516] opened 2018-09-30 08:12 UTC
- GitLens Version: 8.5.6
- VSCode Version: 1.27.2
- OS Version: Linux Mint 19 Cinnamon 3.8.9 (core 4.15.0.34-generic)

After new reload of OS extension GitLens disappeared ([screenshot](https://i.stack.imgur.com/a9fVQ.png))
I can't see any information in my source code, that provide this extension. Reinstallation this extension or vs code didn't apply any effect.

**Comment by wirowka** [comment] 2018-10-03 08:47
Same here, Windows 10 version 1709
VSCode Version: 1.27.2
GitLens Version: 8.5.6

**Comment by ihtiuh** [comment] 2018-10-05 09:47
Same here, but this only happened for one of my git repository, I test with a new git repository and it worked fine though:

OS Version: openSUSE Leap 42.3
VSCode Version: 1.27.2
GitLens Version: 8.5

@eyalcohen4 May be you can update the `settings.json` with `"gitlens.outputLevel": "verbose"` and reload the workspace and check the Output window of GitLens.

For me it gets stuck at "Repository found in ... ":

Git found: 2.13.6 @ /usr/bin/git in 88 ms
Starting repository search in 1 folders
Searching for repositories (depth=1) in '_workspace path_' ...
Running("_workspace path_"): git rev-parse --show-toplevel
GitLens(v8.5.6) activated in 223 ms
Completed("_workspace path_"): git rev-parse --show-toplevel Completed in 105 ms
Repository found in "_workspace path_"

**Comment by eamodio** [comment] 2018-10-08 03:09
Can all of you please enable output channel logging by setting `"gitlens.outputLevel": "debug"` in your `settings.json`. This will enable logging to the *GitLens* channel in the *Output* pane. Once enabled, please attempt to reproduce the issue (if possible) and attach the log lines from the *GitLens* channel.

**Comment by ihtiuh** [comment] 2018-10-08 08:42
With `"gitlens.outputLevel": "debug"`, for me the output is the same with as in the above comment.

**Comment by catexis** [comment] 2018-10-09 08:41
In my output console same information. And one more thing: i get this problem in different computers.
```
Git found: 2.17.1 @ /usr/bin/git in 91 ms
Starting repository search in 1 folders
Searching for repositories (depth=1) in '<workspace_path>' ...
Running(<workspace_path>): git rev-parse --show-toplevel
GitLens(v8.5.6) activated in 213 ms
Completed(<workspace_path>): git rev-parse --show-toplevel Completed in 42 ms
Repository found in '<workspace_path>'
```

**Comment by vadviktor** [comment] 2018-10-09 17:14
Is this related to #520 by any chance?

**Comment by catexis** [comment] 2018-10-10 05:31
There is no antivirus on my linux systems. But the symptoms are similar.

**Comment by vadviktor** [comment] 2018-10-10 08:47
@catexis, of course there is, https://www.clamav.net/ to name one. 😈 

I saw you are using LM, but wanted to remind this thread to rule out the AV vector.

**Comment by eamodio** [comment] 2018-10-11 16:15
@catexis interesting -- thanks for the extra info -- this gives me much more to go on.

**Comment by gitsoft** [comment] 2018-10-12 22:33
Windows 10 Pro, version 1803
VSCode Version: 1.28.1
GitLens Version: 8.5.6

**Comment by eamodio** [comment] 2018-10-13 07:34
@catexis when you repro the error -- if you turn on logging -- do you get any output in the GitLens output channel?

**Comment by gitsoft** [comment] 2018-10-18 09:37
I can confirm that the solution suggested by @michaelgeorgeattard works on windows. 
As described above, you must manually delete %userprofile%\.vscode\extensions\eamodio.gitlens-8.5.6 for the reinstall to make gitlens visible again.

**Comment by tnimni** [comment] 2018-11-04 15:56
@michaelgeorgeattard thanks man that works great
for mac users:
remove the extension
reload vscode
go to setting.json by pressing cmd+shift+p > open user settings
delete all entries regarding the extension
close vs code
open vscode
install the extension

**Comment by eamodio** [comment] 2018-11-11 06:55
I'm closing this -- as the main issue seems to be extension installation issue, which I cannot control (vscode handles extension installation).

**Closed by eamodio** 2018-11-11 06:55 UTC
Labels: needs more info
