### ISSUE TITLE
Don't show github auth notification on install?

### ISSUE THREAD

**Issue by Tyriar** [eamodio/vscode-gitlens#1352] opened 2021-01-28 16:08 UTC
Just a suggestion to avoid notification fatigue. I got this auth notification on all my machines when I installed gitlens, but we already show the more subtle (1) on the account icon when gitlens requests auth.

Additionally it shows up here:

![image](https://user-images.githubusercontent.com/2193314/106165274-c91eb980-613f-11eb-8ad5-b4247b93c3b2.png)

You could also show the auth notification when a user actually tries to use github functionality for the first time, when it's more relevant than extension install.

**Comment by eamodio** [comment] 2021-01-28 21:10
Duplicate of #1336, #1208

**Closed by eamodio** 2021-01-28 21:10 UTC
Labels: potential-bug, triage
