### ISSUE TITLE
git.openFile keyboard shortcut does not work from a GitLens Compare view

### ISSUE THREAD

**Issue by mliq** [eamodio/vscode-gitlens#395] opened 2018-06-04 18:19 UTC
- GitLens Version: 8.3.3
- VSCode Version: 1.23.1
- OS Version: 10.13.5

Steps to Reproduce:

1. "Compare File with Previous Revision"
2. Attempt to execute "git.openFile" with a keyboard shortcut - nothing happens.
3. Attempt to execute "git.openFile" via "Show All Commands" fuzzy search - nothing happens.
4. Attempt to execute "git.openFile" via the button in tab bar located to the left of "Open Working File" - success.

Other Notes / Things I have tried:
* I tried changing keyboard shortcut.
* Note that my keyboard shortcut does appear correctly in the tooltip for the button and in the fuzzy search - yet the button works and keyboard shortcut and fuzzy search does not.

Workflow I am seeking:
Frequently, I want to copy text from a previous revision. The only way I have discovered to do this is with "Open File". If there is a better way, I would be happy to know it. Regardless, it is strange that keyboard shortcuts/fuzzy find does not work, only the UI button. 

Thank you for your work and the amazing extension!

**Comment by eamodio** [comment] 2018-06-04 20:28
`git.openFile` isn't a command from GitLens, it is provided by the vscode git extension itself and since it doesn't know about GitLens files (uris) it doesn't work. I'm assuming you are trying to open the working version of that file? If so use the `gitlens.openWorkingFile` command instead.

Hope that helps.

**Comment by mliq** [comment] 2018-06-05 18:49
@eamodio thank you for your response.

Perhaps I am going about it the wrong way, but my aim is this: 

1. to browse one-by-one back in file revision history using "Compare to Previous" keyboard shortcut - which sometimes seems to work and other times does not go back more than one revision. 
2. Then, when I reach a certain revision, I want to be able to copy and paste the red highlighted code and paste it in current code.

Do you have any suggestion for how to do this most efficiently?

Thank you!

**Comment by mliq** [comment] 2018-06-05 18:50
I should note that Compare with Previous seems to always work using the button, but the keyboard shortcut only can go back one revision - why is this?

**Comment by mliq** [comment] 2018-06-06 15:37
@eamodio I think my issue is, in fact, primarily about keybindings, but it does not seem limited to `chorded` keymap. I have tried all keymaps, settling on `user-defined`, and several keyboard shortcuts do not work when going back in history. 

For example:  `Previous Change` and `Next Change` navigation.
* I have keyboard shortcuts assigned to these, but they do not work in file history views. 
* The buttons do work. 
* the Keyboard shortcuts do work in the regular diff viewer triggered from Source Control view.

Thanks for your help!

**Comment by eamodio** [comment] 2018-06-07 03:45
@mliq I just release GitLens 8.3.4 which should hopefully fix the keyboarding issues. Please re-open this issue if not. Thanks!

**Comment by mliq** [comment] 2018-06-08 14:27
Hi @eamodio - still not fixed. I don't think I am able to re-open the issue though, thank you.

**Comment by eamodio** [comment] 2018-06-08 17:06
Can you provide more details as to what isn't working? Because I can't reproduce any issues with the shortcut keys with the latest release.

**Comment by mliq** [comment] 2018-06-11 16:00
Here is an example:

1. Define keyboard shortcut for `workbench.action.compareEditor.nextChange`.
2. Execute "Compare File With Previous Revision" until multiple changes are present.
3. Attempt to execute `workbench.action.compareEditor.nextChange` via keyboard shortcut - nothing happens.
4. Attempt to execute `workbench.action.compareEditor.nextChange` via the UI button - it works.

UI Button in question:
![ui button](https://user-images.githubusercontent.com/7573605/41242973-a1ce6bac-6d66-11e8-99c0-981359c934e2.png)

**Comment by eamodio** [comment] 2018-06-11 17:55
Hrm, I cannot reproduce this. What version of vscode are you using? I've tried 1.24 and 1.25-insiders. I am on Windows though (and don't have access to a Mac currently).

**Comment by mliq** [comment] 2018-06-14 18:53
I am on 1.24.1 and also had this on 1.23 and 1.24.0. Perhaps it is a Mac issue then...

**Comment by eamodio** [comment] 2018-07-15 04:54
@mliq Is this still an issue? If so, what are you using to setup the keybinding?

Here is mine -- and it works fine for me on Windows
```json
    {
        "key": "alt+n",
        "command": "workbench.action.compareEditor.nextChange",
        "when": "editorTextFocus && isInDiffEditor"
    },
```

**Comment by mliq** [comment] 2018-08-25 00:32
@eamodio Yes, still an issue. I copied your keybinding setup above and no improvement.

**Comment by eamodio** [comment] 2018-12-03 14:06
@mliq Can you try again with GitLens 9?

**Comment by eamodio** [comment] 2018-12-27 21:09
I'm going to close this as I can't reproduce it, nor do I have access to a Mac at this point. And also the commands in question are built-in vscode commands, so if there is some underlying issue it is likely to be with vscode itself. So I would recommend filing an issue against that repository. Sorry.

**Closed by eamodio** 2018-12-27 21:09 UTC
Labels: bug, needs more info
