### ISSUE TITLE
interactive rebase broken & cannot disable

### ISSUE THREAD

**Issue by BlackthornYugen** [eamodio/vscode-gitlens#1395] opened 2021-02-23 18:29 UTC
- GitLens Version: `v11.2.1`
- Git Version: Run `git version 2.17.1`
- VSCode Version: Run `1.53.2` `622cb03f7e070a9670c94bae1a45d78d7181fbd4` `x64`
- OS Version:

Remote | WSL: Ubuntu-18.04
-- | --
OS | Linux x64 5.4.72-microsoft-standard-WSL2

Steps to Reproduce:

1. export EDITOR='code --wait'
2. git rebase -i origin/master

![image](https://user-images.githubusercontent.com/3138467/108889849-d4e48b00-75da-11eb-9000-5f061cc8b560.png)

These steps seem to initiate a "gitlense interactive rebase" but I just want my normal interactive rebase... It seems to do this because gitlense is the default editor for files called "git-rebase-todo"

![image](https://user-images.githubusercontent.com/3138467/108889980-fba2c180-75da-11eb-9d54-fb086d2ee061.png)

Nothing logs to the GitLense output even with `"gitlens.outputLevel": "debug"`. I just want to stop gitlense from automatically opening the git-rebase-todo if possible.

**Comment by BlackthornYugen** [comment] 2021-02-23 18:30
The "Switch to text" and "disable rebase editor" buttons both don't actually do anything nor do they produce anything in the gitlense output.

**Comment by eamodio** [comment] 2021-03-01 04:45
Duplicate of #1172 which should be fixed in the latest VS Code insiders: https://github.com/eamodio/vscode-gitlens/issues/1172#issuecomment-787632412

**Closed by eamodio** 2021-03-01 04:45 UTC
Labels: potential-bug, triage

**Comment by BlackthornYugen** [comment] 2021-03-01 20:45
Had a look at #1172 and I can verify that installing gitlense locally seems to be an interim solution.

**Comment by BlackthornYugen** [comment] 2021-03-02 17:04
Hope so. VSCode started disabling my local GitLense, and won't seem to let me disable the remote one. I disable it, then it says it will take effect after a reload but it re-enables it on me after restarting.

![image](https://user-images.githubusercontent.com/3138467/109685581-6316bf00-7b4f-11eb-95b7-1377743851dd.png)

**Comment by BlackthornYugen** [comment] 2021-03-02 17:06
For the day that it worked for me, I actually liked the GitLense rebase interface. It had nice shortcut keys and had a nice clear way of presenting all the info without changing to far from the text way of doing it. It also lets you switch to the text form if you want too. 

Looking forward to 1.54 :)
