### ISSUE TITLE
how to use the compare update operation?

### ISSUE THREAD

**Issue by luojinghui** [eamodio/vscode-gitlens#770] opened 2019-06-25 11:43 UTC
This is a comparison of git conflicts. The left side is the remote resource and the right side is the local resource.

![image](https://user-images.githubusercontent.com/12367406/60095384-001d3400-9781-11e9-89ae-139cbfe9b7b3.png)

But I couldn't find the action button for the merge a line.

 I hope to be able to offer buttons/actions to move/copy lines between each side, the purpose is to compare conflicts and then selectively merge conflicting content.

**Comment by eamodio** [comment] 2019-06-27 09:04
I'm not exactly sure what you are asking for here, but VS Code doesn't offer much control/extensibility of its diff view (the image you posted above). There a requests opened for VS Code to offer buttons/actions to move/copy lines between each side, etc. Is that what you are asking about?

**Comment by luojinghui** [comment] 2019-06-28 03:21
@eamodio
This is a comparison of git conflicts. The left side is the remote resource and the right side is the local resource.

As you said, I hope to be able to offer buttons/actions to move/copy lines between each side, the purpose is to compare conflicts and then selectively merge conflicting content.

**Comment by eamodio** [comment] 2019-11-12 05:02
Duplicate of https://github.com/eamodio/vscode-gitlens/issues/647

**Closed by eamodio** 2019-11-12 05:02 UTC
Labels: status: duplicate
