### ISSUE TITLE
No way to disable "GitLens would like to connect to GitHub"

### ISSUE THREAD

**Issue by lexicalunit** [eamodio/vscode-gitlens#1275] opened 2020-12-17 23:13 UTC
I don't want GitLens to try and do this. There doesn't seem to be a way to disable this though. This is a bug because there seems to be no way to permanently disable this popup. I get it every time I open a file.

- GitLens Version: 11.0.6
- Git Version: 2.29.2
- VSCode Version: 1.52.1 // ea3859d4ba2f3e577a159bc91e3074c5d85c0523 // x64
- OS Version: macOS 10.15.7

Steps to Reproduce:

1. Open a file.

**Comment by eamodio** [comment] 2020-12-18 00:50
Duplicate of #1208

**Closed by eamodio** 2020-12-18 00:50 UTC
Labels: duplicate
