### ISSUE TITLE
alt+c and alt+w key bindings conflicts with add next occurrence's options

### ISSUE THREAD

**Issue by yoshijava** [eamodio/vscode-gitlens#113] opened 2017-07-09 01:36 UTC
- GitLens Version: 4.3.1
- VSCode Version: 1.13.1
- OS Version: Windows 10

Steps to Reproduce:

1. ctrl+d to select next occurrence
2. alt+c and alt+w, which are the default key bindings for case sensitivity and select whole word

**Comment by eamodio** [comment] 2017-07-28 20:01
Opened https://github.com/Microsoft/vscode/issues/31683

**Comment by eamodio** [comment] 2017-10-10 22:37
Closing as duplicate of https://github.com/eamodio/vscode-gitlens/issues/104

**Closed by eamodio** 2017-10-10 22:37 UTC
