### ISSUE TITLE
Opened revisions of file history are linted by the editor

### ISSUE THREAD

**Issue by infctr** [eamodio/vscode-gitlens#452] opened 2018-07-20 11:47 UTC
So whenever I checkout the revision of a file (comparing commits) from GitLens File History sidebar (doesn't matter) the files in the diff view get linted by editor linters (ts, vscode-tslint, vscode-eslint) and all linting errors are shown in Problems panel and stay there after closing the diff view. 

That seems like really an unexpected behavior because temp files are created in `/var/folders/` and are not related to the project folder so linters should not lint these files at all. Morever, linted output stays in the Problems panel even when the files are closed and I couldn't find any other way to get rid of them other then Reload Window from command panel. 

<img width="718" alt="screenshot 2018-07-16 13 24 33" src="https://user-images.githubusercontent.com/15550153/43000532-7bb911dc-8c2a-11e8-926c-25995f00772a.png">

I was able to disable tslint linting with 
```
"tslint.exclude": [
    "**/var/folders/**/*.*",
  ]
```
but not vscode ts linter. 

So is there any way to disable revision preview files from being linted or is this a bug?

[GitLens output log](https://pastebin.com/Yf0R1wHk)

- GitLens Version: 8.5.2
- VSCode Version: 
1.25.1
1dfc5e557209371715f655691b1235b6b26a06be
x64
- OS Version:
macOS High Sierra 10.13.5 (17F77)

**Comment by eamodio** [comment] 2018-07-20 17:16
Duplicate of #430. I am looking into avoiding these issues.

**Closed by eamodio** 2018-07-20 17:16 UTC

**Comment by infctr** [comment] 2018-08-08 13:13
@eamodio Is there a way to manually remove these files from the Problems View at least? When files are closed they are not listed in Opened Editors and seems there's no other way to ignore the Problems output.
