### ISSUE TITLE
Too many code lenses in postcss files 

### ISSUE THREAD

**Issue by Aarbel** [eamodio/vscode-gitlens#362] opened 2018-05-02 13:05 UTC
Hi Git Lens teams, gitlens infos are quite overflowing css files. How could i remove them ? 

Thanks
 

![image](https://user-images.githubusercontent.com/25119847/39523180-fac16d34-4e14-11e8-8fd7-b6a7033590ea.png)

**Comment by eamodio** [comment] 2018-05-04 01:30
Is that a standard CSS file? I can't reproduce that behavior. Is it possible you have a custom setting for `gitlens.codeLens.scopesByLanguage`?

**Comment by eamodio** [comment] 2018-05-23 13:43
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!

**Comment by Aarbel** [comment] 2018-05-23 14:03
@eamodio  It's a postcss file, sorry i didn't saw your answer

**Comment by eamodio** [comment] 2018-05-23 14:07
@Aarbel np -- what is the extension of the file?

**Comment by eamodio** [comment] 2018-05-25 23:31
@Aarbel if you add the following to your settings.json
```json
"gitlens.codeLens.scopesByLanguage": [
    {
        "language": "css",
        "scopes": [
            "document"
        ]
    },
    {
        "language": "html",
        "scopes": [
            "document"
        ]
    },
    {
        "language": "json",
        "scopes": [
            "document"
        ]
    },
    {
        "language": "jsonc",
        "scopes": [
            "document"
        ]
    },
    {
        "language": "less",
        "scopes": [
            "document"
        ]
    },
    {
        "language": "postcss",
        "scopes": [
            "document"
        ]
    },
    {
        "language": "python",
        "symbolScopes": [
            "!Module"
        ]
    },
    {
        "language": "scss",
        "scopes": [
            "document"
        ]
    },
    {
        "language": "stylus",
        "scopes": [
            "document"
        ]
    },
    {
        "language": "vue",
        "scopes": [
            "document"
        ]
    }
]
```

Does it resolve the issue for you?

**Closed** 2018-05-31 05:46 UTC
Labels: bug, needs more info
