### ISSUE TITLE
How do I stop gitlens from asking me to sign in?

### ISSUE THREAD

**Issue by 54696d21** [eamodio/vscode-gitlens#1233] opened 2020-12-03 00:26 UTC
It often asks me (every 2nd or 3rd time I start VS Code) if I want to sign in with Github. How do I turn this off?

**Comment by mrboring** [comment] 2020-12-06 10:11
@54696d21 The following worked for me:

* Go into the VS Code settings (`Ctrl+,`)
* Search for `github`
* In the left hand menu that appears in the search results, click `GitLens`
* Untick all settings that have `Requires a connection to a supported remote service (e.g. GitHub)`
* `Ctrl+Shift+P` - `Developer: Reload Window`

It would be nice if there was a single setting to disable this.

**Comment by 54696d21** [comment] 2020-12-06 13:02
so pasting this block into the settings.json should achieve it

```json
  "gitlens.currentLine.pullRequests.enabled": false,
  "gitlens.hovers.autolinks.enhanced": false,
  "gitlens.hovers.pullRequests.enabled": false,
  "gitlens.statusBar.pullRequests.enabled": false,
  "gitlens.views.branches.pullRequests.enabled": false,
  "gitlens.views.branches.pullRequests.showForBranches": false,
  "gitlens.views.branches.pullRequests.showForCommits": false,
  "gitlens.views.commits.pullRequests.enabled": false,
  "gitlens.views.commits.pullRequests.showForBranches": false,
  "gitlens.views.commits.pullRequests.showForCommits": false,
  "gitlens.views.contributors.pullRequests.enabled": false,
  "gitlens.views.contributors.pullRequests.showForCommits": false,
  "gitlens.views.searchAndCompare.pullRequests.showForCommits": false,
  "gitlens.views.searchAndCompare.pullRequests.enabled": false,
  "gitlens.views.repositories.pullRequests.showForCommits": false,
  "gitlens.views.repositories.pullRequests.showForBranches": false,
  "gitlens.views.repositories.pullRequests.enabled": false,
  "gitlens.views.remotes.pullRequests.showForCommits": false,
  "gitlens.views.remotes.pullRequests.showForBranches": false,
  "gitlens.views.remotes.pullRequests.enabled": false
```

**Comment by mrboring** [comment] 2020-12-06 13:15
Yes. Thats what I have in my settings.json. Only did it a couple of hours ago, but seems OK at the moment.

**Comment by eamodio** [comment] 2020-12-07 07:01
An easy opt-out is coming very soon, or you can use the [Insiders edition](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders) today. Sorry for the inconvenience :sad:

**Comment by eamodio** [comment] 2020-12-07 07:01
Closing this as a duplicate of #1208

**Closed by eamodio** 2020-12-07 07:01 UTC
Labels: type: question
