### ISSUE TITLE
unnecessary reloading of the file history view?

### ISSUE THREAD

**Issue by ryenus** [eamodio/vscode-gitlens#841] opened 2019-09-04 09:46 UTC
- GitLens Version: 9.9.3
  
- VSCode Version: 1.37.1
- OS Version: macOS 10.14.6

0. disable **Git: Auto Fetch** in vscode settings.
1. open the **File History** view for a file already tracked in a git repository.
2. navigate/click through the history commits
3. the file history view is reloaded many times

My guess is such kind of reloading can be avoided when there's no new commits?
Another minor problem is the currently selected entry is lost upon view reloading.

**Comment by eamodio** [comment] 2019-09-04 15:27
I can't seem to reproduce this. Please enable output channel logging by setting `"gitlens.outputLevel": "debug"` in your settings. This will enable logging to the *GitLens* channel in the *Output* pane. Once enabled, please reproduce the issue and attach the log from the *GitLens* channel. Thanks!

**Comment by eamodio** [comment] 2019-09-24 05:57
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!

**Closed by eamodio** 2019-09-24 05:58 UTC
Labels: status: needs more info
