### ISSUE TITLE
Merge commits are missing from file history

### ISSUE THREAD

**Issue by borekb** [eamodio/vscode-gitlens#766] opened 2019-06-11 19:36 UTC
- GitLens Version: 9.8.2
VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:16:40.241Z)
OS version: Darwin x64 18.6.0

This is listed by `git log`:

<img width="512" alt="Screenshot 2019-06-11 at 21 31 46" src="https://user-images.githubusercontent.com/101152/59300835-6f2e5f00-8c90-11e9-99f5-b0163010d0e6.png">

This is shown by GitLens:

<img width="400" alt="Screenshot 2019-06-11 at 21 33 16" src="https://user-images.githubusercontent.com/101152/59300885-96852c00-8c90-11e9-855e-f559e90f31b3.png">

Note how the merge commits are missing even though they are significant (for this specific file, merge commits had conflicts in this `package.json` and there's a real diff introduced by the merge commit).

**Comment by eamodio** [comment] 2019-06-11 20:00
@borekb this is expected behavior if the _File History_ (and _Line History_) are following renames (this is because `git log --follow` does not play nicely with merge commits (it ends up including tons of unrelated merge commits). If you turn off rename following in the view (under the `...` menu), merge commit should show up.

Is that the behavior you are seeing?

**Comment by borekb** [comment] 2019-06-11 20:17
Oh yes, you're right. It's actually close to impossible to get `git log` behave correctly with `--follow`, it seems: https://stackoverflow.com/a/46492159/21728:

> > How can I display cleanly all of the commits that changed a file, following through renames?
>
> The answer for Git is that you can't, at least not using what is built in to Git.
>
> You can (sometimes) get a little closer by adding `--cc` or `-c` to your git log command. This makes git log look inside merge commits, doing what Git calls a combined diff. But this doesn't necessarily work anyway. [...]

Wow, what a nasty behavior :)

**Comment by eamodio** [comment] 2019-06-11 20:19
Yeah, I've fought with trying to wrangle `git log` with `--follow` and it is just a nightmare -- it changes the behavior of so many of the options (and its not documented that it does).

**Comment by eamodio** [comment] 2019-06-11 21:57
Closing as this is the best I can do with Git currently

**Closed by eamodio** 2019-06-11 21:57 UTC
Labels: status: not bug
