### ISSUE TITLE
gitlens disables coloring for modified files in file explorer in latest 1.8 vscode

### ISSUE THREAD

**Issue by atomi** [eamodio/vscode-gitlens#199] opened 2017-11-12 18:29 UTC
- GitLens Version: latest
- VSCode Version: 1.8
- OS Version: mint 18

Steps to Reproduce:

1. install gitlens
2. coloring in file explorer is disabled

**Comment by eamodio** [comment] 2017-11-12 21:01
I can't reproduce this -- nor should GitLens even have the ability to affect the coloring of files in the File Explorer. If you truly have it narrowed down to installing GitLens to the issue, I would suggest opening an issue with the vscode repo, as there isn't even a current api that GitLens could use to affect that.

**Comment by eamodio** [comment] 2017-11-13 20:59
Closing this -- and if indeed it does turn out to be some GitLens thing, we can re-open.

**Closed by eamodio** 2017-11-13 20:59 UTC
Labels: needs more info, vscode issue
