### ISSUE TITLE
GitLens only available in SCM diff windows

### ISSUE THREAD

**Issue by Arnaud73** [eamodio/vscode-gitlens#262] opened 2018-01-26 18:19 UTC
- GitLens Version: 7.5.7
- VSCode Version: 1.19.3
- OS Version: Mac OS Sierra

Steps to Reproduce: Can't say for sure
Extensions : GitLens is my only extension activated in my test workspace.
Settings : User settings do not contain anything for git / gitlens. Workspace settings are empty.

Behavior:
* GitLens is not available in any editor, for any kind of file. The GitLens icon at the right hand-side of the tab bar is not displayed.
* GitLens is available for SCM diff tabs.

Needless to say I really miss GitLens for my everyday work, but I can't figure out what's preventing of making it appear again.

**Comment by eamodio** [comment] 2018-01-27 15:25
I'm really sorry about the issues you are experiencing. When you say GitLens is available for SCM diff tabs can you expand on that? Also I would recommend, uninstall GitLens, restarting vscode twice (making sure all vscode windows are closed when doing this), and then re-install GitLens. I have heard of some issues when GitLens was upgraded but didn't install properly.

If that still doesn't help please enable output channel logging by setting `"gitlens.outputLevel": "verbose"` in your settings.json. This will enable logging to the GitLens channel in the Output pane. Once enabled, please attempt to reproduce the issue (if possible) and attach the relevant log lines from the GitLens channel.

**Comment by Arnaud73** [comment] 2018-01-29 10:04
Here are two screenshots of the view of a file and the view of the same file in Git Diff mode:

![gitlens - 1](https://user-images.githubusercontent.com/3791370/35504561-aa5b8b9c-04e3-11e8-8747-da307b777ec1.png)

![gitlens - 2](https://user-images.githubusercontent.com/3791370/35504560-aa3f65b6-04e3-11e8-9d18-1001eb3e4f3b.png)

As you can see, GitLens is available (and works) in one tab, but is not available in the second one.

I tried to uninstall, close all windows and restart VS Code several times, then reinstall the extension, but it did not help.

Here is the output of the extension:
```
Git found: 2.14.3 (Apple Git-98) @ /usr/bin/git in 52 ms
Running(/Users/Arnaud/Développement/angular-cli-runner): git rev-parse --show-toplevel
GitLens(v7.5.7) activated in 93 ms
Completed(/Users/Arnaud/Développement/angular-cli-runner): git rev-parse --show-toplevel in 37 ms
Searching (depth=1) for repositories in /Users/Arnaud/Développement/angular-cli-runner took 10 ms
Running(/Users/Arnaud/Développement/angular-cli-runner): git rev-parse --show-toplevel
Completed(/Users/Arnaud/Développement/angular-cli-runner): git rev-parse --show-toplevel in 11 ms
getRemotesCore('/Users/Arnaud/Développement/angular-cli-runner')
Running(/Users/Arnaud/Développement/angular-cli-runner): git remote -v
Completed(/Users/Arnaud/Développement/angular-cli-runner): git remote -v in 141 ms
Running(/Users/Arnaud/Library/Application Support/Code/User): git rev-parse --show-toplevel
Error(/usr/bin/git -c core.quotepath=false -c color.ui=false rev-parse --show-toplevel):  (128) fatal: Not a git repository (or any of the parent directories): .git

Completed(/Users/Arnaud/Library/Application Support/Code/User): git rev-parse --show-toplevel in 18 ms
isTracked('/Users/Arnaud/Library/Application Support/Code/User/settings.json', 'undefined', 'undefined')
Running(): git ls-files /Users/Arnaud/Library/Application Support/Code/User/settings.json
Error(/usr/bin/git -c core.quotepath=false -c color.ui=false ls-files /Users/Arnaud/Library/Application Support/Code/User/settings.json):  (128) fatal: Not a git repository (or any of the parent directories): .git

Completed(): git ls-files /Users/Arnaud/Library/Application Support/Code/User/settings.json in 39 ms
getStatusForRepo('/Users/Arnaud/Développement/angular-cli-runner')
Running(/Users/Arnaud/Développement/angular-cli-runner): git status --porcelain=v2 --branch -u
Completed(/Users/Arnaud/Développement/angular-cli-runner): git status --porcelain=v2 --branch -u in 19 ms
getStatusForRepo('/Users/Arnaud/Développement/angular-cli-runner')
Running(/Users/Arnaud/Développement/angular-cli-runner): git status --porcelain=v2 --branch -u
getBranches('/Users/Arnaud/Développement/angular-cli-runner')
Running(/Users/Arnaud/Développement/angular-cli-runner): git branch -vv -a
Completed(/Users/Arnaud/Développement/angular-cli-runner): git branch -vv -a in 48 ms
Completed(/Users/Arnaud/Développement/angular-cli-runner): git status --porcelain=v2 --branch -u in 64 ms
getChangedFilesCount('/Users/Arnaud/Développement/angular-cli-runner', 'origin/master...')
Running(/Users/Arnaud/Développement/angular-cli-runner): git diff --shortstat --no-ext-diff origin/master...
Completed(/Users/Arnaud/Développement/angular-cli-runner): git diff --shortstat --no-ext-diff origin/master... in 31 ms
Running(/Users/Arnaud/Développement/angular-cli-runner): git rev-parse --show-toplevel
Completed(/Users/Arnaud/Développement/angular-cli-runner): git rev-parse --show-toplevel in 14 ms
isTracked('/Users/Arnaud/Développement/angular-cli-runner/Dockerfile', '/Users/Arnaud/Développement/angular-cli-runner', 'undefined')
Running(/Users/Arnaud/Développement/angular-cli-runner): git ls-files /Users/Arnaud/Développement/angular-cli-runner/Dockerfile
Error(/usr/bin/git -c core.quotepath=false -c color.ui=false ls-files /Users/Arnaud/Développement/angular-cli-runner/Dockerfile):  (128) fatal: /Users/Arnaud/Développement/angular-cli-runner/Dockerfile: '/Users/Arnaud/Développement/angular-cli-runner/Dockerfile' is outside repository

Completed(/Users/Arnaud/Développement/angular-cli-runner): git ls-files /Users/Arnaud/Développement/angular-cli-runner/Dockerfile in 12 ms
isTracked('Dockerfile', '/Users/Arnaud/Développement/angular-cli-runner', 'undefined')
Running(/Users/Arnaud/Développement/angular-cli-runner): git ls-files Dockerfile
Completed(/Users/Arnaud/Développement/angular-cli-runner): git ls-files Dockerfile in 24 ms
isTracked('/Users/Arnaud/Développement/angular-cli-runner/Dockerfile', '/Users/Arnaud/Développement/angular-cli-runner', 'undefined')
getBranch('/Users/Arnaud/Développement/angular-cli-runner')
Running(/Users/Arnaud/Développement/angular-cli-runner): git rev-parse --abbrev-ref --symbolic-full-name @ @{u}
Completed(/Users/Arnaud/Développement/angular-cli-runner): git rev-parse --abbrev-ref --symbolic-full-name @ @{u} in 15 ms
getBlameForLine('/Users/Arnaud/Développement/angular-cli-runner', '/Users/Arnaud/Développement/angular-cli-runner/Dockerfile', 'undefined', 10)
getBlameForFile[Not Cached(blame)]('/Users/Arnaud/Développement/angular-cli-runner', '/Users/Arnaud/Développement/angular-cli-runner/Dockerfile', 'undefined')
isTracked('/Users/Arnaud/Développement/angular-cli-runner/Dockerfile', '/Users/Arnaud/Développement/angular-cli-runner', 'undefined')
Add blame cache for '/users/arnaud/développement/angular-cli-runner/dockerfile:blame'
Running(/Users/Arnaud/Développement/angular-cli-runner): git blame --root --incremental -- Dockerfile
Completed(/Users/Arnaud/Développement/angular-cli-runner): git blame --root --incremental -- Dockerfile in 13 ms
```

**Comment by eamodio** [comment] 2018-01-30 03:24
Really sorry for the inconvenience :( This should be fixed in 7.5.8. Please let me know if you still run into any issues.

**Comment by Arnaud73** [comment] 2018-01-30 10:36
I was very happy to get back GitLens this morning...
But after having upgraded to 7.5.9, then tried to uninistall the extension / close / restart VSCode / reinstall the extension, still no improvement.
There seems to be something more to the problem.
How can I help?

**Comment by eamodio** [comment] 2018-01-30 13:56
Is there a public repo that you can reproduce this on?

**Comment by eamodio** [comment] 2018-01-30 16:33
Could you also attach new logs from v7.5.9 so I can compare?

**Comment by bypotatoes** [comment] 2018-01-31 13:10
It seems I've stuck with the same issue

- GitLens Version: 7.5.9
- VSCode Version: 1.19.3
- OS Version: Mac OS High Sierra v10.13.3

I hope this log will help, as you may get from it I just opened vscode and went through few files in filetree 
```
Git found: 2.8.2 @ usr/local/bin/git in 28 ms
Running(/Users/bypotatoes/Projects/ng2-app): git rev-parse --show-toplevel
GitLens(v7.5.9) activated in 47 ms
Error(usr/local/bin/git -c core.quotepath=false -c color.ui=false rev-parse --show-toplevel):  (ENOENT) 
Completed(/Users/bypotatoes/Projects/ng2-app): git rev-parse --show-toplevel in 13 ms
Searching (depth=1) for repositories in /Users/bypotatoes/Projects/ng2-app took 41 ms
Running(/Users/bypotatoes/Projects/ng2-app): git rev-parse --show-toplevel
Error(usr/local/bin/git -c core.quotepath=false -c color.ui=false rev-parse --show-toplevel):  (ENOENT) 
Completed(/Users/bypotatoes/Projects/ng2-app): git rev-parse --show-toplevel in 4 ms
Running(/Users/bypotatoes/Library/Application Support/Code/User): git rev-parse --show-toplevel
Error(usr/local/bin/git -c core.quotepath=false -c color.ui=false rev-parse --show-toplevel):  (ENOENT) 
Completed(/Users/bypotatoes/Library/Application Support/Code/User): git rev-parse --show-toplevel in 3 ms
isTracked('/Users/bypotatoes/Library/Application Support/Code/User/settings.json', 'undefined', 'undefined')
Running(): git ls-files /Users/bypotatoes/Library/Application Support/Code/User/settings.json
Error(usr/local/bin/git -c core.quotepath=false -c color.ui=false ls-files /Users/bypotatoes/Library/Application Support/Code/User/settings.json):  (128) fatal: Not a git repository (or any of the parent directories): .git

Completed(): git ls-files /Users/bypotatoes/Library/Application Support/Code/User/settings.json in 22 ms
Running(/Users/bypotatoes/Projects/ng2-app/src/app): git rev-parse --show-toplevel
Error(usr/local/bin/git -c core.quotepath=false -c color.ui=false rev-parse --show-toplevel):  (ENOENT) 
Completed(/Users/bypotatoes/Projects/ng2-app/src/app): git rev-parse --show-toplevel in 5 ms
isTracked('/Users/bypotatoes/Projects/ng2-app/src/app/app.module.ts', 'undefined', 'undefined')
Running(): git ls-files /Users/bypotatoes/Projects/ng2-app/src/app/app.module.ts
Error(usr/local/bin/git -c core.quotepath=false -c color.ui=false ls-files /Users/bypotatoes/Projects/ng2-app/src/app/app.module.ts):  (128) fatal: Not a git repository (or any of the parent directories): .git

Completed(): git ls-files /Users/bypotatoes/Projects/ng2-app/src/app/app.module.ts in 43 ms
Running(/Users/bypotatoes/Projects/ng2-app/src/app): git rev-parse --show-toplevel
Error(usr/local/bin/git -c core.quotepath=false -c color.ui=false rev-parse --show-toplevel):  (ENOENT) 
Completed(/Users/bypotatoes/Projects/ng2-app/src/app): git rev-parse --show-toplevel in 4 ms
isTracked('/Users/bypotatoes/Projects/ng2-app/src/app/app.component.ts', 'undefined', 'undefined')
Running(): git ls-files /Users/bypotatoes/Projects/ng2-app/src/app/app.component.ts
Error(usr/local/bin/git -c core.quotepath=false -c color.ui=false ls-files /Users/bypotatoes/Projects/ng2-app/src/app/app.component.ts):  (128) fatal: Not a git repository (or any of the parent directories): .git

Completed(): git ls-files /Users/bypotatoes/Projects/ng2-app/src/app/app.component.ts in 6 ms
Running(/Users/bypotatoes/Projects/ng2-app/src/app): git rev-parse --show-toplevel
Error(usr/local/bin/git -c core.quotepath=false -c color.ui=false rev-parse --show-toplevel):  (ENOENT) 
Completed(/Users/bypotatoes/Projects/ng2-app/src/app): git rev-parse --show-toplevel in 4 ms
isTracked('/Users/bypotatoes/Projects/ng2-app/src/app/app.component.html', 'undefined', 'undefined')
Running(): git ls-files /Users/bypotatoes/Projects/ng2-app/src/app/app.component.html
Error(usr/local/bin/git -c core.quotepath=false -c color.ui=false ls-files /Users/bypotatoes/Projects/ng2-app/src/app/app.component.html):  (128) fatal: Not a git repository (or any of the parent directories): .git

Completed(): git ls-files /Users/bypotatoes/Projects/ng2-app/src/app/app.component.html in 21 ms
```

**Comment by Arnaud73** [comment] 2018-01-31 16:03
Some more information (sorry I'm rather busy since yesterday):
* the problem arises in all my workspaces, whatever extensions are selected (10s of them or just GitLens)
* the problem does not arise on my Windows laptop with almost the same list of extensions, when checking the same Git repositories.

**Comment by Arnaud73** [comment] 2018-01-31 16:06
Here is the output of GitLens in my simple workspace for testing this issues (all other extensions deactivated):
```
Git found: 2.14.3 (Apple Git-98) @ /usr/bin/git in 23 ms
Running(/Users/Arnaud/Développement/angular-cli-runner): git rev-parse --show-toplevel
GitLens(v7.5.9) activated in 63 ms
Completed(/Users/Arnaud/Développement/angular-cli-runner): git rev-parse --show-toplevel in 33 ms
Searching (depth=1) for repositories in /Users/Arnaud/Développement/angular-cli-runner took 8 ms
Running(/Users/Arnaud/Développement/angular-cli-runner): git rev-parse --show-toplevel
Completed(/Users/Arnaud/Développement/angular-cli-runner): git rev-parse --show-toplevel in 18 ms
getRemotesCore('/Users/Arnaud/Développement/angular-cli-runner')
Running(/Users/Arnaud/Développement/angular-cli-runner): git remote -v
Completed(/Users/Arnaud/Développement/angular-cli-runner): git remote -v in 37 ms
Running(/Users/Arnaud/Développement/angular-cli-runner): git rev-parse --show-toplevel
Completed(/Users/Arnaud/Développement/angular-cli-runner): git rev-parse --show-toplevel in 17 ms
isTracked('/Users/Arnaud/Développement/angular-cli-runner/Dockerfile', '/Users/Arnaud/Développement/angular-cli-runner', 'undefined')
Running(/Users/Arnaud/Développement/angular-cli-runner): git ls-files /Users/Arnaud/Développement/angular-cli-runner/Dockerfile
getStatusForRepo('/Users/Arnaud/Développement/angular-cli-runner')
Running(/Users/Arnaud/Développement/angular-cli-runner): git status --porcelain=v2 --branch -u
Error(/usr/bin/git -c core.quotepath=false -c color.ui=false ls-files /Users/Arnaud/Développement/angular-cli-runner/Dockerfile):  (128) fatal: /Users/Arnaud/Développement/angular-cli-runner/Dockerfile: '/Users/Arnaud/Développement/angular-cli-runner/Dockerfile' is outside repository

Completed(/Users/Arnaud/Développement/angular-cli-runner): git ls-files /Users/Arnaud/Développement/angular-cli-runner/Dockerfile in 36 ms
Completed(/Users/Arnaud/Développement/angular-cli-runner): git status --porcelain=v2 --branch -u in 33 ms
getStatusForRepo('/Users/Arnaud/Développement/angular-cli-runner')
Running(/Users/Arnaud/Développement/angular-cli-runner): git status --porcelain=v2 --branch -u
getBranches('/Users/Arnaud/Développement/angular-cli-runner')
Running(/Users/Arnaud/Développement/angular-cli-runner): git branch -vv -a
Completed(/Users/Arnaud/Développement/angular-cli-runner): git status --porcelain=v2 --branch -u in 21 ms
getChangedFilesCount('/Users/Arnaud/Développement/angular-cli-runner', 'origin/master...')
Running(/Users/Arnaud/Développement/angular-cli-runner): git diff --shortstat --no-ext-diff origin/master...
Completed(/Users/Arnaud/Développement/angular-cli-runner): git branch -vv -a in 21 ms
Completed(/Users/Arnaud/Développement/angular-cli-runner): git diff --shortstat --no-ext-diff origin/master... in 12 ms
```

**Comment by eamodio** [comment] 2018-02-01 04:31
@bypotatoes I don't think these are the same issues. I believe your issue is that either the path where GitLens thinks it found git must not exist or the some other path doesn't (as it is failing with ENOENT). 

What happens when you run `usr/local/bin/git rev-parse --show-toplevel` from `/Users/bypotatoes/Projects/ng2-app` does it work? Or fail with ENOENT?

**Comment by eamodio** [comment] 2018-02-01 04:39
@Arnaud73 What happens when you run `/usr/bin/git ls-files /Users/Arnaud/Développement/angular-cli-runner/Dockerfile` in a terminal? Is there anything special about the repository? Or the Dockerfile -- it is part of the repo right?

What does the folder structure look like i.e. where is the .git folder?

**Comment by bypotatoes** [comment] 2018-02-01 07:19
@eamodio O, yeah, I see, ofc it fails with `no such file or directory: usr/local/bin/git`, sorry that I've missed that simple fact

And for sure `/usr/local/bin/git rev-parse --show-toplevel` works. Do you think it what causes missing of `/` at the beginning of the path? Thanks

**Comment by eamodio** [comment] 2018-02-01 07:37
Wow -- I missed the missing `/` at the front. I'll have to look into how that could have happened. For now though, you can set `"gitlens.advanced.git": "/usr/local/bin/git"` and that should fix the issue for you.

**Comment by bypotatoes** [comment] 2018-02-01 07:41
o, thanks, it works, just noticed that there's explicit `"git.path": "/usr/local/bin/git"` at the top of user settings, maybe it will help somehow

**Comment by eamodio** [comment] 2018-02-01 07:58
Great -- glad to hear that works. Can you run `which git` in a terminal and send the output? I'm wondering how that `/` went missing

**Comment by eamodio** [comment] 2018-02-01 08:59
Odd -- thanks

**Comment by Arnaud73** [comment] 2018-02-05 18:01
Sorry for the delay.

Here are the requested informations:
```to read about a specific subcommand or concept.
 Arnaud@Mini  ~/Développement/angular-cli-runner   master ●  /usr/bin/git  version
git version 2.14.3 (Apple Git-98)
 Arnaud@Mini  ~/Développement/angular-cli-runner   master ●  /usr/bin/git ls-files /Users/Arnaud/Développement/angular-cli-runner/Dockerfile
fatal: /Users/Arnaud/Développement/angular-cli-runner/Dockerfile: '/Users/Arnaud/Développement/angular-cli-runner/Dockerfile' is outside repository
 ✘ Arnaud@Mini  ~/Développement/angular-cli-runner   master ●  git status
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   Dockerfile

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.vscode/

no changes added to commit (use "git add" and/or "git commit -a")
 Arnaud@Mini  ~/Développement/angular-cli-runner   master ●  git ls-files Dockerfile 
Dockerfile
```
The Dockerfile is part of the repo (https://github.com/Arnaud73/angular-cli-runner). Nothing specific there.

**Comment by eamodio** [comment] 2018-02-05 23:10
I tried pulling down your repo, and I can't reproduce any errors.

It looks like you have a folder `~/Développement/angular-cli-runner` and in there is your https://github.com/Arnaud73/angular-cli-runner repo. Correct?

How are you opening that folder in vscode? Are you opening the `~/Développement/angular-cli-runner` folder directly? Opening a parent folder?

I'm really at a loss as to what is going wrong. 

Can you attach the output from the *GitLens* output channel with 7.5.10, since it has a lot more logging at startup.

**Comment by Arnaud73** [comment] 2018-02-06 09:57
A complete screencast (a bit too long, sorry)

![gitlens](https://user-images.githubusercontent.com/3791370/35852935-8195f2fc-0b2c-11e8-8b60-3df54ce5d0ff.gif)

**Comment by Arnaud73** [comment] 2018-02-06 10:00
And the complete output of GitLens for this screencast:
```Git found: 2.14.3 (Apple Git-98) @ /usr/bin/git in 22 ms
Starting repository search in 1 folders
Searching for repositories (depth=1) in '/Users/Arnaud/Développement/angular-cli-runner' ...
Running(/Users/Arnaud/Développement/angular-cli-runner): git rev-parse --show-toplevel
GitLens(v7.5.10) activated in 63 ms
Completed(/Users/Arnaud/Développement/angular-cli-runner): git rev-parse --show-toplevel in 30 ms
Repository found in '/Users/Arnaud/Développement/angular-cli-runner'
Running(/Users/Arnaud/Développement/angular-cli-runner): git rev-parse --show-toplevel
Completed(/Users/Arnaud/Développement/angular-cli-runner): git rev-parse --show-toplevel in 49 ms
Repository found in '/Users/Arnaud/Développement/angular-cli-runner'
Searching for repositories (depth=1) in '/Users/Arnaud/Développement/angular-cli-runner' took 101 ms
getRemotesCore('/Users/Arnaud/Développement/angular-cli-runner')
Running(/Users/Arnaud/Développement/angular-cli-runner): git remote -v
Completed(/Users/Arnaud/Développement/angular-cli-runner): git remote -v in 17 ms
getStatusForRepo('/Users/Arnaud/Développement/angular-cli-runner')
Running(/Users/Arnaud/Développement/angular-cli-runner): git status --porcelain=v2 --branch -u
Completed(/Users/Arnaud/Développement/angular-cli-runner): git status --porcelain=v2 --branch -u in 15 ms
getStatusForRepo('/Users/Arnaud/Développement/angular-cli-runner')
Running(/Users/Arnaud/Développement/angular-cli-runner): git status --porcelain=v2 --branch -u
getBranches('/Users/Arnaud/Développement/angular-cli-runner')
Running(/Users/Arnaud/Développement/angular-cli-runner): git branch -vv -a
Completed(/Users/Arnaud/Développement/angular-cli-runner): git status --porcelain=v2 --branch -u in 18 ms
getChangedFilesCount('/Users/Arnaud/Développement/angular-cli-runner', 'origin/master...')
Running(/Users/Arnaud/Développement/angular-cli-runner): git diff --shortstat --no-ext-diff origin/master...
Completed(/Users/Arnaud/Développement/angular-cli-runner): git branch -vv -a in 18 ms
Completed(/Users/Arnaud/Développement/angular-cli-runner): git diff --shortstat --no-ext-diff origin/master... in 11 ms
Running(/Users/Arnaud/Développement/angular-cli-runner): git rev-parse --show-toplevel
Completed(/Users/Arnaud/Développement/angular-cli-runner): git rev-parse --show-toplevel in 29 ms
isTracked('/Users/Arnaud/Développement/angular-cli-runner/Dockerfile', '/Users/Arnaud/Développement/angular-cli-runner', 'undefined')
Running(/Users/Arnaud/Développement/angular-cli-runner): git ls-files /Users/Arnaud/Développement/angular-cli-runner/Dockerfile
Error(/Users/Arnaud/Développement/angular-cli-runner): /usr/bin/git -c core.quotepath=false -c color.ui=false ls-files /Users/Arnaud/Développement/angular-cli-runner/Dockerfile)
    (128) Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false ls-files /Users/Arnaud/Développement/angular-cli-runner/Dockerfile
fatal: /Users/Arnaud/Développement/angular-cli-runner/Dockerfile: '/Users/Arnaud/Développement/angular-cli-runner/Dockerfile' is outside repository

fatal: /Users/Arnaud/Développement/angular-cli-runner/Dockerfile: '/Users/Arnaud/Développement/angular-cli-runner/Dockerfile' is outside repository

Completed(/Users/Arnaud/Développement/angular-cli-runner): git ls-files /Users/Arnaud/Développement/angular-cli-runner/Dockerfile in 16 ms
isTracked('Dockerfile', '/Users/Arnaud/Développement/angular-cli-runner', 'undefined')
Running(/Users/Arnaud/Développement/angular-cli-runner): git ls-files Dockerfile
Completed(/Users/Arnaud/Développement/angular-cli-runner): git ls-files Dockerfile in 20 ms
isTracked('/Users/Arnaud/Développement/angular-cli-runner/Dockerfile', '/Users/Arnaud/Développement/angular-cli-runner', 'undefined')
Running(/Users/Arnaud/Développement/angular-cli-runner): git ls-files /Users/Arnaud/Développement/angular-cli-runner/Dockerfile
Completed(/Users/Arnaud/Développement/angular-cli-runner): git ls-files /Users/Arnaud/Développement/angular-cli-runner/Dockerfile in 21 ms
getBranch('/Users/Arnaud/Développement/angular-cli-runner')
Running(/Users/Arnaud/Développement/angular-cli-runner): git rev-parse --abbrev-ref --symbolic-full-name @ @{u}
Completed(/Users/Arnaud/Développement/angular-cli-runner): git rev-parse --abbrev-ref --symbolic-full-name @ @{u} in 17 ms
getBlameForLine('/Users/Arnaud/Développement/angular-cli-runner', '/Users/Arnaud/Développement/angular-cli-runner/Dockerfile', 'undefined', 10)
getBlameForFile[Not Cached(blame)]('/Users/Arnaud/Développement/angular-cli-runner', '/Users/Arnaud/Développement/angular-cli-runner/Dockerfile', 'undefined')
isTracked('/Users/Arnaud/Développement/angular-cli-runner/Dockerfile', '/Users/Arnaud/Développement/angular-cli-runner', 'undefined')
Add blame cache for '/users/arnaud/développement/angular-cli-runner/dockerfile:blame'
Running(/Users/Arnaud/Développement/angular-cli-runner): git blame --root --incremental -- Dockerfile
Completed(/Users/Arnaud/Développement/angular-cli-runner): git blame --root --incremental -- Dockerfile in 11 ms
getBlameForLine('/Users/Arnaud/Développement/angular-cli-runner', '/Users/Arnaud/Développement/angular-cli-runner/Dockerfile', 'undefined', 15)
getBlameForFile[Cached(blame)]('/Users/Arnaud/Développement/angular-cli-runner', '/Users/Arnaud/Développement/angular-cli-runner/Dockerfile', 'undefined')
getBlameForLine('/Users/Arnaud/Développement/angular-cli-runner', '/Users/Arnaud/Développement/angular-cli-runner/Dockerfile', 'undefined', 17)
getBlameForFile[Cached(blame)]('/Users/Arnaud/Développement/angular-cli-runner', '/Users/Arnaud/Développement/angular-cli-runner/Dockerfile', 'undefined')
getBlameForLine('/Users/Arnaud/Développement/angular-cli-runner', '/Users/Arnaud/Développement/angular-cli-runner/Dockerfile', 'undefined', 16)
getBlameForFile[Cached(blame)]('/Users/Arnaud/Développement/angular-cli-runner', '/Users/Arnaud/Développement/angular-cli-runner/Dockerfile', 'undefined')
Keyboard.beginScope 0
getBlameForFile[Cached(blame)]('/Users/Arnaud/Développement/angular-cli-runner', '/Users/Arnaud/Développement/angular-cli-runner/Dockerfile', 'undefined')
Add listener registrations for annotations
5 ms to compute gutter blame annotations
getBlameForLine('/Users/Arnaud/Développement/angular-cli-runner', '/Users/Arnaud/Développement/angular-cli-runner/Dockerfile', 'undefined', 16)
getBlameForFile[Cached(blame)]('/Users/Arnaud/Développement/angular-cli-runner', '/Users/Arnaud/Développement/angular-cli-runner/Dockerfile', 'undefined')
User: Clear annotations for vs.editor.ICodeEditor:4,$model5
KeyboardScope.dispose 1 0
Remove all listener registrations for annotations
getBlameForLine('/Users/Arnaud/Développement/angular-cli-runner', '/Users/Arnaud/Développement/angular-cli-runner/Dockerfile', 'undefined', 16)
getBlameForFile[Cached(blame)]('/Users/Arnaud/Développement/angular-cli-runner', '/Users/Arnaud/Développement/angular-cli-runner/Dockerfile', 'undefined')```

**Comment by eamodio** [comment] 2018-02-07 07:22
@Arnaud73 I'm at a complete loss on this. I have no idea why the call to `git ls-files /Users/Arnaud/Développement/angular-cli-runner/Dockerfile` is failing -- but that is the crux of it all. I've tried using your repo, on Windows & macOS and I can't reproduce it.

The last thing I would say to try is re-clone your repo into a new folder and see if the problem persists. And if no, then try to figure out what the difference between the 2 are.

**Comment by Arnaud73** [comment] 2018-02-12 13:14
I cannot say I have a multi-year experience with git, however, it seems to me that the commande `git ls-files` is for files in the Git Repo.
In my situation, the file `Dockerfile` is located at `/Users/Arnaud/Développement/angular-cli-runner/Dockerfile` in the filesystem but at `Dockerfile` in the repo because the repo is the directory `/Users/Arnaud/Développement/angular-cli-runner`.
From my understanding of git, it is rather normal that the command with the full path fails and the other one succeeds.
If I compare the git commands generated by the plugin, I have a `git ls-files Dockerfile` that is succeeding when in the SCM diff view, and a `git ls-files /Users/Arnaud/Développement/angular-cli-runner/Dockerfile` when accessing the file directly (which fails).

**Comment by eamodio** [comment] 2018-02-20 02:56
I'm sorry I still have no clue on this one. I have what seems to be the exact same setup (same macOS version, same Apple git version, same repo), and I can't reproduce any issues. If I run `git ls-files /Users/eric/Développement/angular-cli-runner/Dockerfile` it works perfectly fine. And I use `git ls-files` to tell me if the file actually belongs to a repo or not -- if it does it returns the filename.

I really don't know where to go from here. Can you try cloning your repo into a new folder and see if you have the same behavior? The fact that running the same (almost) git command as you and yours fails where mine succeeds it boggling. There must be something else going on in your config/machine/something as this is the only report I've ever seen like this.

**Comment by eamodio** [comment] 2018-03-12 05:32
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!

**Closed by eamodio** 2018-03-12 05:32 UTC
Labels: bug, needs more info
