### ISSUE TITLE
 blame annotation at the end of the current line carries over some formatting from code (namely, underline)

### ISSUE THREAD

**Issue by joelhock** [eamodio/vscode-gitlens#177] opened 2017-10-21 20:15 UTC
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:47:41.889Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|5.7.1
---

Steps to Reproduce:

1. add following `test.ts` file to git repo:
```typescript
// test.ts
let f: f
```

2. put cursor on second line and observe the bright-green underline continuing on through the end-of-line blame annotation
![image](https://user-images.githubusercontent.com/7648957/31855527-84730000-b672-11e7-9a0d-b0012fa5744a.png)

**Comment by eamodio** [comment] 2017-10-21 21:12
Duplicate of https://github.com/eamodio/vscode-gitlens/issues/110

**Closed by eamodio** 2017-10-21 21:12 UTC
