### ISSUE TITLE
Files History - View opened file history

### ISSUE THREAD

**Issue by marocas** [eamodio/vscode-gitlens#876] opened 2019-10-10 14:51 UTC
When I open my project with Workspace file configured with a folder's path to a subdirectory, Gitlens file history stops working.

How can am I doing something wrong or I'm missing some configuration?

Workspace file from VSCode:
```
{
	"folders": [
		{
			"path": "./workspace"
		}
	],
	"settings": {}
}
```

**Comment by eamodio** [comment] 2019-10-25 06:33
@marocas Can you provide more details? Where is the git repo (the `.git` folder) in relation to the workspace? I tried what you have suggested above and I can't reproduce an issue.

Please enable output channel logging by setting `"gitlens.outputLevel": "debug"` in your settings. This will enable logging to the *GitLens* channel in the *Output* pane. Once enabled, please reproduce the issue and attach the log from the *GitLens* channel.

**Comment by marocas** [comment] 2019-11-06 10:29
--project
---- .git
---- workspace
------ JS 
------ CSS

The .git folder is at the same level as the workspace.
This my project folder structure and I didn't get any output with the "debug" level.

**Comment by an-yun** [comment] 2019-11-09 07:31
I have the same problem. The error message is:

> cannot open vscode-remote://ssh-remote%2Bpoweredge/hot-data/zuofy/project/http_server/home/zuofy/project/http_server/src/request.cpp. Detail: 无法读取文件(Error: 找不到文件(vscode-remote://ssh-remote+poweredge/hot-data/zuofy/project/http_server/home/zuofy/project/http_server/src/request.cpp))

 I think it may be caused by link file, here are my situation:
1. I use remote-ssh to visit  my project, whose location is   `/home/zuofy/project/http_server` , and the directory `/home/zuofy/` is a soft link of `/hot-data/zuofy/`.
2. When I open my project (select directory `/home/zuofy/project/http_server` instead of  `/hot-data/zuofy/project/http_server`),  the default work directory of the terminal is `/home/zuofy/project/http_server`, which is so weird. You can see it in the following picture.
![problem](https://raw.githubusercontent.com/an-yun/http_server/master/img/gitlens.jpg)
3.Once I opened the file 'src/request.cpp' in my project, the lower-left corner error message in the above picture pop up, and the right file history doesn't work. Here are the debug outputs:
> [2019-11-09 07:19:45:441] [26] GitService.getCurrentUser completed • 113 ms
> [2019-11-09 07:19:45:442] [4b] GitBlameParser.parse completed • 0 ms
> [2019-11-09 07:19:45:442] [23] GitService.getBlameForFile completed • 149 ms
> [2019-11-09 07:19:45:442] [25] GitService.getBlameForFile completed • 119 ms
> [2019-11-09 07:19:45:442] [22] GitService.getBlameForLine completed • 149 ms
> [2019-11-09 07:19:45:443] [4c] LineAnnotationController.refresh
> [2019-11-09 07:19:45:443] [4d] LineAnnotationController.clear
> [2019-11-09 07:19:45:443] [4d] LineAnnotationController.clear completed • 0 ms
> [2019-11-09 07:19:45:446] [4c] LineAnnotationController.refresh completed • line(s)=4 • 3 ms
> [2019-11-09 07:19:45:625] GitCodeLensProvider.provideCodeLenses: — 5 symbol(s) found
> [2019-11-09 07:19:45:674] [4e] FileHistoryNode.ensureSubscription
> [2019-11-09 07:19:45:674] [4f] FileHistoryNode.subscribe
> [2019-11-09 07:19:45:674] [50] GitService.getRepository — e=GitUri(file:///hot-data/zuofy/project/http_server/home/zuofy/project/http_server/src/request.cpp repoPath=/hot-data/zuofy/project/http_server)
> [2019-11-09 07:19:45:674] [50] GitService.getRepository returned /hot-data/zuofy/project/http_server • 0 ms
> [2019-11-09 07:19:45:675] [4f] FileHistoryNode.subscribe completed • 0 ms
> [2019-11-09 07:19:45:675] [4e] FileHistoryNode.ensureSubscription completed • 0 ms
> [2019-11-09 07:19:45:675] [51] RepositoryNode(gitlens:repository(/hot-data/zuofy/project/http_server)).ensureSubscription
> [2019-11-09 07:19:45:675] [51] RepositoryNode(gitlens:repository(/hot-data/zuofy/project/http_server)).ensureSubscription completed • 0 ms
> [2019-11-09 07:19:45:677] [52] GitService.getStatusForFile — e=/hot-data/zuofy/project/http_server, t=/hot-data/zuofy/project/http_server/home/zuofy/project/http_server/src/request.cpp
> [2019-11-09 07:19:45:686] [53] RepositoriesView.getNodeLastMaxCount — e=BranchNode(gitlens:repository(/hot-data/zuofy/project/http_server):root:branch(master)+current):master
> [2019-11-09 07:19:45:686] [53] RepositoriesView.getNodeLastMaxCount completed • 0 ms
> [2019-11-09 07:19:45:687] [54] GitService.getRemotes — e=/hot-data/zuofy/project/http_server
> [2019-11-09 07:19:45:687] [55] GitService.getRepository — e=/hot-data/zuofy/project/http_server
> [2019-11-09 07:19:45:687] [55] GitService.getRepository returned /hot-data/zuofy/project/http_server • 0 ms
> [2019-11-09 07:19:45:687] [54] GitService.getRemotes completed • 0 ms
> [2019-11-09 07:19:45:688] [/hot-data/zuofy/project/http_server] git status --porcelain=v2 -- home/zuofy/project/http_server/src/request.cpp • 10 ms 
> [2019-11-09 07:19:45:688] [56] GitStatusParser.parse completed • 0 ms

Is there a bug of gitlens, or do I make some wrong configurations? Thank you for reading my problem.

**Comment by eamodio** [comment] 2019-11-11 05:13
@marocas I don't know why you wouldn't have gotten any output -- can you verify that it was set correctly? Do you see the `GitLens` channel in the output pane?

Also are you using a symlink in the project?

**Comment by an-yun** [comment] 2019-11-11 05:25
Yes, I'm using a symlink where I have mentioned in situation 2. You can see it in following picture.
![2019-11-11_132331](https://user-images.githubusercontent.com/10726030/68562923-b6f72380-0486-11ea-965a-89337e890f98.jpg)


And I see the `GitLens `channel in the output pane where is shown in situation 3. Here is the new picture.
![2019-11-11_132111](https://user-images.githubusercontent.com/10726030/68562805-2a4c6580-0486-11ea-9d7f-299afc5275c0.jpg)

**Comment by marocas** [comment] 2019-11-11 10:39
> 
> 
> @marocas I don't know why you wouldn't have gotten any output -- can you verify that it was set correctly? Do you see the `GitLens` channel in the output pane?
> 
> Also are you using a symlink in the project?

Hello @eamodio,
Yes, I do have a symlink on my project, but I don't work on does files.

Here are some screens of the vscode workspace file:

![screen_1 1](https://user-images.githubusercontent.com/7583302/68580867-27924600-046f-11ea-9a7e-d77276c977aa.png)
![screen_1 2](https://user-images.githubusercontent.com/7583302/68580877-2d882700-046f-11ea-8ddb-5ac7bb4f0deb.png)

These next images are from the same root of .git folder:
Same configurations with working file history.
![screen_2 1](https://user-images.githubusercontent.com/7583302/68580925-4690d800-046f-11ea-8576-9e0e6970340c.png)
![screen_2 2](https://user-images.githubusercontent.com/7583302/68580931-485a9b80-046f-11ea-9050-ccb8d9889b89.png)


Hope this helps to clarify this issue.

**Comment by eamodio** [comment] 2019-11-11 15:51
Duplicate of https://github.com/eamodio/vscode-gitlens/issues/677

**Closed by eamodio** 2019-11-11 15:51 UTC
Labels: status: duplicate

**Comment by marocas** [comment] 2019-11-12 19:04
```
[2019-11-12 18:59:39:011] [1] GitService.initialize
[2019-11-12 18:59:39:011] [2] GitService.getBuiltInGitApi
[2019-11-12 18:59:39:319] [2] GitService.getBuiltInGitApi completed • 308 ms
[2019-11-12 18:59:39:381] Git found: 2.23.0.windows.1 @ C:\Program Files\Git\cmd\git.exe • 61 ms
[2019-11-12 18:59:39:381] [1] GitService.initialize completed • 370 ms
[2019-11-12 18:59:39:382] Starting repository search in 1 folders
[2019-11-12 18:59:39:382] [3] GitService.repositorySearch(c:\projects\cenas-umbraco-dotnet\cenas.web) searching (depth=1)...
[2019-11-12 18:59:39:395] [4] GitUri.fromUri — e=Uri(file:///c:/projects/cenas-umbraco-dotnet/cenas.web/assets/scripts/services/account/addresses.js)
[2019-11-12 18:59:39:395] [5] GitService.getRepoPath — e=Uri(file:///c:/projects/cenas-umbraco-dotnet/cenas.web/assets/scripts/services/account/addresses.js)
[2019-11-12 18:59:39:395] [6] GitService.getRepository — e=Uri(file:///c:/projects/cenas-umbraco-dotnet/cenas.web/assets/scripts/services/account/addresses.js), t={"skipCacheUpdate":true}
[2019-11-12 18:59:39:396] [7] LineAnnotationController.resume
[2019-11-12 18:59:39:396] [7] LineAnnotationController.resume completed • 0 ms
[2019-11-12 18:59:39:396] [8] LineAnnotationController.refresh
[2019-11-12 18:59:39:396] [9] LineAnnotationController.clear
[2019-11-12 18:59:39:396] [9] LineAnnotationController.clear completed • 0 ms
[2019-11-12 18:59:39:406] GitLens (v10.1.2) activated • 404 ms
[2019-11-12 18:59:39:406] [8] LineAnnotationController.refresh completed • Skipped because there is no valid editor or no valid lines • 10 ms
[2019-11-12 18:59:39:408] [a] LineAnnotationController.onActiveLinesChanged — e=editor=file:///c:/projects/cenas-umbraco-dotnet/cenas.web/assets/scripts/services/account/addresses.js, lines=undefined, pending=true, reason=editor
[2019-11-12 18:59:39:408] [b] LineAnnotationController.clear
[2019-11-12 18:59:39:408] [b] LineAnnotationController.clear completed • 0 ms
[2019-11-12 18:59:39:408] [a] LineAnnotationController.onActiveLinesChanged completed • 0 ms
[2019-11-12 18:59:39:574] [c:\projects\cenas-umbraco-dotnet\cenas.web] git rev-parse --show-toplevel • 192 ms 
[2019-11-12 18:59:39:575] [3] GitService.repositorySearch(c:\projects\cenas-umbraco-dotnet\cenas.web) found root repository in 'c:/projects/cenas-umbraco-dotnet'
[2019-11-12 18:59:39:577] [c] GitService.repositorySearchCore — e=c:\projects\cenas-umbraco-dotnet\cenas.web, t=1
[2019-11-12 18:59:39:581] [d] GitService.repositorySearchCore — e=c:\projects\cenas-umbraco-dotnet\cenas.web\.vscode, t=0
[2019-11-12 18:59:39:581] [d] GitService.repositorySearchCore completed • 0 ms
[2019-11-12 18:59:39:581] [e] GitService.repositorySearchCore — e=c:\projects\cenas-umbraco-dotnet\cenas.web\App_Browsers, t=0
[2019-11-12 18:59:39:581] [e] GitService.repositorySearchCore completed • 0 ms
[2019-11-12 18:59:39:581] [f] GitService.repositorySearchCore — e=c:\projects\cenas-umbraco-dotnet\cenas.web\App_Code, t=0
[2019-11-12 18:59:39:581] [f] GitService.repositorySearchCore completed • 0 ms
[2019-11-12 18:59:39:581] [10] GitService.repositorySearchCore — e=c:\projects\cenas-umbraco-dotnet\cenas.web\App_Data, t=0
[2019-11-12 18:59:39:582] [10] GitService.repositorySearchCore completed • 0 ms
[2019-11-12 18:59:39:582] [11] GitService.repositorySearchCore — e=c:\projects\cenas-umbraco-dotnet\cenas.web\App_Plugins, t=0
[2019-11-12 18:59:39:582] [11] GitService.repositorySearchCore completed • 0 ms
[2019-11-12 18:59:39:582] [12] GitService.repositorySearchCore — e=c:\projects\cenas-umbraco-dotnet\cenas.web\App_Start, t=0
[2019-11-12 18:59:39:582] [12] GitService.repositorySearchCore completed • 0 ms
[2019-11-12 18:59:39:582] [13] GitService.repositorySearchCore — e=c:\projects\cenas-umbraco-dotnet\cenas.web\assets, t=0
[2019-11-12 18:59:39:582] [13] GitService.repositorySearchCore completed • 0 ms
[2019-11-12 18:59:39:582] [14] GitService.repositorySearchCore — e=c:\projects\cenas-umbraco-dotnet\cenas.web\batchFiles, t=0
[2019-11-12 18:59:39:582] [14] GitService.repositorySearchCore completed • 0 ms
[2019-11-12 18:59:39:582] [15] GitService.repositorySearchCore — e=c:\projects\cenas-umbraco-dotnet\cenas.web\build, t=0
[2019-11-12 18:59:39:582] [15] GitService.repositorySearchCore completed • 0 ms
[2019-11-12 18:59:39:582] [16] GitService.repositorySearchCore — e=c:\projects\cenas-umbraco-dotnet\cenas.web\config, t=0
[2019-11-12 18:59:39:583] [16] GitService.repositorySearchCore completed • 0 ms
[2019-11-12 18:59:39:583] [17] GitService.repositorySearchCore — e=c:\projects\cenas-umbraco-dotnet\cenas.web\Content, t=0
[2019-11-12 18:59:39:583] [17] GitService.repositorySearchCore completed • 0 ms
[2019-11-12 18:59:39:583] [18] GitService.repositorySearchCore — e=c:\projects\cenas-umbraco-dotnet\cenas.web\Controllers, t=0
[2019-11-12 18:59:39:583] [18] GitService.repositorySearchCore completed • 0 ms
[2019-11-12 18:59:39:583] [19] GitService.repositorySearchCore — e=c:\projects\cenas-umbraco-dotnet\cenas.web\css, t=0
[2019-11-12 18:59:39:583] [19] GitService.repositorySearchCore completed • 0 ms
[2019-11-12 18:59:39:583] [1a] GitService.repositorySearchCore — e=c:\projects\cenas-umbraco-dotnet\cenas.web\dis, t=0
[2019-11-12 18:59:39:583] [1a] GitService.repositorySearchCore completed • 0 ms
[2019-11-12 18:59:39:583] [1b] GitService.repositorySearchCore — e=c:\projects\cenas-umbraco-dotnet\cenas.web\dist, t=0
[2019-11-12 18:59:39:583] [1b] GitService.repositorySearchCore completed • 0 ms
[2019-11-12 18:59:39:583] [1c] GitService.repositorySearchCore — e=c:\projects\cenas-umbraco-dotnet\cenas.web\fonts, t=0
[2019-11-12 18:59:39:584] [1c] GitService.repositorySearchCore completed • 0 ms
[2019-11-12 18:59:39:584] [1d] GitService.repositorySearchCore — e=c:\projects\cenas-umbraco-dotnet\cenas.web\Media, t=0
[2019-11-12 18:59:39:584] [1d] GitService.repositorySearchCore completed • 0 ms
[2019-11-12 18:59:39:584] [1e] GitService.repositorySearchCore — e=c:\projects\cenas-umbraco-dotnet\cenas.web\Properties, t=0
[2019-11-12 18:59:39:584] [1e] GitService.repositorySearchCore completed • 0 ms
[2019-11-12 18:59:39:584] [1f] GitService.repositorySearchCore — e=c:\projects\cenas-umbraco-dotnet\cenas.web\Resources, t=0
[2019-11-12 18:59:39:584] [1f] GitService.repositorySearchCore completed • 0 ms
[2019-11-12 18:59:39:584] [20] GitService.repositorySearchCore — e=c:\projects\cenas-umbraco-dotnet\cenas.web\Scripts, t=0
[2019-11-12 18:59:39:584] [20] GitService.repositorySearchCore completed • 0 ms
[2019-11-12 18:59:39:584] [21] GitService.repositorySearchCore — e=c:\projects\cenas-umbraco-dotnet\cenas.web\SQLFiles, t=0
[2019-11-12 18:59:39:584] [21] GitService.repositorySearchCore completed • 0 ms
[2019-11-12 18:59:39:584] [22] GitService.repositorySearchCore — e=c:\projects\cenas-umbraco-dotnet\cenas.web\static, t=0
[2019-11-12 18:59:39:584] [22] GitService.repositorySearchCore completed • 0 ms
[2019-11-12 18:59:39:584] [23] GitService.repositorySearchCore — e=c:\projects\cenas-umbraco-dotnet\cenas.web\Umbraco, t=0
[2019-11-12 18:59:39:585] [23] GitService.repositorySearchCore completed • 0 ms
[2019-11-12 18:59:39:585] [24] GitService.repositorySearchCore — e=c:\projects\cenas-umbraco-dotnet\cenas.web\Umbraco_Client, t=0
[2019-11-12 18:59:39:585] [24] GitService.repositorySearchCore completed • 0 ms
[2019-11-12 18:59:39:585] [25] GitService.repositorySearchCore — e=c:\projects\cenas-umbraco-dotnet\cenas.web\uSync, t=0
[2019-11-12 18:59:39:585] [25] GitService.repositorySearchCore completed • 0 ms
[2019-11-12 18:59:39:585] [26] GitService.repositorySearchCore — e=c:\projects\cenas-umbraco-dotnet\cenas.web\Views, t=0
[2019-11-12 18:59:39:585] [26] GitService.repositorySearchCore completed • 0 ms
[2019-11-12 18:59:39:585] [c] GitService.repositorySearchCore completed • 7 ms
[2019-11-12 18:59:39:585] [3] GitService.repositorySearch(c:\projects\cenas-umbraco-dotnet\cenas.web) returned 1 repositories (c:/projects/cenas-umbraco-dotnet) • 202 ms
[2019-11-12 18:59:39:655] [c:/projects/cenas-umbraco-dotnet] git remote -v • 68 ms 
[2019-11-12 18:59:39:656] [27] GitRemoteParser.parse completed • 0 ms
[2019-11-12 18:59:39:724] [c:/projects/cenas-umbraco-dotnet] git ls-files -- cenas.web/assets/scripts/services/account/addresses.js • 66 ms 
[2019-11-12 18:59:39:724] [28] GitService.isTracked returned false • 67 ms — e=c:\projects\cenas-umbraco-dotnet\cenas.web\assets\scripts\services\account\addresses.js, t=c:/projects/cenas-umbraco-dotnet, i={"skipCacheUpdate":true}
[2019-11-12 18:59:39:724] [6] GitService.getRepository returned undefined • 329 ms
[2019-11-12 18:59:39:789] [29] FileHistoryTrackerNode.onVisibilityChanged — e={"visible":true}
[2019-11-12 18:59:39:789] [2a] FileHistoryTrackerNode.ensureSubscription
[2019-11-12 18:59:39:789] [2b] FileHistoryTrackerNode.subscribe
[2019-11-12 18:59:39:789] [2b] FileHistoryTrackerNode.subscribe completed • 0 ms
[2019-11-12 18:59:39:789] [2c] FileHistoryTrackerNode.triggerChange
[2019-11-12 18:59:39:789] [2d] FileHistoryView.refreshNode — e=FileHistoryTrackerNode, t=false
[2019-11-12 18:59:39:789] [2e] FileHistoryTrackerNode.refresh — false
[2019-11-12 18:59:39:790] [2f] GitUri.fromUri — e=Uri(file:///c:/projects/cenas-umbraco-dotnet/cenas.web/assets/scripts/services/account/addresses.js)
[2019-11-12 18:59:39:790] [30] GitService.getRepoPath — e=Uri(file:///c:/projects/cenas-umbraco-dotnet/cenas.web/assets/scripts/services/account/addresses.js)
[2019-11-12 18:59:39:790] [31] GitService.getRepository — e=Uri(file:///c:/projects/cenas-umbraco-dotnet/cenas.web/assets/scripts/services/account/addresses.js), t={"skipCacheUpdate":true}
[2019-11-12 18:59:39:790] [29] FileHistoryTrackerNode.onVisibilityChanged completed • 0 ms
[2019-11-12 18:59:39:796] [2a] FileHistoryTrackerNode.ensureSubscription completed • 6 ms
[2019-11-12 18:59:39:802] [c:\projects\cenas-umbraco-dotnet\cenas.web\assets\scripts\services\account] git rev-parse --show-toplevel • 77 ms 
[2019-11-12 18:59:39:802] [5] GitService.getRepoPath returned c:/projects/cenas-umbraco-dotnet • 407 ms
[2019-11-12 18:59:39:802] [4] GitUri.fromUri returned GitUri(file:///c:/projects/cenas-umbraco-dotnet/cenas.web/assets/scripts/services/account/addresses.js repoPath=c:/projects/cenas-umbraco-dotnet) • 407 ms
[2019-11-12 18:59:39:802] [33] GitService.getRepository — e=GitUri(file:///c:/projects/cenas-umbraco-dotnet/cenas.web/assets/scripts/services/account/addresses.js repoPath=c:/projects/cenas-umbraco-dotnet)
[2019-11-12 18:59:39:803] [33] GitService.getRepository returned c:/projects/cenas-umbraco-dotnet • 0 ms
[2019-11-12 18:59:39:865] [c:/projects/cenas-umbraco-dotnet] git ls-files -- cenas.web/assets/scripts/services/account/addresses.js • 74 ms 
[2019-11-12 18:59:39:865] [32] GitService.isTracked returned false • 75 ms — e=c:\projects\cenas-umbraco-dotnet\cenas.web\assets\scripts\services\account\addresses.js, t=c:/projects/cenas-umbraco-dotnet, i={"skipCacheUpdate":true}
[2019-11-12 18:59:39:865] [31] GitService.getRepository returned undefined • 75 ms
[2019-11-12 18:59:39:873] [c:/projects/cenas-umbraco-dotnet] git ls-files -- c:\projects\cenas-umbraco-dotnet\cenas.web\assets\scripts\services\account\addresses.js • 70 ms 
[2019-11-12 18:59:39:873] [34] GitService.isTracked returned false • 70 ms — e=GitUri(file:///c:/projects/cenas-umbraco-dotnet/cenas.web/assets/scripts/services/account/addresses.js repoPath=c:/projects/cenas-umbraco-dotnet)
[2019-11-12 18:59:39:873] [35] LineAnnotationController.onActiveLinesChanged — e=editor=file:///c:/projects/cenas-umbraco-dotnet/cenas.web/assets/scripts/services/account/addresses.js, lines=undefined, pending=false, reason=editor
[2019-11-12 18:59:39:873] [36] LineAnnotationController.clear
[2019-11-12 18:59:39:873] [36] LineAnnotationController.clear completed • 0 ms
[2019-11-12 18:59:39:873] [35] LineAnnotationController.onActiveLinesChanged completed • 0 ms
[2019-11-12 18:59:39:929] [c:\projects\cenas-umbraco-dotnet\cenas.web\assets\scripts\services\account] git rev-parse --show-toplevel • 63 ms 
[2019-11-12 18:59:39:929] [30] GitService.getRepoPath returned c:/projects/cenas-umbraco-dotnet • 139 ms
[2019-11-12 18:59:39:929] [2f] GitUri.fromUri returned GitUri(file:///c:/projects/cenas-umbraco-dotnet/cenas.web/assets/scripts/services/account/addresses.js repoPath=c:/projects/cenas-umbraco-dotnet) • 139 ms
[2019-11-12 18:59:39:929] [37] FileHistoryTrackerNode.resetChild
[2019-11-12 18:59:39:929] [37] FileHistoryTrackerNode.resetChild completed • 0 ms
[2019-11-12 18:59:39:929] [2e] FileHistoryTrackerNode.refresh returned false, uri=GitUri(file:///c:/projects/cenas-umbraco-dotnet/cenas.web/assets/scripts/services/account/addresses.js repoPath=c:/projects/cenas-umbraco-dotnet) • 139 ms
[2019-11-12 18:59:39:929] [38] FileHistoryView.triggerNodeChange — e=FileHistoryTrackerNode
[2019-11-12 18:59:39:930] [38] FileHistoryView.triggerNodeChange completed • 0 ms
[2019-11-12 18:59:39:930] [2d] FileHistoryView.refreshNode completed • 140 ms
[2019-11-12 18:59:39:930] [2c] FileHistoryTrackerNode.triggerChange completed • 140 ms
[2019-11-12 18:59:40:133] [39] FileHistoryNode.ensureSubscription
[2019-11-12 18:59:40:133] [3a] FileHistoryNode.subscribe
[2019-11-12 18:59:40:133] [3b] GitService.getRepository — e=GitUri(file:///c:/projects/cenas-umbraco-dotnet/cenas.web/assets/scripts/services/account/addresses.js repoPath=c:/projects/cenas-umbraco-dotnet)
[2019-11-12 18:59:40:134] [3b] GitService.getRepository returned c:/projects/cenas-umbraco-dotnet • 0 ms
[2019-11-12 18:59:40:134] [3a] FileHistoryNode.subscribe completed • 0 ms
[2019-11-12 18:59:40:134] [39] FileHistoryNode.ensureSubscription completed • 0 ms
[2019-11-12 18:59:40:135] [3c] GitService.getStatusForFile — e=c:/projects/cenas-umbraco-dotnet, t=c:\projects\cenas-umbraco-dotnet\cenas.web\assets\scripts\services\account\addresses.js
[2019-11-12 18:59:40:214] [c:/projects/cenas-umbraco-dotnet] git status --porcelain=v2 --find-renames= -- cenas.web/assets/scripts/services/account/addresses.js • 78 ms 
[2019-11-12 18:59:40:215] [3d] GitStatusParser.parse completed • 0 ms
[2019-11-12 18:59:40:215] [3c] GitService.getStatusForFile completed • 79 ms
[2019-11-12 18:59:40:215] [3e] GitService.getLogForFile — e=c:/projects/cenas-umbraco-dotnet, t=c:\projects\cenas-umbraco-dotnet\cenas.web\assets\scripts\services\account\addresses.js, i={}
[2019-11-12 18:59:40:215] [3e] GitService.getLogForFile Cache miss: 'log:n200:follow'
[2019-11-12 18:59:40:215] [3e] GitService.getLogForFile Cache add: 'log:n200:follow'
[2019-11-12 18:59:40:216] [3f] GitService.isTracked returned false • 0 ms — e=c:\projects\cenas-umbraco-dotnet\cenas.web\assets\scripts\services\account\addresses.js, t=c:/projects/cenas-umbraco-dotnet, i={}
[2019-11-12 18:59:40:216] [3e] GitService.getLogForFile Skipping log; 'c:\projects\cenas-umbraco-dotnet\cenas.web\assets\scripts\services\account\addresses.js' is not tracked
[2019-11-12 18:59:40:216] [3e] GitService.getLogForFile completed • 0 ms
[2019-11-12 18:59:44:923] [40] FileHistoryTrackerNode.onActiveEditorChanged
[2019-11-12 18:59:44:923] [41] FileHistoryTrackerNode.triggerChange
[2019-11-12 18:59:44:923] [42] FileHistoryView.refreshNode — e=FileHistoryTrackerNode, t=false
[2019-11-12 18:59:44:923] [43] FileHistoryTrackerNode.refresh — false
[2019-11-12 18:59:44:923] [40] FileHistoryTrackerNode.onActiveEditorChanged completed • 0 ms
[2019-11-12 18:59:44:923] [43] FileHistoryTrackerNode.refresh returned true • 0 ms
[2019-11-12 18:59:44:923] [42] FileHistoryView.refreshNode completed • 0 ms
[2019-11-12 18:59:44:923] [41] FileHistoryTrackerNode.triggerChange completed • 0 ms
[2019-11-12 18:59:47:732] [44] FileHistoryTrackerNode.onActiveEditorChanged
[2019-11-12 18:59:47:732] [45] FileHistoryTrackerNode.triggerChange
[2019-11-12 18:59:47:732] [46] FileHistoryView.refreshNode — e=FileHistoryTrackerNode, t=false
[2019-11-12 18:59:47:732] [47] FileHistoryTrackerNode.refresh — false
[2019-11-12 18:59:47:732] [44] FileHistoryTrackerNode.onActiveEditorChanged completed • 0 ms
[2019-11-12 18:59:47:732] [47] FileHistoryTrackerNode.refresh returned true • 0 ms
[2019-11-12 18:59:47:732] [46] FileHistoryView.refreshNode completed • 0 ms
[2019-11-12 18:59:47:732] [45] FileHistoryTrackerNode.triggerChange completed • 0 ms

```
