### ISSUE TITLE
FEATURE: Settings option to remove "origin/" from git commands via Terminal Window

### ISSUE THREAD

**Issue by jmb-mage** [eamodio/vscode-gitlens#515] opened 2018-09-26 13:28 UTC
via Terminal Window commands for operations like "Checkout Branch (via Terminal)" are including "origin/" in the command when that is not necessary.
`git checkout origin/1.8/dev`
instead of what I want
`git checkout 1.8/dev`

**Describe the feature you'd like.** 
GitLen setting to remove origin from those commands?

_apologies if this exists already, great product BTW!_

**Comment by eamodio** [comment] 2018-09-28 03:14
Why do you want that removed? It avoid any possible ambiguity that might come from the specific usage.

**Comment by jmb-mage** [comment] 2018-09-28 15:04
I'm not the greatest expert in git but when I am using GitLens commands via Terminal in VS Code I get two different things.  
```
PS C:\dev\project1> git checkout origin/1.8/dev
Note: checking out 'origin/1.8/dev'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at acdbda8f Merge pull request #271 from project1/1.8/commit123
```
versus the same command without "origin/"
```
PS C:\dev\project1> git checkout 1.8/dev
Switched to branch '1.8/dev'
Your branch is up to date with 'origin/1.8/dev'.
```

That what happens if the branch 1.8/dev exists.  If it's a new branch, then VS Code thinks the branch name is a GUID unless I take the "origin/" out of the git commands.

**Comment by eamodio** [comment] 2018-09-28 15:41
Right -- damn, sorry about that. Will get that fixed up!

**Comment by eamodio** [comment] 2019-01-03 07:17
I am closing this issue because it has not had recent activity and I believe this is behaving as designed.

**Closed by eamodio** 2019-01-03 07:17 UTC
Labels: needs more info
