### ISSUE TITLE
Can't create new file and directory

### ISSUE THREAD

**Issue by yumen-s** [eamodio/vscode-gitlens#753] opened 2019-05-23 07:57 UTC
- GitLens Version: 9.8.0
  
- VSCode Version: 1.33.1
- OS Version: macOS 10.14.3

Steps to Reproduce:

1. Open a project by VSCode.
1. Create a new file immediately(aboud 0 to 1 second?).
1. The operation is canceled.

![movie](https://user-images.githubusercontent.com/20495704/58235128-25caae00-7d7b-11e9-8fd0-a0166c896569.gif)

When I disable GitLens, the problem doesn't occur.
Maybe GitLens is not the cause...

**Comment by eamodio** [comment] 2019-05-23 17:22
@yumen-s this is a duplicate of #726 and unfortunately is a bug in VS Code itself. Reported here: https://github.com/microsoft/vscode/issues/74218

**Closed by eamodio** 2019-05-23 17:22 UTC

**Comment by yumen-s** [comment] 2019-05-24 00:07
@eamodio thanks!
