### ISSUE TITLE
Compare file differences between branches

### ISSUE THREAD

**Issue by kayrunm** [eamodio/vscode-gitlens#1161] opened 2020-11-16 09:35 UTC
Since the new version (v11) I can't seem to just compare differences between files on different branches, rather than the behind/ahead in the new sidebar. Is there any way to get this comparison back? 

An example of the functionality I'm missing is seen in this screenshot; the "1 file changed" bit.

![image](https://user-images.githubusercontent.com/4512646/99237164-07b70000-27f0-11eb-9e97-12526da1120c.png)

**Comment by wwarby** [comment] 2020-11-16 13:32
I have the same issue. I have a project in which I have two branches that diverged from one another some time ago and will never come back together, but in which I need to be able to see the differences. Before the update I was able to see a list of 20 or so files that were different between branches - now when I compare the branches I see dozens of commits in "Ahead" and Behind" but no file differences. I was utterly reliant on this functionality to manage my project and need to go looking now for a way to downgrade the extension until I can come up with another way of doing things.

**Comment by kayrunm** [comment] 2020-11-16 13:34
Yup, largely in the same boat. Looking at merging three repos for what is largely the same codebase into one, so commits are never going to be the same.

@wwarby thankfully if you go to the Extensions sidebar on VS Code you should be able to click the cog icon for GitLens and then select `Install Another Version...` — I just downgraded to the most recent version before v11.

**Comment by wwarby** [comment] 2020-11-16 14:01
That's @kayrunm I found that option just after I posted. At least that turned out to be an easy fix and I'll still with version 10.x until I have a viable alternative. Never occurred to me how vitally important that feature is to my workflow until it disappeared!

**Comment by Celeborn2BeAlive** [comment] 2020-11-17 00:59
Related #1157

**Comment by BRaimbault** [comment] 2020-11-17 15:41
Same situation here, I chose to roll back to 10.2.3 to get the old "Compare Commits" comparing to branches of my choice focusing on differences between files instead of commits history.

**Comment by justin-databased** [comment] 2020-11-17 16:02
I am a little surprised at how few people are in commenting on this haha. This is the only thing that I use Git Lens for. I am chuckling about it now that I installed the previous version but I was swearing like a sailor just about 10 minutes ago. :facepalm:

**Comment by aramando** [comment] 2020-11-17 18:28
I have this issue too when comparing a branch to master, but it seems to be caused by the branch having been squash-merged to master, then the merge commit reverted; the changes made on the branch _before_ the merge+revert on master are the ones not showing in the GitLens reference comparison, although the files themselves are showing as changed, it's just the diff doesn't show any changes. An equivalent file comparison or PR in Github correctly shows all the changes.

**Comment by finn-wa** [comment] 2020-11-17 20:13
I don't mind the *Behind/Ahead* view and I can imagine it being occasionally useful, but we definitely need a diff view back too. When I'm comparing my local branch to origin, the compare view basically duplicates the new *Changes to push/pull* section now.
![image](https://user-images.githubusercontent.com/18408811/99442370-28ad5b80-297e-11eb-9bd8-c690cae4fba8.png)
I will probably be downgrading to v10 to get this feature back, which is shame because overall v11 seems really nice!

**Comment by Zmaon** [comment] 2020-11-19 10:18
Same here, I use to do most of my code review using this feature. I had to install 10.x for now.

**Comment by mfornet** [comment] 2020-11-19 21:53
I have same issue, and would love if we have by default file diff between branches rather than `Behind` / `Ahead`.

For those struggling with this, a workaround I found (hopefully temporary) is creating a separate branch and squashing all commits, so all differences are shown on that commit (inside `Ahead`).

**Closed** 2020-11-23 03:44 UTC
Labels: type: question

**Comment by eamodio** [comment] 2020-11-23 07:24
Sorry for unintentionally removing this feature 🤦‍♂️. In v11.0.4 I've added back the ability to compare file changes between the references (regardless of ahead/behind).

**Comment by Psithief** [comment] 2020-11-23 10:39
The files are back, but the "new" and "old" sides of the compare are backwards compared to differences in the "Ahead" commits.

**Comment by eamodio** [comment] 2020-11-23 17:18
@Psithief Damn it -- that's what I get for rushing it out without thorough testing. A fix is coming shortly.
