### ISSUE TITLE
Duplicated directory names in commit preview

### ISSUE THREAD

**Issue by nbozhinov** [eamodio/vscode-gitlens#769] opened 2019-06-21 17:24 UTC
Previewing a commit in the "repositories view" sometimes duplicates the names of some directories when showing the changed files so instead of "repo/dir1/dir2/dir3" I see "repo/dir1/dir2/dir2/dir3" which is a nonexistent path.

GitLens version: 9.8.2
VS Code version: 1.34.0
OS: Ubuntu 16.04 LTS

**Comment by eamodio** [comment] 2019-07-09 20:41
@nbozhinov are there symlinks at play here? 
Can you please enable output channel logging by setting `"gitlens.outputLevel": "debug"` in your `settings.json`. This will enable logging to the *GitLens* channel in the *Output* pane. Once enabled, please reproduce the issue (if possible) and attach the log lines from the *GitLens* channel.

**Comment by nbozhinov** [comment] 2019-07-15 12:21
@eamodio no there are no symlinks in the paths that show this problem.
I've enabled the debug logging an am attaching the output from when the problem appeared. I've renamed my user and the project name due to company policy, but structure of the paths is preserved.
[gitlens_debug_output.txt](https://github.com/eamodio/vscode-gitlens/files/3392210/gitlens_debug_output.txt)

**Comment by eamodio** [comment] 2019-07-23 05:09
@nbozhinov First is this still happening with v9.9.1? If so, in that log what paths would get duplicated? You mentioned that it "sometimes" happens -- it is at least consistent with the same files? Or any other details that you can tell me to help see it?

**Comment by nbozhinov** [comment] 2019-07-23 15:49
@eamodio yes it still happens with v9.9.1. It appears to be consistent with the same directory, but happens only on some commits, on others with the same files edited it appear normally. Also the problematic commit appears properly when viewed in GitLab.
The broken file path looks like this:
![Screenshot from 2019-07-23 18-21-07](https://user-images.githubusercontent.com/17404553/61726142-cd635d00-ad79-11e9-9b57-9d4d5b773645.png)
The directory "arch" should appear only once. This is in the "repositories" panel when previewing the current branch. This commit has been amended if this is of any relevance.
I am attaching the log from when the screenshot was taken, but it still doesn't mention this directory at all.
[gitlens_debug.txt](https://github.com/eamodio/vscode-gitlens/files/3422911/gitlens_debug.txt)

**Comment by eamodio** [comment] 2019-07-25 06:03
Can you provide the output of the following git command, replacing `<your-commit-id-here>` with the sha of a commit that shows this file issue?

```
git log --name-status --format="%x3c%x2ff%x3e%n%x3cr%x3e%x20%H%n%x3ca%x3e%x20%aN%n%x3ce%x3e%x20%aE%n%x3cd%x3e%x20%at%n%x3cc%x3e%x20%ct%n%x3cp%x3e%x20%P%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e%n%x3cf%x3e" -n1 -m -M <your-commit-id-here>
```

**Comment by eamodio** [comment] 2019-09-24 05:57
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!

**Closed** 2019-10-06 06:50 UTC
Labels: type: bug
