### ISSUE TITLE
I got stuck when i commit my change

### ISSUE THREAD

**Issue by ChangeHow** [eamodio/vscode-gitlens#1331] opened 2021-01-18 08:31 UTC
- GitLens Version: 11.1.3
- Git Version: 2.21.0

- VSCode Version: 1.52.1
- OS Version: 11.2 Beta

Steps to Reproduce:

1. change something
2. click Gitlens and input something like: `fix(xxx): 更新abc`
3. you may get stuck after doing steps above all, and then Gitlens would run like image below
4. if you doing steps above, but not get stuck, try use input source chinese first and then change source into english
    
![image](https://user-images.githubusercontent.com/23733347/104889169-c3d7a700-59a8-11eb-8dbb-3ff605107289.png)
(It's like stucked in `compositionupdate`)

I don't know this bug belong to whether VSCode or Gitlens, so i report bugs in [here](https://github.com/microsoft/vscode/issues/114517) too.

**Comment by eamodio** [comment] 2021-01-18 08:36
This is an issue in VS Code and is a duplicate of https://github.com/microsoft/vscode/issues/112621 -- which is fixed in the current insiders builds and will be released in the next stable build.

**Closed by eamodio** 2021-01-18 08:36 UTC
Labels: potential-bug, triage
