### ISSUE TITLE
Command GIT failes after update (11.0.6->11.1.0)

### ISSUE THREAD

**Issue by pcluteijn** [eamodio/vscode-gitlens#1301] opened 2020-12-30 14:03 UTC
- GitLens Version: 11.1.0
- Git Version: 2.11.0 (Raspbian9)
- VSCode Version: 1.52.1
- OS Version: Windows 10 (with ssh-terminal connected to Raspberry Pi B 3 running Rasbian OS 9 Stretch)

Steps to Reproduce:

1. After update from 11.0.6 to 11.1.0 the following error is given repetitively.

```
Command` failed: /usr/bin/git -c core.quotepath=false -c color.ui=false tag -l --format=%3cn%3e%(refname)%3cr%3e%(if)%(*objectname)%(then)%(*objectname)%(else)%(objectname)%(end)%3cd%3e%(creatordate:iso8601)%3cad%3e%(authordate:iso8601)%3cs%3e%(subject)
fatal: unknown field name: `if
```

2. Push to origin master fails, only works though cli.

3. Rolling the update back to 11.0.6 "solves" this error.

**Comment by BigPackie** [comment] 2020-12-30 14:28
Exactly the same issue here. Pushing actually works, even though the error pops up. What did not work for me though was trying to expand  branches and view their commit history.

**Comment by eamodio** [comment] 2020-12-31 06:31
Duplicate of https://github.com/eamodio/vscode-gitlens/issues/1294

**Closed by eamodio** 2020-12-31 06:31 UTC
Labels: bug, duplicate
