### ISSUE TITLE
Line wrap doesn't respect file blame annotations

### ISSUE THREAD

**Issue by Qinusty** [eamodio/vscode-gitlens#495] opened 2018-09-05 10:59 UTC
- GitLens Version: 8.5.6

- VSCode Version: 1.26.1
- OS Version: Debian 9.6

Steps to Reproduce:

1. Create a file "file.md"
2. Ensure `editor.wordWrap` is set to `on` in your settings.
3. Create a line which wraps 3/4 times.
4. `git init && git add file.md && git commit -m "test"`
5. Toggle File blame annotations on
6. Observe.

You will see that the wrapped lines ignore the section on the left for the blame annotations and do not indent as the unwrapped lines do.

**Comment by eamodio** [comment] 2018-09-30 04:44
Duplicate of #443

**Closed by eamodio** 2018-09-30 04:44 UTC
Labels: duplicate

**Comment by scott-vsi** [comment] 2020-03-05 18:40
Sorry to comment on a closed issue, but this may not be a duplicate. Qinusty is referring to toggling _file_ blame annotations. The other issue is referring to _line_ annotations. 

If you toggle file blame annotations with word wrap on, then a long line will wrap into the left column that is used to list the blame annotations.

**Comment by eamodio** [comment] 2020-03-06 07:13
They are the same underlying VS Code issue unfortunately.
