### ISSUE TITLE
OUTLINE windows not work with gitlens when I opened python files.

### ISSUE THREAD

**Issue by Exlsunshine** [eamodio/vscode-gitlens#637] opened 2019-01-25 07:56 UTC
- GitLens Version: 9.4.1
  
- VSCode Version: 

Version: 1.30.2 (user setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17763

- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Enable gitlens plugin
2. Open a python file.
3. You will find the OUTLINE window does not work as expected.

**Comment by eamodio** [comment] 2019-11-11 20:09
Duplicate of https://github.com/eamodio/vscode-gitlens/issues/439

**Closed by eamodio** 2019-11-11 20:09 UTC
Labels: status: duplicate
