### ISSUE TITLE
How to switch off notification about connection to Github?

### ISSUE THREAD

**Issue by insolor** [eamodio/vscode-gitlens#1256] opened 2020-12-10 09:53 UTC
I don't want to connect to github. How to switch off the notification which pops up every time I open a file from my github project?

VS Code version: 1.51.1
GitLens version: 11.0.6

![Screensho](https://user-images.githubusercontent.com/2442833/101755711-40dc4a80-3ae6-11eb-8471-baa2884a343a.png)

**Comment by eamodio** [comment] 2020-12-10 17:40
Duplicate of https://github.com/eamodio/vscode-gitlens/issues/1208

And the fix is currently available in the insiders edition (will be coming to stable soon). You can install the insiders edition from [here](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens-insiders). But be sure to disable/uninstall the stable version of GitLens first.

**Closed by eamodio** 2020-12-10 17:40 UTC
Labels: type: question

**Comment by insolor** [comment] 2020-12-10 17:44
Ok, thank you
