### ISSUE TITLE
Activity Bar: Gitlens button always moves itself to the bottom

### ISSUE THREAD

**Issue by vvs** [eamodio/vscode-gitlens#469] opened 2018-08-03 14:57 UTC
- VSCode Version:
Code - Insiders 1.26.0-insider (4fa62b246c4305b4ca00507551f77c58135ce928, 2018-08-03T12:32:37.823Z)
OS version: Windows_NT x64 10.0.17134
Gitlens version: 8.5.4

Steps to Reproduce:

1. Move GitLens button in the Activity Bar to any custom location. E.g., to the top of the Activity Bar.
2. Restart VS Code, the button appears in the correct location, but after some small delay, re-arranges itself to the very bottom of the Activity Bar.

My goal is to move the GitLens button close to the native 'Git' button, but I have re-arrange the button after every restart.

**Comment by eamodio** [comment] 2018-08-03 16:55
Duplicate of #447, see my comment here: https://github.com/eamodio/vscode-gitlens/issues/447#issuecomment-405651593

**Closed by eamodio** 2018-08-03 16:55 UTC
