### ISSUE TITLE
Can't fetch repositories

### ISSUE THREAD

**Issue by marvin46** [eamodio/vscode-gitlens#749] opened 2019-05-20 03:37 UTC
- GitLens Version: v.9.7.4
- VSCode Version: 1.34.0
- OS Version: Windows_NT x64 6.1.7601 (Windows 7 Profesional)

Steps to Reproduce:

1. just click on the fetch button (after pull button in side bar), and in the bottonm right, the notify just give information "Fetching my_repo_name" without give output succes or fail, it seriously make me confuse.

please fix it guys.

**Comment by eamodio** [comment] 2019-05-22 04:23
@marvin46
Can you please enable output channel logging by setting `"gitlens.outputLevel": "debug"` in your `settings.json`. This will enable logging to the *GitLens* channel in the *Output* pane. Once enabled, please reproduce the issue (if possible) and attach the log lines from the *GitLens* channel.

**Comment by marvin46** [comment] 2019-05-22 04:25
Oke i will tell you soon

Pada tanggal Rab, 22 Mei 2019 11.23, Eric Amodio <notifications@github.com>
menulis:

**Comment by marvin46** [comment] 2019-05-23 01:38
![error fetching](https://user-images.githubusercontent.com/27880394/58219715-170dd800-7d36-11e9-8465-7c3a556336b7.png)

thats the gitlens output,

**Comment by eamodio** [comment] 2019-06-05 15:51
@marvin46 I'm still not sure about what the issue is. When you start a fetch I show a progress notification while the fetch is running, and it goes away once it is complete. If there was an error or something during the fetch there should be another error notification.

**Comment by eamodio** [comment] 2019-07-09 20:50
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!

**Closed by eamodio** 2019-07-09 20:50 UTC
Labels: status: needs more info, type: potential bug
