### ISSUE TITLE
Some shortcuts override AZERTY special characters inserting

### ISSUE THREAD

**Issue by Haroenv** [eamodio/vscode-gitlens#186] opened 2017-10-30 11:03 UTC
- GitLens Version: 5.7.1
- VSCode Version: Version 1.18.0-insider (1.18.0-insider) aaec2980609a4bbe44d0cfe2d3f78c85cba1be83
- OS Version: macOS High Sierra 10.13 (17A405)

Steps to Reproduce:

1. Have an AZERTY keyboard 
2. Type `\` (<kbd>⌥</kbd><kbd>⇧</kbd><kbd>:</kbd>)
3. see that the commit search shows up instead of a backslash

```
{
  "command": "gitlens.showCommitSearch",
  "key": "shift+alt+[Period]",
  "when": "gitlens:enabled"
}
```

This happens because alt and alt-shift on Mac in AZERTY are used to enter special characters (for example `\,ß` that could be used in code)

**Comment by Haroenv** [comment] 2017-10-30 11:04
I manually disabled those, but could be nice to avoid this issue alltogether

**Comment by eamodio** [comment] 2017-10-30 14:29
Duplicate of https://github.com/eamodio/vscode-gitlens/issues/104. Please join the conversation there -- https://github.com/eamodio/vscode-gitlens/issues/104#issuecomment-335574528

**Closed by eamodio** 2017-10-30 14:29 UTC

**Comment by Haroenv** [comment] 2017-10-30 14:46
Thanks, didn't find that issue when searching
