### ISSUE TITLE
Hyperlink style leaks into blame annotation

### ISSUE THREAD

**Issue by donaldpipowitch** [eamodio/vscode-gitlens#181] opened 2017-10-27 06:29 UTC
- GitLens Version: 5.7.1
- VSCode Version: 1.17.2
- OS Version:

Steps to Reproduce:

1. Add a link somewhere in your code. _Nothing_ should follow the link on that line.
2. The blame annotation is now underlined :)

![image](https://user-images.githubusercontent.com/1152805/32090617-a432e982-baf0-11e7-9690-ce076b11fc2a.png)

---

Thank you for this extension 👍

**Comment by eamodio** [comment] 2017-10-27 19:14
Duplicate of https://github.com/eamodio/vscode-gitlens/issues/110

**Closed by eamodio** 2017-10-27 19:14 UTC

**Comment by donaldpipowitch** [comment] 2017-10-28 05:22
I'm sorry. I briefly searched for it, but couldn't found a issue. Thanks.
