### ISSUE TITLE
Hover fails to render when scrolled past start of Current Line Blame

### ISSUE THREAD

**Issue by Ollie-Saer-WBS** [eamodio/vscode-gitlens#788] opened 2019-07-11 09:42 UTC
- GitLens Version: 9.8.5
  
- VSCode Version: 1.36.1
- OS Version: Windows 10 Enterprise 1709 (Build 16299.1217)

Steps to Reproduce: 
![See Animated GIF](https://user-images.githubusercontent.com/42766020/61040368-536dc400-a3c8-11e9-8a4d-fb4f4e4ba615.gif)

**Comment by eamodio** [comment] 2019-07-16 20:34
Duplicate of #783

**Closed by eamodio** 2019-07-16 20:34 UTC
