### ISSUE TITLE
Merge using no fast forward (--no-ff)

### ISSUE THREAD

**Issue by shane-smith** [eamodio/vscode-gitlens#407] opened 2018-06-08 08:38 UTC
Issue Type: <b>Feature Request</b>

Could we have a configuration option, so that when we're performing a merge it defaults to including the no-fast-forward option?

![image](https://user-images.githubusercontent.com/943942/41147839-9898aa10-6b46-11e8-8dc1-f471d28f7ff1.png)

In this case, I am wanting to merge master into my current feature branch (to pull in the latest changes). It enters this into my terminal:

    git merge master

Our preference is to use no-fast-forward instead:

    git merge --no-ff master

At the moment, I need to manually update it each time.

I understand that this should probably be off by default, which is why I'm requesting a configuration option for this. Had a quick search and couldn't find one, so if it already exists, please let me know.

Thanks.

----

Extension version: 8.3.5
VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:30:30.113Z)
OS version: Darwin x64 17.5.0

**Comment by eamodio** [comment] 2018-12-03 14:02
@shane-smith would https://github.com/eamodio/vscode-gitlens/issues/561 solve this for you if you were able to always make the _Merge Branch (via Terminal)_ command be `--no-ff`?

**Comment by shane-smith** [comment] 2018-12-03 22:18
@eamodio - I suspect it would, yes.

**Comment by eamodio** [comment] 2018-12-04 00:45
Duplicate of #561

**Closed by eamodio** 2018-12-04 00:45 UTC
Labels: feature, needs more info
