### ISSUE TITLE
GitLens can't see the remote but git can

### ISSUE THREAD

**Issue by gbritton1** [eamodio/vscode-gitlens#649] opened 2019-02-07 18:03 UTC
![image](https://user-images.githubusercontent.com/12263288/52432563-b6d18e00-2ad8-11e9-89ef-3e1f4fe581a9.png)

**Comment by eamodio** [comment] 2019-02-18 22:38
What command are you executing to get that error? It looks like the error is coming from vscode itself (as GitLens uses some vscode commands for push/pull/fetch).

**Comment by gbritton1** [comment] 2019-02-18 23:10
Just wanted to do a pull

**Comment by gbritton1** [comment] 2019-02-18 23:10
Right click, pull

**Comment by eamodio** [comment] 2019-02-18 23:14
Hrm -- can you do a pull from the vscode Source Control side bar (under the ... menu) or via the command palette?

**Comment by gbritton1** [comment] 2019-02-19 01:05
Yeah that works fine

**Comment by eamodio** [comment] 2019-07-09 20:43
@gbritton1 is this still an issue?

**Comment by gbritton1** [comment] 2019-07-09 22:26
Yes

**Comment by BMBurstein** [comment] 2019-07-30 12:25
I am having a similar issue. gitlens only sees one of my 2 remotes:

![image](https://user-images.githubusercontent.com/1149432/62128919-2ed97d80-b2de-11e9-8300-08d3044feaf9.png)

**Comment by eamodio** [comment] 2019-07-30 14:51
Can you please enable output channel logging by setting `"gitlens.outputLevel": "debug"` in your `settings.json`. This will enable logging to the *GitLens* channel in the *Output* pane. Once enabled, please reproduce the issue (if possible) and attach the log lines from the *GitLens* channel.

**Comment by BMBurstein** [comment] 2019-07-30 19:45
From the GitLens channel:

```
[2019-07-30 19:39:59:258] [11c] RepositoriesView.refreshNode — e=RemotesNode(gitlens:repository(/homes/baruchb/work/B0004.00.4030):remotes), t=true
[2019-07-30 19:39:59:258] [11d] RepositoriesView.triggerNodeChange — e=RemotesNode(gitlens:repository(/homes/baruchb/work/B0004.00.4030):remotes)
[2019-07-30 19:39:59:258] [11d] RepositoriesView.triggerNodeChange completed • 0 ms
[2019-07-30 19:39:59:258] [11c] RepositoriesView.refreshNode completed • 0 ms
[2019-07-30 19:39:59:573] [/homes/baruchb/work/B0004.00.4030] git remote -v • 109 ms 
[2019-07-30 19:39:59:574] [11e] GitRemoteParser.parse completed • 0 ms
```

From the GitLens (git) channel:

```
[2019-07-30 19:39:59:573] [/homes/baruchb/work/B0004.00.4030] git remote -v • 109 ms 
```

**Comment by eamodio** [comment] 2019-07-30 19:51
@BMBurstein Thanks -- can you send me the output of `git remote -v `?

**Comment by BMBurstein** [comment] 2019-07-30 20:14
As much as I can share of it is in the image I posted. Here is a sample output. It is the same format as my real output.:

```
> git remote -v
origin  /home/user1/repos/B0004.02.4033 (fetch)
origin  /home/user1/repos/B0004.02.4033 (push)
radion  /home/user2/repos/B0004.02.4033/ (fetch)
radion  /home/user2/repos/B0004.02.4033/ (push)
```

As I am pasting and editing the above output I noticed that the remote that gitlens is ignoring has a trailing slash. I hadn't noticed that before. Related?

**Comment by eamodio** [comment] 2019-07-30 22:29
Thanks! I see the issue and will be fixed in the next release.

**Comment by eamodio** [comment] 2019-07-30 22:41
@gbritton1 I've moved your issue here: https://github.com/eamodio/vscode-gitlens/issues/807 (sorry about the confusion)

**Comment by BMBurstein** [comment] 2019-07-31 04:49
Thank you for the quick fix.
I'm sorry for hijacking the original thread. I thought the two were related.

**Comment by BMBurstein** [comment] 2019-07-31 07:38
I just found that in a different repo it is the other way round. The first remote listed in `git remote -v` has the trailing slash, and GitLens only lists that one. Is this the same issue? Does this fix fix this too?

**Comment by gbritton1** [comment] 2019-07-31 13:23
Problem resolved for me with latest version

**Comment by eamodio** [comment] 2019-07-31 14:56
@BMBurstein it should fix it either way. It really wasn't about the slash, but instead that the remote wasn't a http[s]/git/ssh url

**Closed** 2019-08-01 06:27 UTC
Labels: type: bug
