### ISSUE TITLE
unable to remove/disable on line hover gitblame option

### ISSUE THREAD

**Issue by mustafawm** [eamodio/vscode-gitlens#243] opened 2018-01-15 10:23 UTC
- GitLens Version: 7.5.1
- VSCode Version: 1.19.2
- OS Version: macOS 10.13

Can you please tell me how to disable online (on hover) gitblame details (like in the gif line 50) and only leave the status bar one.

![gitlens-preview](https://user-images.githubusercontent.com/13101565/34937734-fac06d3c-fa39-11e7-9b50-a02da8fe6ff6.gif)

**Comment by TimonVS** [comment] 2018-01-15 13:10
I'm having the same issue.

**Comment by mustafawm** [comment] 2018-01-15 13:26
Thanks for your comment, but that did not help in my case. I tried it before opening this issue.

**Comment by eamodio** [comment] 2018-01-15 14:08
So sorry -- will be putting out a release as soon as I get this fixed (should be soon --- just woke up)

**Comment by eamodio** [comment] 2018-01-15 14:09
Duplicate of https://github.com/eamodio/vscode-gitlens/issues/242
Please follow along on the that issue

**Comment by TimonVS** [comment] 2018-01-15 14:10
@eamodio No worries. Stuff like this can happen :). Thanks for making this amazing plugin!

**Closed** 2018-01-15 14:09 UTC
Labels: bug

**Comment by mustafawm** [comment] 2018-01-15 14:18
Good morning :) 
No worries mate, It's a tiny bug. I wouldn't have opened this one but wasn't quite sure that 242 was addressing the exact thing.

Thanks for awesome plugin. It's so smooth, I actually thought it comes with vscode by default.

**Comment by eamodio** [comment] 2018-01-15 15:53
Thank you all for your patience and kind words! GitLens 7.5.2 has been pushed to the marketplace and should resolve this issue. Please let me know if not. Again sorry for the inconvenience!

**Comment by eamodio** [comment] 2018-01-15 15:55
https://github.com/Microsoft/vscode/issues/15756 can't happen soon enough. Please upvote ;)

**Comment by mustafawm** [comment] 2018-01-17 23:53
Hi @eamodio I know this is not the most appropriate place to ask but I tried to figure out a way to go back to my old config of the plugin with _no luck_. 

Can you please tell me how to only show git blame on **status bar** (bottom)? and disable this (pic)
![screen shot 2018-01-18 at 10 44 07 am](https://user-images.githubusercontent.com/13101565/35073535-6d5eaaa2-fc3d-11e7-8fd3-95e4746cabf8.png)


current config
```
    "gitlens.blame.line.enabled": false,
    "gitlens.codeLens.authors.enabled": false,
    "gitlens.annotations.file.gutter.hover.details": false,
    "gitlens.annotations.line.hover.changes": false,
    "gitlens.annotations.line.trailing.hover.changes": false,
    "gitlens.annotations.file.gutter.hover.wholeLine": false,
    "gitlens.gitExplorer.gravatars": false,
    "gitlens.annotations.file.gutter.heatmap.enabled": false,

```

**Comment by eamodio** [comment] 2018-01-18 02:38
@mustafawm use the following:

```json
"gitlens.blame.line.enabled": false, // turns of the end of line or hover blame annotations
"gitlens.codeLens.enabled": false, // turns off the code lens
"gitlens.statusBar.enabled": true // turns on the status bar blame (on by default)
```
