### ISSUE TITLE
Open File in Remote and Copy Remote File URL do not work with GitHub Enterprise

### ISSUE THREAD

**Issue by jaywryan** [eamodio/vscode-gitlens#512] opened 2018-09-24 16:09 UTC
- GitLens Version: 8.5.6

- VSCode Version: 1.27.2
- OS Version: Win 10

Steps to Reproduce:

1.  Attempt to run either command from a GitHub Enterprise repository
2.  Contents doesn't get copied to your clipboard, or brower opened.  "Copy URL for <file> to Clipboard from..." appears in Command Pallet but nothing typed works and no suggestions loaded.

I am assuming that this has to do with authentication into GitHub Enterprise to query for the URL.  Another note is that we are using ssh not https for the remote url.

**Comment by eamodio** [comment] 2018-09-28 03:59
What does your remote url look like?

**Comment by sethetter** [comment] 2018-10-02 18:41
I'm also having this issue, however we do have an `https` url for the remote. It looks like `https://our.gh.enterprise.url.here/org/repo`, as you would expect.

When using "Open In Remote" I'm then presented with an input with the placeholder text `Open {filename} in...`. If I try to type anything here and hit enter, or any other combination, nothing happens.

**Comment by sethetter** [comment] 2018-10-02 19:05
That quick pick list is empty, and looking at the code it seems it should be providing me with a list of remote to choose from, must be a problem with getting the remote list.

**Comment by sethetter** [comment] 2018-10-02 19:58
Solved it -- I did not have the remote configured in `gitlens.remotes`.

```
"gitlens.remotes": [{ "domain": "git.corporate-url.com", "type": "GitHub" }]
```

[Found the docs](https://github.com/eamodio/vscode-gitlens#custom-remotes-settings)!

**Comment by eamodio** [comment] 2018-10-02 20:29
Hehe -- we could work on a PR that adds support for unknown remotes and allows configuring it to be added into the `gitlens.remotes`  😄 

FYI, if you are interested in a PR please make sure to target the `develop` branch as that will be the next version of GitLens.

**Comment by eamodio** [comment] 2019-01-08 05:45
I am closing this issue because I believe it is working as intended.

**Closed by eamodio** 2019-01-08 05:45 UTC
Labels: needs more info

**Comment by DeathPoem** [comment] 2020-04-29 03:44
> Solved it -- I did not have the remote configured in `gitlens.remotes`.
> 
> ```
> "gitlens.remotes": [{ "domain": "git.corporate-url.com", "type": "GitHub" }]
> ```
> 
> [Found the docs](https://github.com/eamodio/vscode-gitlens#custom-remotes-settings)!
> 
> Glad this works already, but I'm a little bummed, I thought this might be a good first hacktoberfest PR ;)

I solved this by the same method with some difficulties, so record my experience here in case someone need. My corporate using gitlab, so ```"type": "GitHub"```  doesn't work, ```"type": "GitLab"``` works.

**Comment by rshemant** [comment] 2020-07-20 01:37
> "gitlens.remotes": [{ "domain": "git.corporate-url.com", "type": "GitHub" }]

workd for me as well 👍 
![image](https://user-images.githubusercontent.com/49910052/87891469-5f7d6e80-ca7d-11ea-9ba0-057a64be1d61.png)
