### ISSUE TITLE
Gitlens cause vscode runs very slow

### ISSUE THREAD

**Issue by fuzihaofzh** [eamodio/vscode-gitlens#509] opened 2018-09-22 12:17 UTC
- GitLens Version: 8.5.6

- VSCode Version: 1.27.2
- OS Version: macOS 10.12.6

I do know that someone has submitted a similar issue (https://github.com/eamodio/vscode-gitlens/issues/367), but it has not been solved. I found this problem again. And I tried to reproduce the error. I guess it's incompatible with python extension.

Steps to Reproduce:

1. Disabled all extensions, only keep python, intellisense will work.
2. Disabled all extensions, only keep python and gitlens, open a simple test file. Mouse hover on some keywords, it will show "Loading...", then, type "impu", intellisense will not complete the input.

**Comment by eamodio** [comment] 2018-09-28 03:42
I'm pretty sure this is related to https://github.com/eamodio/vscode-gitlens/issues/439.
Can you try to repeat your test after setting `"gitlens.codeLens.enabled": false` in your config? That will confirm my suspicions.

**Comment by eamodio** [comment] 2018-10-01 19:35
Can you please enable output channel logging by setting `"gitlens.outputLevel": "debug"` in your `settings.json`. This will enable logging to the *GitLens* channel in the *Output* pane. Once enabled, please attempt to reproduce the issue (if possible) and attach the log lines from the *GitLens* channel.

**Comment by Xekyo** [comment] 2018-10-02 02:33
This is just from running it about one minute, while trying to add a new line. It stutters and letters only appear delayed. In the log, I've replaced the project path and file path with placeholders, but I hope that works for you. Lemme know if you need more data or if I should be doing something differently. Thank you for looking into this.

**Comment by eamodio** [comment] 2018-10-02 03:19
How big is the file you are editing? Is the slowness only with that (or other large files)? Do you see the same behavior with small files?

**Comment by Xekyo** [comment] 2018-10-02 18:59
The file is about 4000 LOC. The effect is indeed a lot less pronounced on a smaller file.

**Comment by eamodio** [comment] 2018-10-02 20:31
Do you have `"files.autoSave": "afterDelay"` and `files.autoSaveDelay` set to a short interval?

**Comment by Xekyo** [comment] 2018-10-03 19:16
My Auto Save is off. But, how would saving my file change the blame? Wouldn't that only be impacted by a git operation such as commit, pull or rebase? So, why would blame rerun on saving?
Ah, maybe because the lines shifted?

**Comment by Xekyo** [comment] 2018-10-03 19:38
I'm very sorry.

I was trying to reproduce the issue with GitLens 9.0.0-alpha and went about deactivating various plugins (again). It seems that I may have misattributed the slowdown. The slowdown problem gets also significantly better when I deactivate the CodeMetrics plugin. I think it may be the combination of the two running at similar times, or just the CodeMetrics plugin that is causing the brunt of the slowdown.

Thank you for looking into this, I will try running my VSCode for a while without CM and then will report back whether I still experience this issue at all.

**Comment by eamodio** [comment] 2018-10-03 20:36
Yeah, I try to recalculate the blame with the edits so that all the blame information is correct.

No problem at all -- glad you've found a possible explanation for it. Please report back after you've been using it for a while -- I'm very curious as to what the performance issue is (other than just competing calculations)

**Comment by eamodio** [comment] 2018-11-11 06:56
I am closing this issue because it needs more information and has not had recent activity.  Please re-open this issue when more details can be provided.

Thanks!

**Closed by eamodio** 2018-11-11 06:56 UTC
Labels: needs more info

**Comment by Xekyo** [comment] 2018-11-21 23:52
Sorry for the late follow-up: I've not had any issues since disabling the CodeMetrics plugin. Thanks!
