### ISSUE TITLE
Python file scrolling

### ISSUE THREAD

**Issue by namzat** [eamodio/vscode-gitlens#17] opened 2016-11-17 20:31 UTC
In a python file, if there is gitlens stuff showing and I type in the file, the page scrolls up a little each time I press a key.  When at the top it bounces a little.  I'm currently using

_VS Code Version 1.8.0-insider
Commit 043310affe454f94c665494b77818c1425cbe8db
Date 2016-11-17T12:27:28.054Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0_

_GitLens 1.0.2_

This looks like if may be along the same line as closed issue #9 .

**Comment by depl0y** [comment] 2016-11-18 14:54
This isn't only with python, having the same problem with VS Code 1.7.1, Gitlens 1.0.2 and Typescript files.

**Comment by eamodio** [comment] 2016-11-26 16:07
@namzat @depl0y is this only reproducible for you if the first line in the file is blank? I can't reproduce it otherwise.

If so, this is a vscode bug see: https://github.com/eamodio/vscode-gitlens/issues/19

**Comment by eamodio** [comment] 2016-12-05 20:52
I'm assuming this is the same as #19 -- closing. Please let me know if it isn't.

**Closed by eamodio** 2016-12-05 20:52 UTC
