### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ravihara** [eamodio/vscode-gitlens#638] opened 2019-01-28 08:42 UTC
[eamodio.gitlens-unresponsive.cpuprofile.txt](https://github.com/eamodio/vscode-gitlens/files/2802055/eamodio.gitlens-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `gitlens`
- Extension Version: `9.4.1`
- OS Version: `Linux x64 4.15.0-43-generic`
- VSCode version: `1.30.2`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by eamodio** [comment] 2019-09-25 16:54
Closing because this is quite old. If this can be reproduced on GitLens 10 please re-open.

**Closed by eamodio** 2019-09-25 16:54 UTC
Labels: type: potential bug
