### ISSUE TITLE
add option to 'ignore' an array of commit id in line blame

### ISSUE THREAD

**Issue by a7madgamal** [eamodio/vscode-gitlens#592] opened 2018-12-12 10:17 UTC
in line blame feature is amazing and I use it all the time. However, some commits like changing the formatting of the codebase will be in your face.
would be great if we can ignore some commits and show their parent commits as the blame result

**Comment by a7madgamal** [comment] 2018-12-12 10:20
something like this https://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/git-hyper-blame.html

**Comment by eamodio** [comment] 2018-12-12 16:40
Duplicate of https://github.com/eamodio/vscode-gitlens/issues/413

**Closed by eamodio** 2018-12-12 16:40 UTC
Labels: duplicate
