### ISSUE TITLE
Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false for-each-ref --format=%3ch%3e%(HEAD)%3cn%3e%(refname:lstrip=1)%3cu%3e%(upstream:short)%3ct%3e%(upstream:track)%3cr%3e%(objectname) refs/heads refs/remotes fatal: unknown refname: format lstrip=1

### ISSUE THREAD

**Issue by weiguoquan422** [eamodio/vscode-gitlens#742] opened 2019-05-08 10:49 UTC
- GitLens Version: 9.7.1
  
- VSCode Version: 1.33.1
- OS Version: debian9

Steps to Reproduce:

1. when I click master or Branches tree to expand them,
there is a error pop up
Command failed: /usr/bin/git -c core.quotepath=false -c color.ui=false for-each-ref --format=%3ch%3e%(HEAD)%3cn%3e%(refname:lstrip=1)%3cu%3e%(upstream:short)%3ct%3e%(upstream:track)%3cr%3e%(objectname) refs/heads refs/remotes
fatal: unknown refname: format lstrip=1

**Comment by weiguoquan422** [comment] 2019-05-08 10:52
Also, I can't view master and Branches tree. There's nothing there.

**Comment by Cheng-Ya** [comment] 2019-05-09 01:52
> I install version 9.6.3, No problem.
> And version 9.7.1, 9.7.0, both have this problem.

me too

**Comment by stevenventimiglia** [comment] 2019-05-09 05:31
Seems related to `[branch "master"]` referring to multiple repos, in my case.  I have three repos in tandem as `[remote "all"]`.  In `[branch "master"]`, when I use `remote = all`, it fails.  When I target any of the three individually, (ex. `remote = origin`, `remote = github`, `remote = bitbucket`), there is no error.  However, that is not a fix.

**Comment by LachlanArthur** [comment] 2019-05-10 01:33
The error "fatal: unknown refname: format lstrip=1" is likely because git is outdated.

My git version was 2.7, and this issue was resolved by upgrading (to 2.21 at the time of this comment).

**Comment by eamodio** [comment] 2019-05-10 20:38
Duplicate of #737

**Closed by eamodio** 2019-05-10 20:38 UTC
Labels: type: bug

**Comment by ifinik** [comment] 2019-05-10 20:42
duplicate of 737, that duplicate if this
wat?
