### ISSUE TITLE
Disable the "What's new" notification spam

### ISSUE THREAD

**Issue by tuxracer** [eamodio/vscode-gitlens#752] opened 2019-05-22 21:01 UTC
Can we please disable this entirely? Not a lot of examples of this type of notification spam from other extension. Really appreciate all the hard work that goes into this extension but this really feels like an abuse of the vscode notification system.

**Comment by eamodio** [comment] 2019-05-22 21:14
Duplicate of #738

**Closed by eamodio** 2019-05-22 21:14 UTC
